site_name: Workflows v2.0.4+20210318
site_url: http://byron.github.io/google-apis-rs/google-workflows1-cli
site_description: A complete library to interact with Workflows (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/workflows1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_locations-get.md', 'Projects', 'Locations Get']
- ['projects_locations-list.md', 'Projects', 'Locations List']
- ['projects_locations-operations-delete.md', 'Projects', 'Locations Operations Delete']
- ['projects_locations-operations-get.md', 'Projects', 'Locations Operations Get']
- ['projects_locations-operations-list.md', 'Projects', 'Locations Operations List']
- ['projects_locations-workflows-create.md', 'Projects', 'Locations Workflows Create']
- ['projects_locations-workflows-delete.md', 'Projects', 'Locations Workflows Delete']
- ['projects_locations-workflows-get.md', 'Projects', 'Locations Workflows Get']
- ['projects_locations-workflows-list.md', 'Projects', 'Locations Workflows List']
- ['projects_locations-workflows-patch.md', 'Projects', 'Locations Workflows Patch']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

