site_name: GKE Hub v2.0.3+20210322
site_url: http://byron.github.io/google-apis-rs/google-gkehub1-cli
site_description: A complete library to interact with GKE Hub (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/gkehub1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_locations-get.md', 'Projects', 'Locations Get']
- ['projects_locations-list.md', 'Projects', 'Locations List']
- ['projects_locations-memberships-create.md', 'Projects', 'Locations Memberships Create']
- ['projects_locations-memberships-delete.md', 'Projects', 'Locations Memberships Delete']
- ['projects_locations-memberships-generate-connect-manifest.md', 'Projects', 'Locations Memberships Generate Connect Manifest']
- ['projects_locations-memberships-get.md', 'Projects', 'Locations Memberships Get']
- ['projects_locations-memberships-get-iam-policy.md', 'Projects', 'Locations Memberships Get Iam Policy']
- ['projects_locations-memberships-list.md', 'Projects', 'Locations Memberships List']
- ['projects_locations-memberships-patch.md', 'Projects', 'Locations Memberships Patch']
- ['projects_locations-memberships-set-iam-policy.md', 'Projects', 'Locations Memberships Set Iam Policy']
- ['projects_locations-memberships-test-iam-permissions.md', 'Projects', 'Locations Memberships Test Iam Permissions']
- ['projects_locations-operations-cancel.md', 'Projects', 'Locations Operations Cancel']
- ['projects_locations-operations-delete.md', 'Projects', 'Locations Operations Delete']
- ['projects_locations-operations-get.md', 'Projects', 'Locations Operations Get']
- ['projects_locations-operations-list.md', 'Projects', 'Locations Operations List']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

