site_name: Policy Troubleshooter v2.0.3+20210329
site_url: http://byron.github.io/google-apis-rs/google-policytroubleshooter1-cli
site_description: A complete library to interact with Policy Troubleshooter (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/policytroubleshooter1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['iam_troubleshoot.md', 'Iam', 'Troubleshoot']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

