site_name: Fact Check Tools v2.0.4+20210330
site_url: http://byron.github.io/google-apis-rs/google-factchecktools1_alpha1-cli
site_description: A complete library to interact with Fact Check Tools (protocol v1alpha1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/factchecktools1_alpha1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['claims_search.md', 'Claims', 'Search']
- ['pages_create.md', 'Pages', 'Create']
- ['pages_delete.md', 'Pages', 'Delete']
- ['pages_get.md', 'Pages', 'Get']
- ['pages_list.md', 'Pages', 'List']
- ['pages_update.md', 'Pages', 'Update']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

