site_name: Logging v5.0.5+20240531
site_url: http://byron.github.io/google-apis-rs/google-logging2-cli
site_description: A complete library to interact with Logging (protocol v2)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/logging2-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Billing Accounts':
    - 'Exclusions Create': 'billing-accounts_exclusions-create.md'
    - 'Exclusions Delete': 'billing-accounts_exclusions-delete.md'
    - 'Exclusions Get': 'billing-accounts_exclusions-get.md'
    - 'Exclusions List': 'billing-accounts_exclusions-list.md'
    - 'Exclusions Patch': 'billing-accounts_exclusions-patch.md'
    - 'Get Cmek Settings': 'billing-accounts_get-cmek-settings.md'
    - 'Get Settings': 'billing-accounts_get-settings.md'
    - 'Locations Buckets Create': 'billing-accounts_locations-buckets-create.md'
    - 'Locations Buckets Create Async': 'billing-accounts_locations-buckets-create-async.md'
    - 'Locations Buckets Delete': 'billing-accounts_locations-buckets-delete.md'
    - 'Locations Buckets Get': 'billing-accounts_locations-buckets-get.md'
    - 'Locations Buckets Links Create': 'billing-accounts_locations-buckets-links-create.md'
    - 'Locations Buckets Links Delete': 'billing-accounts_locations-buckets-links-delete.md'
    - 'Locations Buckets Links Get': 'billing-accounts_locations-buckets-links-get.md'
    - 'Locations Buckets Links List': 'billing-accounts_locations-buckets-links-list.md'
    - 'Locations Buckets List': 'billing-accounts_locations-buckets-list.md'
    - 'Locations Buckets Patch': 'billing-accounts_locations-buckets-patch.md'
    - 'Locations Buckets Undelete': 'billing-accounts_locations-buckets-undelete.md'
    - 'Locations Buckets Update Async': 'billing-accounts_locations-buckets-update-async.md'
    - 'Locations Buckets Views Create': 'billing-accounts_locations-buckets-views-create.md'
    - 'Locations Buckets Views Delete': 'billing-accounts_locations-buckets-views-delete.md'
    - 'Locations Buckets Views Get': 'billing-accounts_locations-buckets-views-get.md'
    - 'Locations Buckets Views List': 'billing-accounts_locations-buckets-views-list.md'
    - 'Locations Buckets Views Logs List': 'billing-accounts_locations-buckets-views-logs-list.md'
    - 'Locations Buckets Views Patch': 'billing-accounts_locations-buckets-views-patch.md'
    - 'Locations Get': 'billing-accounts_locations-get.md'
    - 'Locations List': 'billing-accounts_locations-list.md'
    - 'Locations Operations Cancel': 'billing-accounts_locations-operations-cancel.md'
    - 'Locations Operations Get': 'billing-accounts_locations-operations-get.md'
    - 'Locations Operations List': 'billing-accounts_locations-operations-list.md'
    - 'Locations Recent Queries List': 'billing-accounts_locations-recent-queries-list.md'
    - 'Locations Saved Queries Create': 'billing-accounts_locations-saved-queries-create.md'
    - 'Locations Saved Queries Delete': 'billing-accounts_locations-saved-queries-delete.md'
    - 'Locations Saved Queries List': 'billing-accounts_locations-saved-queries-list.md'
    - 'Logs Delete': 'billing-accounts_logs-delete.md'
    - 'Logs List': 'billing-accounts_logs-list.md'
    - 'Sinks Create': 'billing-accounts_sinks-create.md'
    - 'Sinks Delete': 'billing-accounts_sinks-delete.md'
    - 'Sinks Get': 'billing-accounts_sinks-get.md'
    - 'Sinks List': 'billing-accounts_sinks-list.md'
    - 'Sinks Patch': 'billing-accounts_sinks-patch.md'
    - 'Sinks Update': 'billing-accounts_sinks-update.md'
- 'Entries':
    - 'Copy': 'entries_copy.md'
    - 'List': 'entries_list.md'
    - 'Tail': 'entries_tail.md'
    - 'Write': 'entries_write.md'
- 'Exclusions':
    - 'Create': 'exclusions_create.md'
    - 'Delete': 'exclusions_delete.md'
    - 'Get': 'exclusions_get.md'
    - 'List': 'exclusions_list.md'
    - 'Patch': 'exclusions_patch.md'
- 'Folders':
    - 'Exclusions Create': 'folders_exclusions-create.md'
    - 'Exclusions Delete': 'folders_exclusions-delete.md'
    - 'Exclusions Get': 'folders_exclusions-get.md'
    - 'Exclusions List': 'folders_exclusions-list.md'
    - 'Exclusions Patch': 'folders_exclusions-patch.md'
    - 'Get Cmek Settings': 'folders_get-cmek-settings.md'
    - 'Get Settings': 'folders_get-settings.md'
    - 'Locations Buckets Create': 'folders_locations-buckets-create.md'
    - 'Locations Buckets Create Async': 'folders_locations-buckets-create-async.md'
    - 'Locations Buckets Delete': 'folders_locations-buckets-delete.md'
    - 'Locations Buckets Get': 'folders_locations-buckets-get.md'
    - 'Locations Buckets Links Create': 'folders_locations-buckets-links-create.md'
    - 'Locations Buckets Links Delete': 'folders_locations-buckets-links-delete.md'
    - 'Locations Buckets Links Get': 'folders_locations-buckets-links-get.md'
    - 'Locations Buckets Links List': 'folders_locations-buckets-links-list.md'
    - 'Locations Buckets List': 'folders_locations-buckets-list.md'
    - 'Locations Buckets Patch': 'folders_locations-buckets-patch.md'
    - 'Locations Buckets Undelete': 'folders_locations-buckets-undelete.md'
    - 'Locations Buckets Update Async': 'folders_locations-buckets-update-async.md'
    - 'Locations Buckets Views Create': 'folders_locations-buckets-views-create.md'
    - 'Locations Buckets Views Delete': 'folders_locations-buckets-views-delete.md'
    - 'Locations Buckets Views Get': 'folders_locations-buckets-views-get.md'
    - 'Locations Buckets Views Get Iam Policy': 'folders_locations-buckets-views-get-iam-policy.md'
    - 'Locations Buckets Views List': 'folders_locations-buckets-views-list.md'
    - 'Locations Buckets Views Logs List': 'folders_locations-buckets-views-logs-list.md'
    - 'Locations Buckets Views Patch': 'folders_locations-buckets-views-patch.md'
    - 'Locations Buckets Views Set Iam Policy': 'folders_locations-buckets-views-set-iam-policy.md'
    - 'Locations Buckets Views Test Iam Permissions': 'folders_locations-buckets-views-test-iam-permissions.md'
    - 'Locations Get': 'folders_locations-get.md'
    - 'Locations List': 'folders_locations-list.md'
    - 'Locations Operations Cancel': 'folders_locations-operations-cancel.md'
    - 'Locations Operations Get': 'folders_locations-operations-get.md'
    - 'Locations Operations List': 'folders_locations-operations-list.md'
    - 'Locations Recent Queries List': 'folders_locations-recent-queries-list.md'
    - 'Locations Saved Queries Create': 'folders_locations-saved-queries-create.md'
    - 'Locations Saved Queries Delete': 'folders_locations-saved-queries-delete.md'
    - 'Locations Saved Queries List': 'folders_locations-saved-queries-list.md'
    - 'Logs Delete': 'folders_logs-delete.md'
    - 'Logs List': 'folders_logs-list.md'
    - 'Sinks Create': 'folders_sinks-create.md'
    - 'Sinks Delete': 'folders_sinks-delete.md'
    - 'Sinks Get': 'folders_sinks-get.md'
    - 'Sinks List': 'folders_sinks-list.md'
    - 'Sinks Patch': 'folders_sinks-patch.md'
    - 'Sinks Update': 'folders_sinks-update.md'
    - 'Update Settings': 'folders_update-settings.md'
- 'Locations':
    - 'Buckets Create': 'locations_buckets-create.md'
    - 'Buckets Create Async': 'locations_buckets-create-async.md'
    - 'Buckets Delete': 'locations_buckets-delete.md'
    - 'Buckets Get': 'locations_buckets-get.md'
    - 'Buckets Links Create': 'locations_buckets-links-create.md'
    - 'Buckets Links Delete': 'locations_buckets-links-delete.md'
    - 'Buckets Links Get': 'locations_buckets-links-get.md'
    - 'Buckets Links List': 'locations_buckets-links-list.md'
    - 'Buckets List': 'locations_buckets-list.md'
    - 'Buckets Patch': 'locations_buckets-patch.md'
    - 'Buckets Undelete': 'locations_buckets-undelete.md'
    - 'Buckets Update Async': 'locations_buckets-update-async.md'
    - 'Buckets Views Create': 'locations_buckets-views-create.md'
    - 'Buckets Views Delete': 'locations_buckets-views-delete.md'
    - 'Buckets Views Get': 'locations_buckets-views-get.md'
    - 'Buckets Views Get Iam Policy': 'locations_buckets-views-get-iam-policy.md'
    - 'Buckets Views List': 'locations_buckets-views-list.md'
    - 'Buckets Views Patch': 'locations_buckets-views-patch.md'
    - 'Buckets Views Set Iam Policy': 'locations_buckets-views-set-iam-policy.md'
    - 'Buckets Views Test Iam Permissions': 'locations_buckets-views-test-iam-permissions.md'
    - 'Get': 'locations_get.md'
    - 'List': 'locations_list.md'
    - 'Operations Cancel': 'locations_operations-cancel.md'
    - 'Operations Get': 'locations_operations-get.md'
    - 'Operations List': 'locations_operations-list.md'
- 'Logs':
    - 'Delete': 'logs_delete.md'
    - 'List': 'logs_list.md'
- 'Methods':
    - 'Get Cmek Settings': 'methods_get-cmek-settings.md'
    - 'Get Settings': 'methods_get-settings.md'
    - 'Update Cmek Settings': 'methods_update-cmek-settings.md'
    - 'Update Settings': 'methods_update-settings.md'
- 'Monitored Resource Descriptors':
    - 'List': 'monitored-resource-descriptors_list.md'
- 'Organizations':
    - 'Exclusions Create': 'organizations_exclusions-create.md'
    - 'Exclusions Delete': 'organizations_exclusions-delete.md'
    - 'Exclusions Get': 'organizations_exclusions-get.md'
    - 'Exclusions List': 'organizations_exclusions-list.md'
    - 'Exclusions Patch': 'organizations_exclusions-patch.md'
    - 'Get Cmek Settings': 'organizations_get-cmek-settings.md'
    - 'Get Settings': 'organizations_get-settings.md'
    - 'Locations Buckets Create': 'organizations_locations-buckets-create.md'
    - 'Locations Buckets Create Async': 'organizations_locations-buckets-create-async.md'
    - 'Locations Buckets Delete': 'organizations_locations-buckets-delete.md'
    - 'Locations Buckets Get': 'organizations_locations-buckets-get.md'
    - 'Locations Buckets Links Create': 'organizations_locations-buckets-links-create.md'
    - 'Locations Buckets Links Delete': 'organizations_locations-buckets-links-delete.md'
    - 'Locations Buckets Links Get': 'organizations_locations-buckets-links-get.md'
    - 'Locations Buckets Links List': 'organizations_locations-buckets-links-list.md'
    - 'Locations Buckets List': 'organizations_locations-buckets-list.md'
    - 'Locations Buckets Patch': 'organizations_locations-buckets-patch.md'
    - 'Locations Buckets Undelete': 'organizations_locations-buckets-undelete.md'
    - 'Locations Buckets Update Async': 'organizations_locations-buckets-update-async.md'
    - 'Locations Buckets Views Create': 'organizations_locations-buckets-views-create.md'
    - 'Locations Buckets Views Delete': 'organizations_locations-buckets-views-delete.md'
    - 'Locations Buckets Views Get': 'organizations_locations-buckets-views-get.md'
    - 'Locations Buckets Views Get Iam Policy': 'organizations_locations-buckets-views-get-iam-policy.md'
    - 'Locations Buckets Views List': 'organizations_locations-buckets-views-list.md'
    - 'Locations Buckets Views Logs List': 'organizations_locations-buckets-views-logs-list.md'
    - 'Locations Buckets Views Patch': 'organizations_locations-buckets-views-patch.md'
    - 'Locations Buckets Views Set Iam Policy': 'organizations_locations-buckets-views-set-iam-policy.md'
    - 'Locations Buckets Views Test Iam Permissions': 'organizations_locations-buckets-views-test-iam-permissions.md'
    - 'Locations Get': 'organizations_locations-get.md'
    - 'Locations List': 'organizations_locations-list.md'
    - 'Locations Operations Cancel': 'organizations_locations-operations-cancel.md'
    - 'Locations Operations Get': 'organizations_locations-operations-get.md'
    - 'Locations Operations List': 'organizations_locations-operations-list.md'
    - 'Locations Recent Queries List': 'organizations_locations-recent-queries-list.md'
    - 'Locations Saved Queries Create': 'organizations_locations-saved-queries-create.md'
    - 'Locations Saved Queries Delete': 'organizations_locations-saved-queries-delete.md'
    - 'Locations Saved Queries List': 'organizations_locations-saved-queries-list.md'
    - 'Logs Delete': 'organizations_logs-delete.md'
    - 'Logs List': 'organizations_logs-list.md'
    - 'Sinks Create': 'organizations_sinks-create.md'
    - 'Sinks Delete': 'organizations_sinks-delete.md'
    - 'Sinks Get': 'organizations_sinks-get.md'
    - 'Sinks List': 'organizations_sinks-list.md'
    - 'Sinks Patch': 'organizations_sinks-patch.md'
    - 'Sinks Update': 'organizations_sinks-update.md'
    - 'Update Cmek Settings': 'organizations_update-cmek-settings.md'
    - 'Update Settings': 'organizations_update-settings.md'
- 'Projects':
    - 'Exclusions Create': 'projects_exclusions-create.md'
    - 'Exclusions Delete': 'projects_exclusions-delete.md'
    - 'Exclusions Get': 'projects_exclusions-get.md'
    - 'Exclusions List': 'projects_exclusions-list.md'
    - 'Exclusions Patch': 'projects_exclusions-patch.md'
    - 'Get Cmek Settings': 'projects_get-cmek-settings.md'
    - 'Get Settings': 'projects_get-settings.md'
    - 'Locations Buckets Create': 'projects_locations-buckets-create.md'
    - 'Locations Buckets Create Async': 'projects_locations-buckets-create-async.md'
    - 'Locations Buckets Delete': 'projects_locations-buckets-delete.md'
    - 'Locations Buckets Get': 'projects_locations-buckets-get.md'
    - 'Locations Buckets Links Create': 'projects_locations-buckets-links-create.md'
    - 'Locations Buckets Links Delete': 'projects_locations-buckets-links-delete.md'
    - 'Locations Buckets Links Get': 'projects_locations-buckets-links-get.md'
    - 'Locations Buckets Links List': 'projects_locations-buckets-links-list.md'
    - 'Locations Buckets List': 'projects_locations-buckets-list.md'
    - 'Locations Buckets Patch': 'projects_locations-buckets-patch.md'
    - 'Locations Buckets Undelete': 'projects_locations-buckets-undelete.md'
    - 'Locations Buckets Update Async': 'projects_locations-buckets-update-async.md'
    - 'Locations Buckets Views Create': 'projects_locations-buckets-views-create.md'
    - 'Locations Buckets Views Delete': 'projects_locations-buckets-views-delete.md'
    - 'Locations Buckets Views Get': 'projects_locations-buckets-views-get.md'
    - 'Locations Buckets Views Get Iam Policy': 'projects_locations-buckets-views-get-iam-policy.md'
    - 'Locations Buckets Views List': 'projects_locations-buckets-views-list.md'
    - 'Locations Buckets Views Logs List': 'projects_locations-buckets-views-logs-list.md'
    - 'Locations Buckets Views Patch': 'projects_locations-buckets-views-patch.md'
    - 'Locations Buckets Views Set Iam Policy': 'projects_locations-buckets-views-set-iam-policy.md'
    - 'Locations Buckets Views Test Iam Permissions': 'projects_locations-buckets-views-test-iam-permissions.md'
    - 'Locations Get': 'projects_locations-get.md'
    - 'Locations List': 'projects_locations-list.md'
    - 'Locations Operations Cancel': 'projects_locations-operations-cancel.md'
    - 'Locations Operations Get': 'projects_locations-operations-get.md'
    - 'Locations Operations List': 'projects_locations-operations-list.md'
    - 'Locations Recent Queries List': 'projects_locations-recent-queries-list.md'
    - 'Locations Saved Queries Create': 'projects_locations-saved-queries-create.md'
    - 'Locations Saved Queries Delete': 'projects_locations-saved-queries-delete.md'
    - 'Locations Saved Queries List': 'projects_locations-saved-queries-list.md'
    - 'Logs Delete': 'projects_logs-delete.md'
    - 'Logs List': 'projects_logs-list.md'
    - 'Metrics Create': 'projects_metrics-create.md'
    - 'Metrics Delete': 'projects_metrics-delete.md'
    - 'Metrics Get': 'projects_metrics-get.md'
    - 'Metrics List': 'projects_metrics-list.md'
    - 'Metrics Update': 'projects_metrics-update.md'
    - 'Sinks Create': 'projects_sinks-create.md'
    - 'Sinks Delete': 'projects_sinks-delete.md'
    - 'Sinks Get': 'projects_sinks-get.md'
    - 'Sinks List': 'projects_sinks-list.md'
    - 'Sinks Patch': 'projects_sinks-patch.md'
    - 'Sinks Update': 'projects_sinks-update.md'
- 'Sinks':
    - 'Create': 'sinks_create.md'
    - 'Delete': 'sinks_delete.md'
    - 'Get': 'sinks_get.md'
    - 'List': 'sinks_list.md'
    - 'Update': 'sinks_update.md'

theme: readthedocs

copyright: Copyright &copy; 2015â€“2024, `Sebastian Thiel`

