site_name: Logging v2.0.5+20210325
site_url: http://byron.github.io/google-apis-rs/google-logging2-cli
site_description: A complete library to interact with Logging (protocol v2)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/logging2-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['billing-accounts_buckets-get.md', 'Billing Accounts', 'Buckets Get']
- ['billing-accounts_buckets-views-get.md', 'Billing Accounts', 'Buckets Views Get']
- ['billing-accounts_exclusions-create.md', 'Billing Accounts', 'Exclusions Create']
- ['billing-accounts_exclusions-delete.md', 'Billing Accounts', 'Exclusions Delete']
- ['billing-accounts_exclusions-get.md', 'Billing Accounts', 'Exclusions Get']
- ['billing-accounts_exclusions-list.md', 'Billing Accounts', 'Exclusions List']
- ['billing-accounts_exclusions-patch.md', 'Billing Accounts', 'Exclusions Patch']
- ['billing-accounts_locations-buckets-create.md', 'Billing Accounts', 'Locations Buckets Create']
- ['billing-accounts_locations-buckets-delete.md', 'Billing Accounts', 'Locations Buckets Delete']
- ['billing-accounts_locations-buckets-list.md', 'Billing Accounts', 'Locations Buckets List']
- ['billing-accounts_locations-buckets-patch.md', 'Billing Accounts', 'Locations Buckets Patch']
- ['billing-accounts_locations-buckets-undelete.md', 'Billing Accounts', 'Locations Buckets Undelete']
- ['billing-accounts_locations-buckets-views-create.md', 'Billing Accounts', 'Locations Buckets Views Create']
- ['billing-accounts_locations-buckets-views-delete.md', 'Billing Accounts', 'Locations Buckets Views Delete']
- ['billing-accounts_locations-buckets-views-list.md', 'Billing Accounts', 'Locations Buckets Views List']
- ['billing-accounts_locations-buckets-views-patch.md', 'Billing Accounts', 'Locations Buckets Views Patch']
- ['billing-accounts_locations-get.md', 'Billing Accounts', 'Locations Get']
- ['billing-accounts_locations-list.md', 'Billing Accounts', 'Locations List']
- ['billing-accounts_logs-delete.md', 'Billing Accounts', 'Logs Delete']
- ['billing-accounts_logs-list.md', 'Billing Accounts', 'Logs List']
- ['billing-accounts_sinks-create.md', 'Billing Accounts', 'Sinks Create']
- ['billing-accounts_sinks-delete.md', 'Billing Accounts', 'Sinks Delete']
- ['billing-accounts_sinks-get.md', 'Billing Accounts', 'Sinks Get']
- ['billing-accounts_sinks-list.md', 'Billing Accounts', 'Sinks List']
- ['billing-accounts_sinks-patch.md', 'Billing Accounts', 'Sinks Patch']
- ['billing-accounts_sinks-update.md', 'Billing Accounts', 'Sinks Update']
- ['entries_list.md', 'Entries', 'List']
- ['entries_tail.md', 'Entries', 'Tail']
- ['entries_write.md', 'Entries', 'Write']
- ['exclusions_create.md', 'Exclusions', 'Create']
- ['exclusions_delete.md', 'Exclusions', 'Delete']
- ['exclusions_get.md', 'Exclusions', 'Get']
- ['exclusions_list.md', 'Exclusions', 'List']
- ['exclusions_patch.md', 'Exclusions', 'Patch']
- ['folders_exclusions-create.md', 'Folders', 'Exclusions Create']
- ['folders_exclusions-delete.md', 'Folders', 'Exclusions Delete']
- ['folders_exclusions-get.md', 'Folders', 'Exclusions Get']
- ['folders_exclusions-list.md', 'Folders', 'Exclusions List']
- ['folders_exclusions-patch.md', 'Folders', 'Exclusions Patch']
- ['folders_locations-buckets-create.md', 'Folders', 'Locations Buckets Create']
- ['folders_locations-buckets-delete.md', 'Folders', 'Locations Buckets Delete']
- ['folders_locations-buckets-get.md', 'Folders', 'Locations Buckets Get']
- ['folders_locations-buckets-list.md', 'Folders', 'Locations Buckets List']
- ['folders_locations-buckets-patch.md', 'Folders', 'Locations Buckets Patch']
- ['folders_locations-buckets-undelete.md', 'Folders', 'Locations Buckets Undelete']
- ['folders_locations-buckets-views-create.md', 'Folders', 'Locations Buckets Views Create']
- ['folders_locations-buckets-views-delete.md', 'Folders', 'Locations Buckets Views Delete']
- ['folders_locations-buckets-views-get.md', 'Folders', 'Locations Buckets Views Get']
- ['folders_locations-buckets-views-list.md', 'Folders', 'Locations Buckets Views List']
- ['folders_locations-buckets-views-patch.md', 'Folders', 'Locations Buckets Views Patch']
- ['folders_locations-get.md', 'Folders', 'Locations Get']
- ['folders_locations-list.md', 'Folders', 'Locations List']
- ['folders_logs-delete.md', 'Folders', 'Logs Delete']
- ['folders_logs-list.md', 'Folders', 'Logs List']
- ['folders_sinks-create.md', 'Folders', 'Sinks Create']
- ['folders_sinks-delete.md', 'Folders', 'Sinks Delete']
- ['folders_sinks-get.md', 'Folders', 'Sinks Get']
- ['folders_sinks-list.md', 'Folders', 'Sinks List']
- ['folders_sinks-patch.md', 'Folders', 'Sinks Patch']
- ['folders_sinks-update.md', 'Folders', 'Sinks Update']
- ['locations_buckets-create.md', 'Locations', 'Buckets Create']
- ['locations_buckets-delete.md', 'Locations', 'Buckets Delete']
- ['locations_buckets-get.md', 'Locations', 'Buckets Get']
- ['locations_buckets-list.md', 'Locations', 'Buckets List']
- ['locations_buckets-patch.md', 'Locations', 'Buckets Patch']
- ['locations_buckets-undelete.md', 'Locations', 'Buckets Undelete']
- ['locations_buckets-views-create.md', 'Locations', 'Buckets Views Create']
- ['locations_buckets-views-delete.md', 'Locations', 'Buckets Views Delete']
- ['locations_buckets-views-get.md', 'Locations', 'Buckets Views Get']
- ['locations_buckets-views-list.md', 'Locations', 'Buckets Views List']
- ['locations_buckets-views-patch.md', 'Locations', 'Buckets Views Patch']
- ['locations_get.md', 'Locations', 'Get']
- ['locations_list.md', 'Locations', 'List']
- ['logs_delete.md', 'Logs', 'Delete']
- ['logs_list.md', 'Logs', 'List']
- ['methods_get-cmek-settings.md', 'Methods', 'Get Cmek Settings']
- ['methods_update-cmek-settings.md', 'Methods', 'Update Cmek Settings']
- ['monitored-resource-descriptors_list.md', 'Monitored Resource Descriptors', 'List']
- ['organizations_exclusions-create.md', 'Organizations', 'Exclusions Create']
- ['organizations_exclusions-delete.md', 'Organizations', 'Exclusions Delete']
- ['organizations_exclusions-get.md', 'Organizations', 'Exclusions Get']
- ['organizations_exclusions-list.md', 'Organizations', 'Exclusions List']
- ['organizations_exclusions-patch.md', 'Organizations', 'Exclusions Patch']
- ['organizations_get-cmek-settings.md', 'Organizations', 'Get Cmek Settings']
- ['organizations_locations-buckets-create.md', 'Organizations', 'Locations Buckets Create']
- ['organizations_locations-buckets-delete.md', 'Organizations', 'Locations Buckets Delete']
- ['organizations_locations-buckets-get.md', 'Organizations', 'Locations Buckets Get']
- ['organizations_locations-buckets-list.md', 'Organizations', 'Locations Buckets List']
- ['organizations_locations-buckets-patch.md', 'Organizations', 'Locations Buckets Patch']
- ['organizations_locations-buckets-undelete.md', 'Organizations', 'Locations Buckets Undelete']
- ['organizations_locations-buckets-views-create.md', 'Organizations', 'Locations Buckets Views Create']
- ['organizations_locations-buckets-views-delete.md', 'Organizations', 'Locations Buckets Views Delete']
- ['organizations_locations-buckets-views-get.md', 'Organizations', 'Locations Buckets Views Get']
- ['organizations_locations-buckets-views-list.md', 'Organizations', 'Locations Buckets Views List']
- ['organizations_locations-buckets-views-patch.md', 'Organizations', 'Locations Buckets Views Patch']
- ['organizations_locations-get.md', 'Organizations', 'Locations Get']
- ['organizations_locations-list.md', 'Organizations', 'Locations List']
- ['organizations_logs-delete.md', 'Organizations', 'Logs Delete']
- ['organizations_logs-list.md', 'Organizations', 'Logs List']
- ['organizations_sinks-create.md', 'Organizations', 'Sinks Create']
- ['organizations_sinks-delete.md', 'Organizations', 'Sinks Delete']
- ['organizations_sinks-get.md', 'Organizations', 'Sinks Get']
- ['organizations_sinks-list.md', 'Organizations', 'Sinks List']
- ['organizations_sinks-patch.md', 'Organizations', 'Sinks Patch']
- ['organizations_sinks-update.md', 'Organizations', 'Sinks Update']
- ['organizations_update-cmek-settings.md', 'Organizations', 'Update Cmek Settings']
- ['projects_exclusions-create.md', 'Projects', 'Exclusions Create']
- ['projects_exclusions-delete.md', 'Projects', 'Exclusions Delete']
- ['projects_exclusions-get.md', 'Projects', 'Exclusions Get']
- ['projects_exclusions-list.md', 'Projects', 'Exclusions List']
- ['projects_exclusions-patch.md', 'Projects', 'Exclusions Patch']
- ['projects_locations-buckets-create.md', 'Projects', 'Locations Buckets Create']
- ['projects_locations-buckets-delete.md', 'Projects', 'Locations Buckets Delete']
- ['projects_locations-buckets-get.md', 'Projects', 'Locations Buckets Get']
- ['projects_locations-buckets-list.md', 'Projects', 'Locations Buckets List']
- ['projects_locations-buckets-patch.md', 'Projects', 'Locations Buckets Patch']
- ['projects_locations-buckets-undelete.md', 'Projects', 'Locations Buckets Undelete']
- ['projects_locations-buckets-views-create.md', 'Projects', 'Locations Buckets Views Create']
- ['projects_locations-buckets-views-delete.md', 'Projects', 'Locations Buckets Views Delete']
- ['projects_locations-buckets-views-get.md', 'Projects', 'Locations Buckets Views Get']
- ['projects_locations-buckets-views-list.md', 'Projects', 'Locations Buckets Views List']
- ['projects_locations-buckets-views-patch.md', 'Projects', 'Locations Buckets Views Patch']
- ['projects_locations-get.md', 'Projects', 'Locations Get']
- ['projects_locations-list.md', 'Projects', 'Locations List']
- ['projects_logs-delete.md', 'Projects', 'Logs Delete']
- ['projects_logs-list.md', 'Projects', 'Logs List']
- ['projects_metrics-create.md', 'Projects', 'Metrics Create']
- ['projects_metrics-delete.md', 'Projects', 'Metrics Delete']
- ['projects_metrics-get.md', 'Projects', 'Metrics Get']
- ['projects_metrics-list.md', 'Projects', 'Metrics List']
- ['projects_metrics-update.md', 'Projects', 'Metrics Update']
- ['projects_sinks-create.md', 'Projects', 'Sinks Create']
- ['projects_sinks-delete.md', 'Projects', 'Sinks Delete']
- ['projects_sinks-get.md', 'Projects', 'Sinks Get']
- ['projects_sinks-list.md', 'Projects', 'Sinks List']
- ['projects_sinks-patch.md', 'Projects', 'Sinks Patch']
- ['projects_sinks-update.md', 'Projects', 'Sinks Update']
- ['sinks_create.md', 'Sinks', 'Create']
- ['sinks_delete.md', 'Sinks', 'Delete']
- ['sinks_get.md', 'Sinks', 'Get']
- ['sinks_list.md', 'Sinks', 'List']
- ['sinks_update.md', 'Sinks', 'Update']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

