site_name: Games v2.0.0+20210325
site_url: http://byron.github.io/google-apis-rs/google-games1-cli
site_description: A complete library to interact with Games (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/games1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['achievement-definitions_list.md', 'Achievement Definitions', 'List']
- ['achievements_increment.md', 'Achievements', 'Increment']
- ['achievements_list.md', 'Achievements', 'List']
- ['achievements_reveal.md', 'Achievements', 'Reveal']
- ['achievements_set-steps-at-least.md', 'Achievements', 'Set Steps At Least']
- ['achievements_unlock.md', 'Achievements', 'Unlock']
- ['achievements_update-multiple.md', 'Achievements', 'Update Multiple']
- ['applications_get.md', 'Applications', 'Get']
- ['applications_get-end-point.md', 'Applications', 'Get End Point']
- ['applications_played.md', 'Applications', 'Played']
- ['applications_verify.md', 'Applications', 'Verify']
- ['events_list-by-player.md', 'Events', 'List By Player']
- ['events_list-definitions.md', 'Events', 'List Definitions']
- ['events_record.md', 'Events', 'Record']
- ['leaderboards_get.md', 'Leaderboards', 'Get']
- ['leaderboards_list.md', 'Leaderboards', 'List']
- ['metagame_get-metagame-config.md', 'Metagame', 'Get Metagame Config']
- ['metagame_list-categories-by-player.md', 'Metagame', 'List Categories By Player']
- ['players_get.md', 'Players', 'Get']
- ['players_list.md', 'Players', 'List']
- ['revisions_check.md', 'Revisions', 'Check']
- ['scores_get.md', 'Scores', 'Get']
- ['scores_list.md', 'Scores', 'List']
- ['scores_list-window.md', 'Scores', 'List Window']
- ['scores_submit.md', 'Scores', 'Submit']
- ['scores_submit-multiple.md', 'Scores', 'Submit Multiple']
- ['snapshots_get.md', 'Snapshots', 'Get']
- ['snapshots_list.md', 'Snapshots', 'List']
- ['snapshots-extended_resolve-snapshot-head.md', 'Snapshots Extended', 'Resolve Snapshot Head']
- ['stats_get.md', 'Stats', 'Get']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

