site_name: NetworkServices v7.0.0+20251203
site_url: http://byron.github.io/google-apis-rs/google-networkservices1-cli
site_description: A complete library to interact with NetworkServices (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/networkservices1-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Projects':
    - 'Locations Authz Extensions Create': 'projects_locations-authz-extensions-create.md'
    - 'Locations Authz Extensions Delete': 'projects_locations-authz-extensions-delete.md'
    - 'Locations Authz Extensions Get': 'projects_locations-authz-extensions-get.md'
    - 'Locations Authz Extensions List': 'projects_locations-authz-extensions-list.md'
    - 'Locations Authz Extensions Patch': 'projects_locations-authz-extensions-patch.md'
    - 'Locations Edge Cache Keysets Get Iam Policy': 'projects_locations-edge-cache-keysets-get-iam-policy.md'
    - 'Locations Edge Cache Keysets Set Iam Policy': 'projects_locations-edge-cache-keysets-set-iam-policy.md'
    - 'Locations Edge Cache Keysets Test Iam Permissions': 'projects_locations-edge-cache-keysets-test-iam-permissions.md'
    - 'Locations Edge Cache Origins Get Iam Policy': 'projects_locations-edge-cache-origins-get-iam-policy.md'
    - 'Locations Edge Cache Origins Set Iam Policy': 'projects_locations-edge-cache-origins-set-iam-policy.md'
    - 'Locations Edge Cache Origins Test Iam Permissions': 'projects_locations-edge-cache-origins-test-iam-permissions.md'
    - 'Locations Edge Cache Services Get Iam Policy': 'projects_locations-edge-cache-services-get-iam-policy.md'
    - 'Locations Edge Cache Services Set Iam Policy': 'projects_locations-edge-cache-services-set-iam-policy.md'
    - 'Locations Edge Cache Services Test Iam Permissions': 'projects_locations-edge-cache-services-test-iam-permissions.md'
    - 'Locations Endpoint Policies Create': 'projects_locations-endpoint-policies-create.md'
    - 'Locations Endpoint Policies Delete': 'projects_locations-endpoint-policies-delete.md'
    - 'Locations Endpoint Policies Get': 'projects_locations-endpoint-policies-get.md'
    - 'Locations Endpoint Policies List': 'projects_locations-endpoint-policies-list.md'
    - 'Locations Endpoint Policies Patch': 'projects_locations-endpoint-policies-patch.md'
    - 'Locations Gateways Create': 'projects_locations-gateways-create.md'
    - 'Locations Gateways Delete': 'projects_locations-gateways-delete.md'
    - 'Locations Gateways Get': 'projects_locations-gateways-get.md'
    - 'Locations Gateways List': 'projects_locations-gateways-list.md'
    - 'Locations Gateways Patch': 'projects_locations-gateways-patch.md'
    - 'Locations Gateways Route Views Get': 'projects_locations-gateways-route-views-get.md'
    - 'Locations Gateways Route Views List': 'projects_locations-gateways-route-views-list.md'
    - 'Locations Get': 'projects_locations-get.md'
    - 'Locations Grpc Routes Create': 'projects_locations-grpc-routes-create.md'
    - 'Locations Grpc Routes Delete': 'projects_locations-grpc-routes-delete.md'
    - 'Locations Grpc Routes Get': 'projects_locations-grpc-routes-get.md'
    - 'Locations Grpc Routes List': 'projects_locations-grpc-routes-list.md'
    - 'Locations Grpc Routes Patch': 'projects_locations-grpc-routes-patch.md'
    - 'Locations Http Routes Create': 'projects_locations-http-routes-create.md'
    - 'Locations Http Routes Delete': 'projects_locations-http-routes-delete.md'
    - 'Locations Http Routes Get': 'projects_locations-http-routes-get.md'
    - 'Locations Http Routes List': 'projects_locations-http-routes-list.md'
    - 'Locations Http Routes Patch': 'projects_locations-http-routes-patch.md'
    - 'Locations Lb Edge Extensions Create': 'projects_locations-lb-edge-extensions-create.md'
    - 'Locations Lb Edge Extensions Delete': 'projects_locations-lb-edge-extensions-delete.md'
    - 'Locations Lb Edge Extensions Get': 'projects_locations-lb-edge-extensions-get.md'
    - 'Locations Lb Edge Extensions List': 'projects_locations-lb-edge-extensions-list.md'
    - 'Locations Lb Edge Extensions Patch': 'projects_locations-lb-edge-extensions-patch.md'
    - 'Locations Lb Route Extensions Create': 'projects_locations-lb-route-extensions-create.md'
    - 'Locations Lb Route Extensions Delete': 'projects_locations-lb-route-extensions-delete.md'
    - 'Locations Lb Route Extensions Get': 'projects_locations-lb-route-extensions-get.md'
    - 'Locations Lb Route Extensions List': 'projects_locations-lb-route-extensions-list.md'
    - 'Locations Lb Route Extensions Patch': 'projects_locations-lb-route-extensions-patch.md'
    - 'Locations Lb Traffic Extensions Create': 'projects_locations-lb-traffic-extensions-create.md'
    - 'Locations Lb Traffic Extensions Delete': 'projects_locations-lb-traffic-extensions-delete.md'
    - 'Locations Lb Traffic Extensions Get': 'projects_locations-lb-traffic-extensions-get.md'
    - 'Locations Lb Traffic Extensions List': 'projects_locations-lb-traffic-extensions-list.md'
    - 'Locations Lb Traffic Extensions Patch': 'projects_locations-lb-traffic-extensions-patch.md'
    - 'Locations List': 'projects_locations-list.md'
    - 'Locations Meshes Create': 'projects_locations-meshes-create.md'
    - 'Locations Meshes Delete': 'projects_locations-meshes-delete.md'
    - 'Locations Meshes Get': 'projects_locations-meshes-get.md'
    - 'Locations Meshes List': 'projects_locations-meshes-list.md'
    - 'Locations Meshes Patch': 'projects_locations-meshes-patch.md'
    - 'Locations Meshes Route Views Get': 'projects_locations-meshes-route-views-get.md'
    - 'Locations Meshes Route Views List': 'projects_locations-meshes-route-views-list.md'
    - 'Locations Operations Cancel': 'projects_locations-operations-cancel.md'
    - 'Locations Operations Delete': 'projects_locations-operations-delete.md'
    - 'Locations Operations Get': 'projects_locations-operations-get.md'
    - 'Locations Operations List': 'projects_locations-operations-list.md'
    - 'Locations Service Bindings Create': 'projects_locations-service-bindings-create.md'
    - 'Locations Service Bindings Delete': 'projects_locations-service-bindings-delete.md'
    - 'Locations Service Bindings Get': 'projects_locations-service-bindings-get.md'
    - 'Locations Service Bindings List': 'projects_locations-service-bindings-list.md'
    - 'Locations Service Bindings Patch': 'projects_locations-service-bindings-patch.md'
    - 'Locations Service Lb Policies Create': 'projects_locations-service-lb-policies-create.md'
    - 'Locations Service Lb Policies Delete': 'projects_locations-service-lb-policies-delete.md'
    - 'Locations Service Lb Policies Get': 'projects_locations-service-lb-policies-get.md'
    - 'Locations Service Lb Policies List': 'projects_locations-service-lb-policies-list.md'
    - 'Locations Service Lb Policies Patch': 'projects_locations-service-lb-policies-patch.md'
    - 'Locations Tcp Routes Create': 'projects_locations-tcp-routes-create.md'
    - 'Locations Tcp Routes Delete': 'projects_locations-tcp-routes-delete.md'
    - 'Locations Tcp Routes Get': 'projects_locations-tcp-routes-get.md'
    - 'Locations Tcp Routes List': 'projects_locations-tcp-routes-list.md'
    - 'Locations Tcp Routes Patch': 'projects_locations-tcp-routes-patch.md'
    - 'Locations Tls Routes Create': 'projects_locations-tls-routes-create.md'
    - 'Locations Tls Routes Delete': 'projects_locations-tls-routes-delete.md'
    - 'Locations Tls Routes Get': 'projects_locations-tls-routes-get.md'
    - 'Locations Tls Routes List': 'projects_locations-tls-routes-list.md'
    - 'Locations Tls Routes Patch': 'projects_locations-tls-routes-patch.md'
    - 'Locations Wasm Plugins Create': 'projects_locations-wasm-plugins-create.md'
    - 'Locations Wasm Plugins Delete': 'projects_locations-wasm-plugins-delete.md'
    - 'Locations Wasm Plugins Get': 'projects_locations-wasm-plugins-get.md'
    - 'Locations Wasm Plugins List': 'projects_locations-wasm-plugins-list.md'
    - 'Locations Wasm Plugins Patch': 'projects_locations-wasm-plugins-patch.md'
    - 'Locations Wasm Plugins Versions Create': 'projects_locations-wasm-plugins-versions-create.md'
    - 'Locations Wasm Plugins Versions Delete': 'projects_locations-wasm-plugins-versions-delete.md'
    - 'Locations Wasm Plugins Versions Get': 'projects_locations-wasm-plugins-versions-get.md'
    - 'Locations Wasm Plugins Versions List': 'projects_locations-wasm-plugins-versions-list.md'

theme: readthedocs

copyright: Copyright &copy; 2015â€“2024, `Sebastian Thiel`
