site_name: Hangouts Chat v2.0.8+20210324
site_url: http://byron.github.io/google-apis-rs/google-chat1-cli
site_description: A complete library to interact with Hangouts Chat (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/chat1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['dms_conversations-messages.md', 'Dms', 'Conversations Messages']
- ['dms_messages.md', 'Dms', 'Messages']
- ['dms_webhooks.md', 'Dms', 'Webhooks']
- ['media_download.md', 'Media', 'Download']
- ['rooms_conversations-messages.md', 'Rooms', 'Conversations Messages']
- ['rooms_messages.md', 'Rooms', 'Messages']
- ['rooms_webhooks.md', 'Rooms', 'Webhooks']
- ['spaces_get.md', 'Spaces', 'Get']
- ['spaces_list.md', 'Spaces', 'List']
- ['spaces_members-get.md', 'Spaces', 'Members Get']
- ['spaces_members-list.md', 'Spaces', 'Members List']
- ['spaces_messages-attachments-get.md', 'Spaces', 'Messages Attachments Get']
- ['spaces_messages-create.md', 'Spaces', 'Messages Create']
- ['spaces_messages-delete.md', 'Spaces', 'Messages Delete']
- ['spaces_messages-get.md', 'Spaces', 'Messages Get']
- ['spaces_messages-update.md', 'Spaces', 'Messages Update']
- ['spaces_webhooks.md', 'Spaces', 'Webhooks']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

