site_name: Pubsub v3.0.0+20220221
site_url: http://byron.github.io/google-apis-rs/google-pubsub1-cli
site_description: A complete library to interact with Pubsub (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/pubsub1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_schemas-create.md', 'Projects', 'Schemas Create']
- ['projects_schemas-delete.md', 'Projects', 'Schemas Delete']
- ['projects_schemas-get.md', 'Projects', 'Schemas Get']
- ['projects_schemas-get-iam-policy.md', 'Projects', 'Schemas Get Iam Policy']
- ['projects_schemas-list.md', 'Projects', 'Schemas List']
- ['projects_schemas-set-iam-policy.md', 'Projects', 'Schemas Set Iam Policy']
- ['projects_schemas-test-iam-permissions.md', 'Projects', 'Schemas Test Iam Permissions']
- ['projects_schemas-validate.md', 'Projects', 'Schemas Validate']
- ['projects_schemas-validate-message.md', 'Projects', 'Schemas Validate Message']
- ['projects_snapshots-create.md', 'Projects', 'Snapshots Create']
- ['projects_snapshots-delete.md', 'Projects', 'Snapshots Delete']
- ['projects_snapshots-get.md', 'Projects', 'Snapshots Get']
- ['projects_snapshots-get-iam-policy.md', 'Projects', 'Snapshots Get Iam Policy']
- ['projects_snapshots-list.md', 'Projects', 'Snapshots List']
- ['projects_snapshots-patch.md', 'Projects', 'Snapshots Patch']
- ['projects_snapshots-set-iam-policy.md', 'Projects', 'Snapshots Set Iam Policy']
- ['projects_snapshots-test-iam-permissions.md', 'Projects', 'Snapshots Test Iam Permissions']
- ['projects_subscriptions-acknowledge.md', 'Projects', 'Subscriptions Acknowledge']
- ['projects_subscriptions-create.md', 'Projects', 'Subscriptions Create']
- ['projects_subscriptions-delete.md', 'Projects', 'Subscriptions Delete']
- ['projects_subscriptions-detach.md', 'Projects', 'Subscriptions Detach']
- ['projects_subscriptions-get.md', 'Projects', 'Subscriptions Get']
- ['projects_subscriptions-get-iam-policy.md', 'Projects', 'Subscriptions Get Iam Policy']
- ['projects_subscriptions-list.md', 'Projects', 'Subscriptions List']
- ['projects_subscriptions-modify-ack-deadline.md', 'Projects', 'Subscriptions Modify Ack Deadline']
- ['projects_subscriptions-modify-push-config.md', 'Projects', 'Subscriptions Modify Push Config']
- ['projects_subscriptions-patch.md', 'Projects', 'Subscriptions Patch']
- ['projects_subscriptions-pull.md', 'Projects', 'Subscriptions Pull']
- ['projects_subscriptions-seek.md', 'Projects', 'Subscriptions Seek']
- ['projects_subscriptions-set-iam-policy.md', 'Projects', 'Subscriptions Set Iam Policy']
- ['projects_subscriptions-test-iam-permissions.md', 'Projects', 'Subscriptions Test Iam Permissions']
- ['projects_topics-create.md', 'Projects', 'Topics Create']
- ['projects_topics-delete.md', 'Projects', 'Topics Delete']
- ['projects_topics-get.md', 'Projects', 'Topics Get']
- ['projects_topics-get-iam-policy.md', 'Projects', 'Topics Get Iam Policy']
- ['projects_topics-list.md', 'Projects', 'Topics List']
- ['projects_topics-patch.md', 'Projects', 'Topics Patch']
- ['projects_topics-publish.md', 'Projects', 'Topics Publish']
- ['projects_topics-set-iam-policy.md', 'Projects', 'Topics Set Iam Policy']
- ['projects_topics-snapshots-list.md', 'Projects', 'Topics Snapshots List']
- ['projects_topics-subscriptions-list.md', 'Projects', 'Topics Subscriptions List']
- ['projects_topics-test-iam-permissions.md', 'Projects', 'Topics Test Iam Permissions']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

