site_name: dfareporting v1.0.7+20180830
site_url: http://byron.github.io/google-apis-rs/google-dfareporting2d8-cli
site_description: A complete library to interact with dfareporting (protocol v2.8)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/dfareporting2d8-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['account-active-ad-summaries_get.md', 'Account Active Ad Summaries', 'Get']
- ['account-permission-groups_get.md', 'Account Permission Groups', 'Get']
- ['account-permission-groups_list.md', 'Account Permission Groups', 'List']
- ['account-permissions_get.md', 'Account Permissions', 'Get']
- ['account-permissions_list.md', 'Account Permissions', 'List']
- ['account-user-profiles_get.md', 'Account User Profiles', 'Get']
- ['account-user-profiles_insert.md', 'Account User Profiles', 'Insert']
- ['account-user-profiles_list.md', 'Account User Profiles', 'List']
- ['account-user-profiles_patch.md', 'Account User Profiles', 'Patch']
- ['account-user-profiles_update.md', 'Account User Profiles', 'Update']
- ['accounts_get.md', 'Accounts', 'Get']
- ['accounts_list.md', 'Accounts', 'List']
- ['accounts_patch.md', 'Accounts', 'Patch']
- ['accounts_update.md', 'Accounts', 'Update']
- ['ads_get.md', 'Ads', 'Get']
- ['ads_insert.md', 'Ads', 'Insert']
- ['ads_list.md', 'Ads', 'List']
- ['ads_patch.md', 'Ads', 'Patch']
- ['ads_update.md', 'Ads', 'Update']
- ['advertiser-groups_delete.md', 'Advertiser Groups', 'Delete']
- ['advertiser-groups_get.md', 'Advertiser Groups', 'Get']
- ['advertiser-groups_insert.md', 'Advertiser Groups', 'Insert']
- ['advertiser-groups_list.md', 'Advertiser Groups', 'List']
- ['advertiser-groups_patch.md', 'Advertiser Groups', 'Patch']
- ['advertiser-groups_update.md', 'Advertiser Groups', 'Update']
- ['advertisers_get.md', 'Advertisers', 'Get']
- ['advertisers_insert.md', 'Advertisers', 'Insert']
- ['advertisers_list.md', 'Advertisers', 'List']
- ['advertisers_patch.md', 'Advertisers', 'Patch']
- ['advertisers_update.md', 'Advertisers', 'Update']
- ['browsers_list.md', 'Browsers', 'List']
- ['campaign-creative-associations_insert.md', 'Campaign Creative Associations', 'Insert']
- ['campaign-creative-associations_list.md', 'Campaign Creative Associations', 'List']
- ['campaigns_get.md', 'Campaigns', 'Get']
- ['campaigns_insert.md', 'Campaigns', 'Insert']
- ['campaigns_list.md', 'Campaigns', 'List']
- ['campaigns_patch.md', 'Campaigns', 'Patch']
- ['campaigns_update.md', 'Campaigns', 'Update']
- ['change-logs_get.md', 'Change Logs', 'Get']
- ['change-logs_list.md', 'Change Logs', 'List']
- ['cities_list.md', 'Cities', 'List']
- ['connection-types_get.md', 'Connection Types', 'Get']
- ['connection-types_list.md', 'Connection Types', 'List']
- ['content-categories_delete.md', 'Content Categories', 'Delete']
- ['content-categories_get.md', 'Content Categories', 'Get']
- ['content-categories_insert.md', 'Content Categories', 'Insert']
- ['content-categories_list.md', 'Content Categories', 'List']
- ['content-categories_patch.md', 'Content Categories', 'Patch']
- ['content-categories_update.md', 'Content Categories', 'Update']
- ['conversions_batchinsert.md', 'Conversions', 'Batchinsert']
- ['conversions_batchupdate.md', 'Conversions', 'Batchupdate']
- ['countries_get.md', 'Countries', 'Get']
- ['countries_list.md', 'Countries', 'List']
- ['creative-assets_insert.md', 'Creative Assets', 'Insert']
- ['creative-field-values_delete.md', 'Creative Field Values', 'Delete']
- ['creative-field-values_get.md', 'Creative Field Values', 'Get']
- ['creative-field-values_insert.md', 'Creative Field Values', 'Insert']
- ['creative-field-values_list.md', 'Creative Field Values', 'List']
- ['creative-field-values_patch.md', 'Creative Field Values', 'Patch']
- ['creative-field-values_update.md', 'Creative Field Values', 'Update']
- ['creative-fields_delete.md', 'Creative Fields', 'Delete']
- ['creative-fields_get.md', 'Creative Fields', 'Get']
- ['creative-fields_insert.md', 'Creative Fields', 'Insert']
- ['creative-fields_list.md', 'Creative Fields', 'List']
- ['creative-fields_patch.md', 'Creative Fields', 'Patch']
- ['creative-fields_update.md', 'Creative Fields', 'Update']
- ['creative-groups_get.md', 'Creative Groups', 'Get']
- ['creative-groups_insert.md', 'Creative Groups', 'Insert']
- ['creative-groups_list.md', 'Creative Groups', 'List']
- ['creative-groups_patch.md', 'Creative Groups', 'Patch']
- ['creative-groups_update.md', 'Creative Groups', 'Update']
- ['creatives_get.md', 'Creatives', 'Get']
- ['creatives_insert.md', 'Creatives', 'Insert']
- ['creatives_list.md', 'Creatives', 'List']
- ['creatives_patch.md', 'Creatives', 'Patch']
- ['creatives_update.md', 'Creatives', 'Update']
- ['dimension-values_query.md', 'Dimension Values', 'Query']
- ['directory-site-contacts_get.md', 'Directory Site Contacts', 'Get']
- ['directory-site-contacts_list.md', 'Directory Site Contacts', 'List']
- ['directory-sites_get.md', 'Directory Sites', 'Get']
- ['directory-sites_insert.md', 'Directory Sites', 'Insert']
- ['directory-sites_list.md', 'Directory Sites', 'List']
- ['dynamic-targeting-keys_delete.md', 'Dynamic Targeting Keys', 'Delete']
- ['dynamic-targeting-keys_insert.md', 'Dynamic Targeting Keys', 'Insert']
- ['dynamic-targeting-keys_list.md', 'Dynamic Targeting Keys', 'List']
- ['event-tags_delete.md', 'Event Tags', 'Delete']
- ['event-tags_get.md', 'Event Tags', 'Get']
- ['event-tags_insert.md', 'Event Tags', 'Insert']
- ['event-tags_list.md', 'Event Tags', 'List']
- ['event-tags_patch.md', 'Event Tags', 'Patch']
- ['event-tags_update.md', 'Event Tags', 'Update']
- ['files_get.md', 'Files', 'Get']
- ['files_list.md', 'Files', 'List']
- ['floodlight-activities_delete.md', 'Floodlight Activities', 'Delete']
- ['floodlight-activities_generatetag.md', 'Floodlight Activities', 'Generatetag']
- ['floodlight-activities_get.md', 'Floodlight Activities', 'Get']
- ['floodlight-activities_insert.md', 'Floodlight Activities', 'Insert']
- ['floodlight-activities_list.md', 'Floodlight Activities', 'List']
- ['floodlight-activities_patch.md', 'Floodlight Activities', 'Patch']
- ['floodlight-activities_update.md', 'Floodlight Activities', 'Update']
- ['floodlight-activity-groups_get.md', 'Floodlight Activity Groups', 'Get']
- ['floodlight-activity-groups_insert.md', 'Floodlight Activity Groups', 'Insert']
- ['floodlight-activity-groups_list.md', 'Floodlight Activity Groups', 'List']
- ['floodlight-activity-groups_patch.md', 'Floodlight Activity Groups', 'Patch']
- ['floodlight-activity-groups_update.md', 'Floodlight Activity Groups', 'Update']
- ['floodlight-configurations_get.md', 'Floodlight Configurations', 'Get']
- ['floodlight-configurations_list.md', 'Floodlight Configurations', 'List']
- ['floodlight-configurations_patch.md', 'Floodlight Configurations', 'Patch']
- ['floodlight-configurations_update.md', 'Floodlight Configurations', 'Update']
- ['inventory-items_get.md', 'Inventory Items', 'Get']
- ['inventory-items_list.md', 'Inventory Items', 'List']
- ['landing-pages_delete.md', 'Landing Pages', 'Delete']
- ['landing-pages_get.md', 'Landing Pages', 'Get']
- ['landing-pages_insert.md', 'Landing Pages', 'Insert']
- ['landing-pages_list.md', 'Landing Pages', 'List']
- ['landing-pages_patch.md', 'Landing Pages', 'Patch']
- ['landing-pages_update.md', 'Landing Pages', 'Update']
- ['languages_list.md', 'Languages', 'List']
- ['metros_list.md', 'Metros', 'List']
- ['mobile-carriers_get.md', 'Mobile Carriers', 'Get']
- ['mobile-carriers_list.md', 'Mobile Carriers', 'List']
- ['operating-system-versions_get.md', 'Operating System Versions', 'Get']
- ['operating-system-versions_list.md', 'Operating System Versions', 'List']
- ['operating-systems_get.md', 'Operating Systems', 'Get']
- ['operating-systems_list.md', 'Operating Systems', 'List']
- ['order-documents_get.md', 'Order Documents', 'Get']
- ['order-documents_list.md', 'Order Documents', 'List']
- ['orders_get.md', 'Orders', 'Get']
- ['orders_list.md', 'Orders', 'List']
- ['placement-groups_get.md', 'Placement Groups', 'Get']
- ['placement-groups_insert.md', 'Placement Groups', 'Insert']
- ['placement-groups_list.md', 'Placement Groups', 'List']
- ['placement-groups_patch.md', 'Placement Groups', 'Patch']
- ['placement-groups_update.md', 'Placement Groups', 'Update']
- ['placement-strategies_delete.md', 'Placement Strategies', 'Delete']
- ['placement-strategies_get.md', 'Placement Strategies', 'Get']
- ['placement-strategies_insert.md', 'Placement Strategies', 'Insert']
- ['placement-strategies_list.md', 'Placement Strategies', 'List']
- ['placement-strategies_patch.md', 'Placement Strategies', 'Patch']
- ['placement-strategies_update.md', 'Placement Strategies', 'Update']
- ['placements_generatetags.md', 'Placements', 'Generatetags']
- ['placements_get.md', 'Placements', 'Get']
- ['placements_insert.md', 'Placements', 'Insert']
- ['placements_list.md', 'Placements', 'List']
- ['placements_patch.md', 'Placements', 'Patch']
- ['placements_update.md', 'Placements', 'Update']
- ['platform-types_get.md', 'Platform Types', 'Get']
- ['platform-types_list.md', 'Platform Types', 'List']
- ['postal-codes_get.md', 'Postal Codes', 'Get']
- ['postal-codes_list.md', 'Postal Codes', 'List']
- ['projects_get.md', 'Projects', 'Get']
- ['projects_list.md', 'Projects', 'List']
- ['regions_list.md', 'Regions', 'List']
- ['remarketing-list-shares_get.md', 'Remarketing List Shares', 'Get']
- ['remarketing-list-shares_patch.md', 'Remarketing List Shares', 'Patch']
- ['remarketing-list-shares_update.md', 'Remarketing List Shares', 'Update']
- ['remarketing-lists_get.md', 'Remarketing Lists', 'Get']
- ['remarketing-lists_insert.md', 'Remarketing Lists', 'Insert']
- ['remarketing-lists_list.md', 'Remarketing Lists', 'List']
- ['remarketing-lists_patch.md', 'Remarketing Lists', 'Patch']
- ['remarketing-lists_update.md', 'Remarketing Lists', 'Update']
- ['reports_compatible-fields-query.md', 'Reports', 'Compatible Fields Query']
- ['reports_delete.md', 'Reports', 'Delete']
- ['reports_files-get.md', 'Reports', 'Files Get']
- ['reports_files-list.md', 'Reports', 'Files List']
- ['reports_get.md', 'Reports', 'Get']
- ['reports_insert.md', 'Reports', 'Insert']
- ['reports_list.md', 'Reports', 'List']
- ['reports_patch.md', 'Reports', 'Patch']
- ['reports_run.md', 'Reports', 'Run']
- ['reports_update.md', 'Reports', 'Update']
- ['sites_get.md', 'Sites', 'Get']
- ['sites_insert.md', 'Sites', 'Insert']
- ['sites_list.md', 'Sites', 'List']
- ['sites_patch.md', 'Sites', 'Patch']
- ['sites_update.md', 'Sites', 'Update']
- ['sizes_get.md', 'Sizes', 'Get']
- ['sizes_insert.md', 'Sizes', 'Insert']
- ['sizes_list.md', 'Sizes', 'List']
- ['subaccounts_get.md', 'Subaccounts', 'Get']
- ['subaccounts_insert.md', 'Subaccounts', 'Insert']
- ['subaccounts_list.md', 'Subaccounts', 'List']
- ['subaccounts_patch.md', 'Subaccounts', 'Patch']
- ['subaccounts_update.md', 'Subaccounts', 'Update']
- ['targetable-remarketing-lists_get.md', 'Targetable Remarketing Lists', 'Get']
- ['targetable-remarketing-lists_list.md', 'Targetable Remarketing Lists', 'List']
- ['targeting-templates_get.md', 'Targeting Templates', 'Get']
- ['targeting-templates_insert.md', 'Targeting Templates', 'Insert']
- ['targeting-templates_list.md', 'Targeting Templates', 'List']
- ['targeting-templates_patch.md', 'Targeting Templates', 'Patch']
- ['targeting-templates_update.md', 'Targeting Templates', 'Update']
- ['user-profiles_get.md', 'User Profiles', 'Get']
- ['user-profiles_list.md', 'User Profiles', 'List']
- ['user-role-permission-groups_get.md', 'User Role Permission Groups', 'Get']
- ['user-role-permission-groups_list.md', 'User Role Permission Groups', 'List']
- ['user-role-permissions_get.md', 'User Role Permissions', 'Get']
- ['user-role-permissions_list.md', 'User Role Permissions', 'List']
- ['user-roles_delete.md', 'User Roles', 'Delete']
- ['user-roles_get.md', 'User Roles', 'Get']
- ['user-roles_insert.md', 'User Roles', 'Insert']
- ['user-roles_list.md', 'User Roles', 'List']
- ['user-roles_patch.md', 'User Roles', 'Patch']
- ['user-roles_update.md', 'User Roles', 'Update']
- ['video-formats_get.md', 'Video Formats', 'Get']
- ['video-formats_list.md', 'Video Formats', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

