site_name: Shopping Content v3.0.2+20220303
site_url: http://byron.github.io/google-apis-rs/google-content2-cli
site_description: A complete library to interact with Shopping Content (protocol v2)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/content2-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['accounts_authinfo.md', 'Accounts', 'Authinfo']
- ['accounts_claimwebsite.md', 'Accounts', 'Claimwebsite']
- ['accounts_custombatch.md', 'Accounts', 'Custombatch']
- ['accounts_delete.md', 'Accounts', 'Delete']
- ['accounts_get.md', 'Accounts', 'Get']
- ['accounts_insert.md', 'Accounts', 'Insert']
- ['accounts_link.md', 'Accounts', 'Link']
- ['accounts_list.md', 'Accounts', 'List']
- ['accounts_update.md', 'Accounts', 'Update']
- ['accountstatuses_custombatch.md', 'Accountstatuses', 'Custombatch']
- ['accountstatuses_get.md', 'Accountstatuses', 'Get']
- ['accountstatuses_list.md', 'Accountstatuses', 'List']
- ['accounttax_custombatch.md', 'Accounttax', 'Custombatch']
- ['accounttax_get.md', 'Accounttax', 'Get']
- ['accounttax_list.md', 'Accounttax', 'List']
- ['accounttax_update.md', 'Accounttax', 'Update']
- ['datafeeds_custombatch.md', 'Datafeeds', 'Custombatch']
- ['datafeeds_delete.md', 'Datafeeds', 'Delete']
- ['datafeeds_fetchnow.md', 'Datafeeds', 'Fetchnow']
- ['datafeeds_get.md', 'Datafeeds', 'Get']
- ['datafeeds_insert.md', 'Datafeeds', 'Insert']
- ['datafeeds_list.md', 'Datafeeds', 'List']
- ['datafeeds_update.md', 'Datafeeds', 'Update']
- ['datafeedstatuses_custombatch.md', 'Datafeedstatuses', 'Custombatch']
- ['datafeedstatuses_get.md', 'Datafeedstatuses', 'Get']
- ['datafeedstatuses_list.md', 'Datafeedstatuses', 'List']
- ['inventory_custombatch.md', 'Inventory', 'Custombatch']
- ['inventory_set.md', 'Inventory', 'Set']
- ['liasettings_custombatch.md', 'Liasettings', 'Custombatch']
- ['liasettings_get.md', 'Liasettings', 'Get']
- ['liasettings_getaccessiblegmbaccounts.md', 'Liasettings', 'Getaccessiblegmbaccounts']
- ['liasettings_list.md', 'Liasettings', 'List']
- ['liasettings_listposdataproviders.md', 'Liasettings', 'Listposdataproviders']
- ['liasettings_requestgmbaccess.md', 'Liasettings', 'Requestgmbaccess']
- ['liasettings_requestinventoryverification.md', 'Liasettings', 'Requestinventoryverification']
- ['liasettings_setinventoryverificationcontact.md', 'Liasettings', 'Setinventoryverificationcontact']
- ['liasettings_setposdataprovider.md', 'Liasettings', 'Setposdataprovider']
- ['liasettings_update.md', 'Liasettings', 'Update']
- ['orderinvoices_createchargeinvoice.md', 'Orderinvoices', 'Createchargeinvoice']
- ['orderinvoices_createrefundinvoice.md', 'Orderinvoices', 'Createrefundinvoice']
- ['orderreports_listdisbursements.md', 'Orderreports', 'Listdisbursements']
- ['orderreports_listtransactions.md', 'Orderreports', 'Listtransactions']
- ['orderreturns_get.md', 'Orderreturns', 'Get']
- ['orderreturns_list.md', 'Orderreturns', 'List']
- ['orders_acknowledge.md', 'Orders', 'Acknowledge']
- ['orders_advancetestorder.md', 'Orders', 'Advancetestorder']
- ['orders_cancel.md', 'Orders', 'Cancel']
- ['orders_cancellineitem.md', 'Orders', 'Cancellineitem']
- ['orders_canceltestorderbycustomer.md', 'Orders', 'Canceltestorderbycustomer']
- ['orders_createtestorder.md', 'Orders', 'Createtestorder']
- ['orders_createtestreturn.md', 'Orders', 'Createtestreturn']
- ['orders_custombatch.md', 'Orders', 'Custombatch']
- ['orders_get.md', 'Orders', 'Get']
- ['orders_getbymerchantorderid.md', 'Orders', 'Getbymerchantorderid']
- ['orders_gettestordertemplate.md', 'Orders', 'Gettestordertemplate']
- ['orders_instorerefundlineitem.md', 'Orders', 'Instorerefundlineitem']
- ['orders_list.md', 'Orders', 'List']
- ['orders_refund.md', 'Orders', 'Refund']
- ['orders_rejectreturnlineitem.md', 'Orders', 'Rejectreturnlineitem']
- ['orders_returnlineitem.md', 'Orders', 'Returnlineitem']
- ['orders_returnrefundlineitem.md', 'Orders', 'Returnrefundlineitem']
- ['orders_setlineitemmetadata.md', 'Orders', 'Setlineitemmetadata']
- ['orders_shiplineitems.md', 'Orders', 'Shiplineitems']
- ['orders_updatelineitemshippingdetails.md', 'Orders', 'Updatelineitemshippingdetails']
- ['orders_updatemerchantorderid.md', 'Orders', 'Updatemerchantorderid']
- ['orders_updateshipment.md', 'Orders', 'Updateshipment']
- ['pos_custombatch.md', 'Pos', 'Custombatch']
- ['pos_delete.md', 'Pos', 'Delete']
- ['pos_get.md', 'Pos', 'Get']
- ['pos_insert.md', 'Pos', 'Insert']
- ['pos_inventory.md', 'Pos', 'Inventory']
- ['pos_list.md', 'Pos', 'List']
- ['pos_sale.md', 'Pos', 'Sale']
- ['products_custombatch.md', 'Products', 'Custombatch']
- ['products_delete.md', 'Products', 'Delete']
- ['products_get.md', 'Products', 'Get']
- ['products_insert.md', 'Products', 'Insert']
- ['products_list.md', 'Products', 'List']
- ['productstatuses_custombatch.md', 'Productstatuses', 'Custombatch']
- ['productstatuses_get.md', 'Productstatuses', 'Get']
- ['productstatuses_list.md', 'Productstatuses', 'List']
- ['shippingsettings_custombatch.md', 'Shippingsettings', 'Custombatch']
- ['shippingsettings_get.md', 'Shippingsettings', 'Get']
- ['shippingsettings_getsupportedcarriers.md', 'Shippingsettings', 'Getsupportedcarriers']
- ['shippingsettings_getsupportedholidays.md', 'Shippingsettings', 'Getsupportedholidays']
- ['shippingsettings_getsupportedpickupservices.md', 'Shippingsettings', 'Getsupportedpickupservices']
- ['shippingsettings_list.md', 'Shippingsettings', 'List']
- ['shippingsettings_update.md', 'Shippingsettings', 'Update']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

