site_name: Android Enterprise v1.0.7+20181003
site_url: http://byron.github.io/google-apis-rs/google-androidenterprise1-cli
site_description: A complete library to interact with Android Enterprise (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/androidenterprise1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['devices_get.md', 'Devices', 'Get']
- ['devices_get-state.md', 'Devices', 'Get State']
- ['devices_list.md', 'Devices', 'List']
- ['devices_patch.md', 'Devices', 'Patch']
- ['devices_set-state.md', 'Devices', 'Set State']
- ['devices_update.md', 'Devices', 'Update']
- ['enterprises_acknowledge-notification-set.md', 'Enterprises', 'Acknowledge Notification Set']
- ['enterprises_complete-signup.md', 'Enterprises', 'Complete Signup']
- ['enterprises_create-web-token.md', 'Enterprises', 'Create Web Token']
- ['enterprises_enroll.md', 'Enterprises', 'Enroll']
- ['enterprises_generate-signup-url.md', 'Enterprises', 'Generate Signup Url']
- ['enterprises_get.md', 'Enterprises', 'Get']
- ['enterprises_get-android-device-policy-config.md', 'Enterprises', 'Get Android Device Policy Config']
- ['enterprises_get-service-account.md', 'Enterprises', 'Get Service Account']
- ['enterprises_get-store-layout.md', 'Enterprises', 'Get Store Layout']
- ['enterprises_list.md', 'Enterprises', 'List']
- ['enterprises_pull-notification-set.md', 'Enterprises', 'Pull Notification Set']
- ['enterprises_send-test-push-notification.md', 'Enterprises', 'Send Test Push Notification']
- ['enterprises_set-account.md', 'Enterprises', 'Set Account']
- ['enterprises_set-android-device-policy-config.md', 'Enterprises', 'Set Android Device Policy Config']
- ['enterprises_set-store-layout.md', 'Enterprises', 'Set Store Layout']
- ['enterprises_unenroll.md', 'Enterprises', 'Unenroll']
- ['entitlements_delete.md', 'Entitlements', 'Delete']
- ['entitlements_get.md', 'Entitlements', 'Get']
- ['entitlements_list.md', 'Entitlements', 'List']
- ['entitlements_patch.md', 'Entitlements', 'Patch']
- ['entitlements_update.md', 'Entitlements', 'Update']
- ['grouplicenses_get.md', 'Grouplicenses', 'Get']
- ['grouplicenses_list.md', 'Grouplicenses', 'List']
- ['grouplicenseusers_list.md', 'Grouplicenseusers', 'List']
- ['installs_delete.md', 'Installs', 'Delete']
- ['installs_get.md', 'Installs', 'Get']
- ['installs_list.md', 'Installs', 'List']
- ['installs_patch.md', 'Installs', 'Patch']
- ['installs_update.md', 'Installs', 'Update']
- ['managedconfigurationsfordevice_delete.md', 'Managedconfigurationsfordevice', 'Delete']
- ['managedconfigurationsfordevice_get.md', 'Managedconfigurationsfordevice', 'Get']
- ['managedconfigurationsfordevice_list.md', 'Managedconfigurationsfordevice', 'List']
- ['managedconfigurationsfordevice_patch.md', 'Managedconfigurationsfordevice', 'Patch']
- ['managedconfigurationsfordevice_update.md', 'Managedconfigurationsfordevice', 'Update']
- ['managedconfigurationsforuser_delete.md', 'Managedconfigurationsforuser', 'Delete']
- ['managedconfigurationsforuser_get.md', 'Managedconfigurationsforuser', 'Get']
- ['managedconfigurationsforuser_list.md', 'Managedconfigurationsforuser', 'List']
- ['managedconfigurationsforuser_patch.md', 'Managedconfigurationsforuser', 'Patch']
- ['managedconfigurationsforuser_update.md', 'Managedconfigurationsforuser', 'Update']
- ['managedconfigurationssettings_list.md', 'Managedconfigurationssettings', 'List']
- ['permissions_get.md', 'Permissions', 'Get']
- ['products_approve.md', 'Products', 'Approve']
- ['products_generate-approval-url.md', 'Products', 'Generate Approval Url']
- ['products_get.md', 'Products', 'Get']
- ['products_get-app-restrictions-schema.md', 'Products', 'Get App Restrictions Schema']
- ['products_get-permissions.md', 'Products', 'Get Permissions']
- ['products_list.md', 'Products', 'List']
- ['products_unapprove.md', 'Products', 'Unapprove']
- ['serviceaccountkeys_delete.md', 'Serviceaccountkeys', 'Delete']
- ['serviceaccountkeys_insert.md', 'Serviceaccountkeys', 'Insert']
- ['serviceaccountkeys_list.md', 'Serviceaccountkeys', 'List']
- ['storelayoutclusters_delete.md', 'Storelayoutclusters', 'Delete']
- ['storelayoutclusters_get.md', 'Storelayoutclusters', 'Get']
- ['storelayoutclusters_insert.md', 'Storelayoutclusters', 'Insert']
- ['storelayoutclusters_list.md', 'Storelayoutclusters', 'List']
- ['storelayoutclusters_patch.md', 'Storelayoutclusters', 'Patch']
- ['storelayoutclusters_update.md', 'Storelayoutclusters', 'Update']
- ['storelayoutpages_delete.md', 'Storelayoutpages', 'Delete']
- ['storelayoutpages_get.md', 'Storelayoutpages', 'Get']
- ['storelayoutpages_insert.md', 'Storelayoutpages', 'Insert']
- ['storelayoutpages_list.md', 'Storelayoutpages', 'List']
- ['storelayoutpages_patch.md', 'Storelayoutpages', 'Patch']
- ['storelayoutpages_update.md', 'Storelayoutpages', 'Update']
- ['users_delete.md', 'Users', 'Delete']
- ['users_generate-authentication-token.md', 'Users', 'Generate Authentication Token']
- ['users_generate-token.md', 'Users', 'Generate Token']
- ['users_get.md', 'Users', 'Get']
- ['users_get-available-product-set.md', 'Users', 'Get Available Product Set']
- ['users_insert.md', 'Users', 'Insert']
- ['users_list.md', 'Users', 'List']
- ['users_patch.md', 'Users', 'Patch']
- ['users_revoke-device-access.md', 'Users', 'Revoke Device Access']
- ['users_revoke-token.md', 'Users', 'Revoke Token']
- ['users_set-available-product-set.md', 'Users', 'Set Available Product Set']
- ['users_update.md', 'Users', 'Update']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

