site_name: Cloud Identity v2.0.5+20210310
site_url: http://byron.github.io/google-apis-rs/google-cloudidentity1-cli
site_description: A complete library to interact with Cloud Identity (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/cloudidentity1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['devices_cancel-wipe.md', 'Devices', 'Cancel Wipe']
- ['devices_create.md', 'Devices', 'Create']
- ['devices_delete.md', 'Devices', 'Delete']
- ['devices_device-users-approve.md', 'Devices', 'Device Users Approve']
- ['devices_device-users-block.md', 'Devices', 'Device Users Block']
- ['devices_device-users-cancel-wipe.md', 'Devices', 'Device Users Cancel Wipe']
- ['devices_device-users-client-states-get.md', 'Devices', 'Device Users Client States Get']
- ['devices_device-users-client-states-list.md', 'Devices', 'Device Users Client States List']
- ['devices_device-users-client-states-patch.md', 'Devices', 'Device Users Client States Patch']
- ['devices_device-users-delete.md', 'Devices', 'Device Users Delete']
- ['devices_device-users-get.md', 'Devices', 'Device Users Get']
- ['devices_device-users-list.md', 'Devices', 'Device Users List']
- ['devices_device-users-lookup.md', 'Devices', 'Device Users Lookup']
- ['devices_device-users-wipe.md', 'Devices', 'Device Users Wipe']
- ['devices_get.md', 'Devices', 'Get']
- ['devices_list.md', 'Devices', 'List']
- ['devices_wipe.md', 'Devices', 'Wipe']
- ['groups_create.md', 'Groups', 'Create']
- ['groups_delete.md', 'Groups', 'Delete']
- ['groups_get.md', 'Groups', 'Get']
- ['groups_list.md', 'Groups', 'List']
- ['groups_lookup.md', 'Groups', 'Lookup']
- ['groups_memberships-check-transitive-membership.md', 'Groups', 'Memberships Check Transitive Membership']
- ['groups_memberships-create.md', 'Groups', 'Memberships Create']
- ['groups_memberships-delete.md', 'Groups', 'Memberships Delete']
- ['groups_memberships-get.md', 'Groups', 'Memberships Get']
- ['groups_memberships-get-membership-graph.md', 'Groups', 'Memberships Get Membership Graph']
- ['groups_memberships-list.md', 'Groups', 'Memberships List']
- ['groups_memberships-lookup.md', 'Groups', 'Memberships Lookup']
- ['groups_memberships-modify-membership-roles.md', 'Groups', 'Memberships Modify Membership Roles']
- ['groups_memberships-search-transitive-groups.md', 'Groups', 'Memberships Search Transitive Groups']
- ['groups_memberships-search-transitive-memberships.md', 'Groups', 'Memberships Search Transitive Memberships']
- ['groups_patch.md', 'Groups', 'Patch']
- ['groups_search.md', 'Groups', 'Search']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

