site_name: Cloud Identity v1.0.12+20190629
site_url: http://byron.github.io/google-apis-rs/google-cloudidentity1-cli
site_description: A complete library to interact with Cloud Identity (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/cloudidentity1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['groups_create.md', 'Groups', 'Create']
- ['groups_delete.md', 'Groups', 'Delete']
- ['groups_get.md', 'Groups', 'Get']
- ['groups_list.md', 'Groups', 'List']
- ['groups_lookup.md', 'Groups', 'Lookup']
- ['groups_memberships-create.md', 'Groups', 'Memberships Create']
- ['groups_memberships-delete.md', 'Groups', 'Memberships Delete']
- ['groups_memberships-get.md', 'Groups', 'Memberships Get']
- ['groups_memberships-list.md', 'Groups', 'Memberships List']
- ['groups_memberships-lookup.md', 'Groups', 'Memberships Lookup']
- ['groups_patch.md', 'Groups', 'Patch']
- ['groups_search.md', 'Groups', 'Search']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

