site_name: discovery v2.0.3+20200806
site_url: http://byron.github.io/google-apis-rs/google-discovery1-cli
site_description: A complete library to interact with discovery (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/discovery1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['apis_get-rest.md', 'Apis', 'Get Rest']
- ['apis_list.md', 'Apis', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

