site_name: Cloud Asset v3.1.0+20220225
site_url: http://byron.github.io/google-apis-rs/google-cloudasset1-cli
site_description: A complete library to interact with Cloud Asset (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/cloudasset1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['assets_list.md', 'Assets', 'List']
- ['effective-iam-policies_batch-get.md', 'Effective Iam Policies', 'Batch Get']
- ['feeds_create.md', 'Feeds', 'Create']
- ['feeds_delete.md', 'Feeds', 'Delete']
- ['feeds_get.md', 'Feeds', 'Get']
- ['feeds_list.md', 'Feeds', 'List']
- ['feeds_patch.md', 'Feeds', 'Patch']
- ['methods_analyze-iam-policy.md', 'Methods', 'Analyze Iam Policy']
- ['methods_analyze-iam-policy-longrunning.md', 'Methods', 'Analyze Iam Policy Longrunning']
- ['methods_analyze-move.md', 'Methods', 'Analyze Move']
- ['methods_batch-get-assets-history.md', 'Methods', 'Batch Get Assets History']
- ['methods_export-assets.md', 'Methods', 'Export Assets']
- ['methods_search-all-iam-policies.md', 'Methods', 'Search All Iam Policies']
- ['methods_search-all-resources.md', 'Methods', 'Search All Resources']
- ['operations_get.md', 'Operations', 'Get']
- ['saved-queries_create.md', 'Saved Queries', 'Create']
- ['saved-queries_delete.md', 'Saved Queries', 'Delete']
- ['saved-queries_get.md', 'Saved Queries', 'Get']
- ['saved-queries_list.md', 'Saved Queries', 'List']
- ['saved-queries_patch.md', 'Saved Queries', 'Patch']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

