site_name: NetworkSecurity v7.0.0+20251203
site_url: http://byron.github.io/google-apis-rs/google-networksecurity1-cli
site_description: A complete library to interact with NetworkSecurity (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/networksecurity1-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Organizations':
    - 'Locations Address Groups Add Items': 'organizations_locations-address-groups-add-items.md'
    - 'Locations Address Groups Clone Items': 'organizations_locations-address-groups-clone-items.md'
    - 'Locations Address Groups Create': 'organizations_locations-address-groups-create.md'
    - 'Locations Address Groups Delete': 'organizations_locations-address-groups-delete.md'
    - 'Locations Address Groups Get': 'organizations_locations-address-groups-get.md'
    - 'Locations Address Groups List': 'organizations_locations-address-groups-list.md'
    - 'Locations Address Groups List References': 'organizations_locations-address-groups-list-references.md'
    - 'Locations Address Groups Patch': 'organizations_locations-address-groups-patch.md'
    - 'Locations Address Groups Remove Items': 'organizations_locations-address-groups-remove-items.md'
    - 'Locations Firewall Endpoints Create': 'organizations_locations-firewall-endpoints-create.md'
    - 'Locations Firewall Endpoints Delete': 'organizations_locations-firewall-endpoints-delete.md'
    - 'Locations Firewall Endpoints Get': 'organizations_locations-firewall-endpoints-get.md'
    - 'Locations Firewall Endpoints List': 'organizations_locations-firewall-endpoints-list.md'
    - 'Locations Firewall Endpoints Patch': 'organizations_locations-firewall-endpoints-patch.md'
    - 'Locations Operations Cancel': 'organizations_locations-operations-cancel.md'
    - 'Locations Operations Delete': 'organizations_locations-operations-delete.md'
    - 'Locations Operations Get': 'organizations_locations-operations-get.md'
    - 'Locations Operations List': 'organizations_locations-operations-list.md'
    - 'Locations Security Profile Groups Create': 'organizations_locations-security-profile-groups-create.md'
    - 'Locations Security Profile Groups Delete': 'organizations_locations-security-profile-groups-delete.md'
    - 'Locations Security Profile Groups Get': 'organizations_locations-security-profile-groups-get.md'
    - 'Locations Security Profile Groups List': 'organizations_locations-security-profile-groups-list.md'
    - 'Locations Security Profile Groups Patch': 'organizations_locations-security-profile-groups-patch.md'
    - 'Locations Security Profiles Create': 'organizations_locations-security-profiles-create.md'
    - 'Locations Security Profiles Delete': 'organizations_locations-security-profiles-delete.md'
    - 'Locations Security Profiles Get': 'organizations_locations-security-profiles-get.md'
    - 'Locations Security Profiles List': 'organizations_locations-security-profiles-list.md'
    - 'Locations Security Profiles Patch': 'organizations_locations-security-profiles-patch.md'
- 'Projects':
    - 'Locations Address Groups Add Items': 'projects_locations-address-groups-add-items.md'
    - 'Locations Address Groups Clone Items': 'projects_locations-address-groups-clone-items.md'
    - 'Locations Address Groups Create': 'projects_locations-address-groups-create.md'
    - 'Locations Address Groups Delete': 'projects_locations-address-groups-delete.md'
    - 'Locations Address Groups Get': 'projects_locations-address-groups-get.md'
    - 'Locations Address Groups Get Iam Policy': 'projects_locations-address-groups-get-iam-policy.md'
    - 'Locations Address Groups List': 'projects_locations-address-groups-list.md'
    - 'Locations Address Groups List References': 'projects_locations-address-groups-list-references.md'
    - 'Locations Address Groups Patch': 'projects_locations-address-groups-patch.md'
    - 'Locations Address Groups Remove Items': 'projects_locations-address-groups-remove-items.md'
    - 'Locations Address Groups Set Iam Policy': 'projects_locations-address-groups-set-iam-policy.md'
    - 'Locations Address Groups Test Iam Permissions': 'projects_locations-address-groups-test-iam-permissions.md'
    - 'Locations Authorization Policies Create': 'projects_locations-authorization-policies-create.md'
    - 'Locations Authorization Policies Delete': 'projects_locations-authorization-policies-delete.md'
    - 'Locations Authorization Policies Get': 'projects_locations-authorization-policies-get.md'
    - 'Locations Authorization Policies Get Iam Policy': 'projects_locations-authorization-policies-get-iam-policy.md'
    - 'Locations Authorization Policies List': 'projects_locations-authorization-policies-list.md'
    - 'Locations Authorization Policies Patch': 'projects_locations-authorization-policies-patch.md'
    - 'Locations Authorization Policies Set Iam Policy': 'projects_locations-authorization-policies-set-iam-policy.md'
    - 'Locations Authorization Policies Test Iam Permissions': 'projects_locations-authorization-policies-test-iam-permissions.md'
    - 'Locations Authz Policies Create': 'projects_locations-authz-policies-create.md'
    - 'Locations Authz Policies Delete': 'projects_locations-authz-policies-delete.md'
    - 'Locations Authz Policies Get': 'projects_locations-authz-policies-get.md'
    - 'Locations Authz Policies Get Iam Policy': 'projects_locations-authz-policies-get-iam-policy.md'
    - 'Locations Authz Policies List': 'projects_locations-authz-policies-list.md'
    - 'Locations Authz Policies Patch': 'projects_locations-authz-policies-patch.md'
    - 'Locations Authz Policies Set Iam Policy': 'projects_locations-authz-policies-set-iam-policy.md'
    - 'Locations Authz Policies Test Iam Permissions': 'projects_locations-authz-policies-test-iam-permissions.md'
    - 'Locations Backend Authentication Configs Create': 'projects_locations-backend-authentication-configs-create.md'
    - 'Locations Backend Authentication Configs Delete': 'projects_locations-backend-authentication-configs-delete.md'
    - 'Locations Backend Authentication Configs Get': 'projects_locations-backend-authentication-configs-get.md'
    - 'Locations Backend Authentication Configs List': 'projects_locations-backend-authentication-configs-list.md'
    - 'Locations Backend Authentication Configs Patch': 'projects_locations-backend-authentication-configs-patch.md'
    - 'Locations Client Tls Policies Create': 'projects_locations-client-tls-policies-create.md'
    - 'Locations Client Tls Policies Delete': 'projects_locations-client-tls-policies-delete.md'
    - 'Locations Client Tls Policies Get': 'projects_locations-client-tls-policies-get.md'
    - 'Locations Client Tls Policies Get Iam Policy': 'projects_locations-client-tls-policies-get-iam-policy.md'
    - 'Locations Client Tls Policies List': 'projects_locations-client-tls-policies-list.md'
    - 'Locations Client Tls Policies Patch': 'projects_locations-client-tls-policies-patch.md'
    - 'Locations Client Tls Policies Set Iam Policy': 'projects_locations-client-tls-policies-set-iam-policy.md'
    - 'Locations Client Tls Policies Test Iam Permissions': 'projects_locations-client-tls-policies-test-iam-permissions.md'
    - 'Locations Dns Threat Detectors Create': 'projects_locations-dns-threat-detectors-create.md'
    - 'Locations Dns Threat Detectors Delete': 'projects_locations-dns-threat-detectors-delete.md'
    - 'Locations Dns Threat Detectors Get': 'projects_locations-dns-threat-detectors-get.md'
    - 'Locations Dns Threat Detectors List': 'projects_locations-dns-threat-detectors-list.md'
    - 'Locations Dns Threat Detectors Patch': 'projects_locations-dns-threat-detectors-patch.md'
    - 'Locations Firewall Endpoint Associations Create': 'projects_locations-firewall-endpoint-associations-create.md'
    - 'Locations Firewall Endpoint Associations Delete': 'projects_locations-firewall-endpoint-associations-delete.md'
    - 'Locations Firewall Endpoint Associations Get': 'projects_locations-firewall-endpoint-associations-get.md'
    - 'Locations Firewall Endpoint Associations List': 'projects_locations-firewall-endpoint-associations-list.md'
    - 'Locations Firewall Endpoint Associations Patch': 'projects_locations-firewall-endpoint-associations-patch.md'
    - 'Locations Firewall Endpoints Create': 'projects_locations-firewall-endpoints-create.md'
    - 'Locations Firewall Endpoints Delete': 'projects_locations-firewall-endpoints-delete.md'
    - 'Locations Firewall Endpoints Get': 'projects_locations-firewall-endpoints-get.md'
    - 'Locations Firewall Endpoints List': 'projects_locations-firewall-endpoints-list.md'
    - 'Locations Firewall Endpoints Patch': 'projects_locations-firewall-endpoints-patch.md'
    - 'Locations Gateway Security Policies Create': 'projects_locations-gateway-security-policies-create.md'
    - 'Locations Gateway Security Policies Delete': 'projects_locations-gateway-security-policies-delete.md'
    - 'Locations Gateway Security Policies Get': 'projects_locations-gateway-security-policies-get.md'
    - 'Locations Gateway Security Policies List': 'projects_locations-gateway-security-policies-list.md'
    - 'Locations Gateway Security Policies Patch': 'projects_locations-gateway-security-policies-patch.md'
    - 'Locations Gateway Security Policies Rules Create': 'projects_locations-gateway-security-policies-rules-create.md'
    - 'Locations Gateway Security Policies Rules Delete': 'projects_locations-gateway-security-policies-rules-delete.md'
    - 'Locations Gateway Security Policies Rules Get': 'projects_locations-gateway-security-policies-rules-get.md'
    - 'Locations Gateway Security Policies Rules List': 'projects_locations-gateway-security-policies-rules-list.md'
    - 'Locations Gateway Security Policies Rules Patch': 'projects_locations-gateway-security-policies-rules-patch.md'
    - 'Locations Get': 'projects_locations-get.md'
    - 'Locations Intercept Deployment Groups Create': 'projects_locations-intercept-deployment-groups-create.md'
    - 'Locations Intercept Deployment Groups Delete': 'projects_locations-intercept-deployment-groups-delete.md'
    - 'Locations Intercept Deployment Groups Get': 'projects_locations-intercept-deployment-groups-get.md'
    - 'Locations Intercept Deployment Groups List': 'projects_locations-intercept-deployment-groups-list.md'
    - 'Locations Intercept Deployment Groups Patch': 'projects_locations-intercept-deployment-groups-patch.md'
    - 'Locations Intercept Deployments Create': 'projects_locations-intercept-deployments-create.md'
    - 'Locations Intercept Deployments Delete': 'projects_locations-intercept-deployments-delete.md'
    - 'Locations Intercept Deployments Get': 'projects_locations-intercept-deployments-get.md'
    - 'Locations Intercept Deployments List': 'projects_locations-intercept-deployments-list.md'
    - 'Locations Intercept Deployments Patch': 'projects_locations-intercept-deployments-patch.md'
    - 'Locations Intercept Endpoint Group Associations Create': 'projects_locations-intercept-endpoint-group-associations-create.md'
    - 'Locations Intercept Endpoint Group Associations Delete': 'projects_locations-intercept-endpoint-group-associations-delete.md'
    - 'Locations Intercept Endpoint Group Associations Get': 'projects_locations-intercept-endpoint-group-associations-get.md'
    - 'Locations Intercept Endpoint Group Associations List': 'projects_locations-intercept-endpoint-group-associations-list.md'
    - 'Locations Intercept Endpoint Group Associations Patch': 'projects_locations-intercept-endpoint-group-associations-patch.md'
    - 'Locations Intercept Endpoint Groups Create': 'projects_locations-intercept-endpoint-groups-create.md'
    - 'Locations Intercept Endpoint Groups Delete': 'projects_locations-intercept-endpoint-groups-delete.md'
    - 'Locations Intercept Endpoint Groups Get': 'projects_locations-intercept-endpoint-groups-get.md'
    - 'Locations Intercept Endpoint Groups List': 'projects_locations-intercept-endpoint-groups-list.md'
    - 'Locations Intercept Endpoint Groups Patch': 'projects_locations-intercept-endpoint-groups-patch.md'
    - 'Locations List': 'projects_locations-list.md'
    - 'Locations Mirroring Deployment Groups Create': 'projects_locations-mirroring-deployment-groups-create.md'
    - 'Locations Mirroring Deployment Groups Delete': 'projects_locations-mirroring-deployment-groups-delete.md'
    - 'Locations Mirroring Deployment Groups Get': 'projects_locations-mirroring-deployment-groups-get.md'
    - 'Locations Mirroring Deployment Groups List': 'projects_locations-mirroring-deployment-groups-list.md'
    - 'Locations Mirroring Deployment Groups Patch': 'projects_locations-mirroring-deployment-groups-patch.md'
    - 'Locations Mirroring Deployments Create': 'projects_locations-mirroring-deployments-create.md'
    - 'Locations Mirroring Deployments Delete': 'projects_locations-mirroring-deployments-delete.md'
    - 'Locations Mirroring Deployments Get': 'projects_locations-mirroring-deployments-get.md'
    - 'Locations Mirroring Deployments List': 'projects_locations-mirroring-deployments-list.md'
    - 'Locations Mirroring Deployments Patch': 'projects_locations-mirroring-deployments-patch.md'
    - 'Locations Mirroring Endpoint Group Associations Create': 'projects_locations-mirroring-endpoint-group-associations-create.md'
    - 'Locations Mirroring Endpoint Group Associations Delete': 'projects_locations-mirroring-endpoint-group-associations-delete.md'
    - 'Locations Mirroring Endpoint Group Associations Get': 'projects_locations-mirroring-endpoint-group-associations-get.md'
    - 'Locations Mirroring Endpoint Group Associations List': 'projects_locations-mirroring-endpoint-group-associations-list.md'
    - 'Locations Mirroring Endpoint Group Associations Patch': 'projects_locations-mirroring-endpoint-group-associations-patch.md'
    - 'Locations Mirroring Endpoint Groups Create': 'projects_locations-mirroring-endpoint-groups-create.md'
    - 'Locations Mirroring Endpoint Groups Delete': 'projects_locations-mirroring-endpoint-groups-delete.md'
    - 'Locations Mirroring Endpoint Groups Get': 'projects_locations-mirroring-endpoint-groups-get.md'
    - 'Locations Mirroring Endpoint Groups List': 'projects_locations-mirroring-endpoint-groups-list.md'
    - 'Locations Mirroring Endpoint Groups Patch': 'projects_locations-mirroring-endpoint-groups-patch.md'
    - 'Locations Operations Cancel': 'projects_locations-operations-cancel.md'
    - 'Locations Operations Delete': 'projects_locations-operations-delete.md'
    - 'Locations Operations Get': 'projects_locations-operations-get.md'
    - 'Locations Operations List': 'projects_locations-operations-list.md'
    - 'Locations Server Tls Policies Create': 'projects_locations-server-tls-policies-create.md'
    - 'Locations Server Tls Policies Delete': 'projects_locations-server-tls-policies-delete.md'
    - 'Locations Server Tls Policies Get': 'projects_locations-server-tls-policies-get.md'
    - 'Locations Server Tls Policies Get Iam Policy': 'projects_locations-server-tls-policies-get-iam-policy.md'
    - 'Locations Server Tls Policies List': 'projects_locations-server-tls-policies-list.md'
    - 'Locations Server Tls Policies Patch': 'projects_locations-server-tls-policies-patch.md'
    - 'Locations Server Tls Policies Set Iam Policy': 'projects_locations-server-tls-policies-set-iam-policy.md'
    - 'Locations Server Tls Policies Test Iam Permissions': 'projects_locations-server-tls-policies-test-iam-permissions.md'
    - 'Locations Tls Inspection Policies Create': 'projects_locations-tls-inspection-policies-create.md'
    - 'Locations Tls Inspection Policies Delete': 'projects_locations-tls-inspection-policies-delete.md'
    - 'Locations Tls Inspection Policies Get': 'projects_locations-tls-inspection-policies-get.md'
    - 'Locations Tls Inspection Policies List': 'projects_locations-tls-inspection-policies-list.md'
    - 'Locations Tls Inspection Policies Patch': 'projects_locations-tls-inspection-policies-patch.md'
    - 'Locations Url Lists Create': 'projects_locations-url-lists-create.md'
    - 'Locations Url Lists Delete': 'projects_locations-url-lists-delete.md'
    - 'Locations Url Lists Get': 'projects_locations-url-lists-get.md'
    - 'Locations Url Lists List': 'projects_locations-url-lists-list.md'
    - 'Locations Url Lists Patch': 'projects_locations-url-lists-patch.md'

theme: readthedocs

copyright: Copyright &copy; 2015â€“2024, `Sebastian Thiel`
