site_name: fitness v2.0.0+20210323
site_url: http://byron.github.io/google-apis-rs/google-fitness1-cli
site_description: A complete library to interact with fitness (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/fitness1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['users_data-sources-create.md', 'Users', 'Data Sources Create']
- ['users_data-sources-data-point-changes-list.md', 'Users', 'Data Sources Data Point Changes List']
- ['users_data-sources-datasets-delete.md', 'Users', 'Data Sources Datasets Delete']
- ['users_data-sources-datasets-get.md', 'Users', 'Data Sources Datasets Get']
- ['users_data-sources-datasets-patch.md', 'Users', 'Data Sources Datasets Patch']
- ['users_data-sources-delete.md', 'Users', 'Data Sources Delete']
- ['users_data-sources-get.md', 'Users', 'Data Sources Get']
- ['users_data-sources-list.md', 'Users', 'Data Sources List']
- ['users_data-sources-update.md', 'Users', 'Data Sources Update']
- ['users_dataset-aggregate.md', 'Users', 'Dataset Aggregate']
- ['users_sessions-delete.md', 'Users', 'Sessions Delete']
- ['users_sessions-list.md', 'Users', 'Sessions List']
- ['users_sessions-update.md', 'Users', 'Sessions Update']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

