site_name: cloudlatencytest v1.0.13+20160309
site_url: http://byron.github.io/google-apis-rs/google-cloudlatencytest2-cli
site_description: A complete library to interact with cloudlatencytest (protocol v2)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/cloudlatencytest2-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['statscollection_updateaggregatedstats.md', 'Statscollection', 'Updateaggregatedstats']
- ['statscollection_updatestats.md', 'Statscollection', 'Updatestats']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

