site_name: Service Networking v1.0.7+20181011
site_url: http://byron.github.io/google-apis-rs/google-servicenetworking1_beta-cli
site_description: A complete library to interact with Service Networking (protocol v1beta)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/servicenetworking1_beta-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['operations_get.md', 'Operations', 'Get']
- ['services_add-subnetwork.md', 'Services', 'Add Subnetwork']
- ['services_connections-create.md', 'Services', 'Connections Create']
- ['services_connections-list.md', 'Services', 'Connections List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

