site_name: Artifact Registry v2.0.5+20210324
site_url: http://byron.github.io/google-apis-rs/google-artifactregistry1-cli
site_description: A complete library to interact with Artifact Registry (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/artifactregistry1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['operations_cancel.md', 'Operations', 'Cancel']
- ['operations_delete.md', 'Operations', 'Delete']
- ['operations_get.md', 'Operations', 'Get']
- ['operations_list.md', 'Operations', 'List']
- ['projects_locations-repositories-docker-images-list.md', 'Projects', 'Locations Repositories Docker Images List']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

