site_name: licensing v4.0.1+20220305
site_url: http://byron.github.io/google-apis-rs/google-licensing1-cli
site_description: A complete library to interact with licensing (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/licensing1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['license-assignments_delete.md', 'License Assignments', 'Delete']
- ['license-assignments_get.md', 'License Assignments', 'Get']
- ['license-assignments_insert.md', 'License Assignments', 'Insert']
- ['license-assignments_list-for-product.md', 'License Assignments', 'List For Product']
- ['license-assignments_list-for-product-and-sku.md', 'License Assignments', 'List For Product And Sku']
- ['license-assignments_patch.md', 'License Assignments', 'Patch']
- ['license-assignments_update.md', 'License Assignments', 'Update']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

