site_name: Speech v2.0.3+20210325
site_url: http://byron.github.io/google-apis-rs/google-speech1-cli
site_description: A complete library to interact with Speech (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/speech1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['operations_get.md', 'Operations', 'Get']
- ['operations_list.md', 'Operations', 'List']
- ['speech_longrunningrecognize.md', 'Speech', 'Longrunningrecognize']
- ['speech_recognize.md', 'Speech', 'Recognize']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

