site_name: Drive Activity v4.0.1+20220301
site_url: http://byron.github.io/google-apis-rs/google-driveactivity2-cli
site_description: A complete library to interact with Drive Activity (protocol v2)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/driveactivity2-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['activity_query.md', 'Activity', 'Query']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

