site_name: Firebase Remote Config v1.0.9+20171129
site_url: http://byron.github.io/google-apis-rs/google-firebaseremoteconfig1-cli
site_description: A complete library to interact with Firebase Remote Config (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/firebaseremoteconfig1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_get-remote-config.md', 'Projects', 'Get Remote Config']
- ['projects_update-remote-config.md', 'Projects', 'Update Remote Config']

theme: readthedocs

copyright: Copyright &copy; 2015-2019, `Sebastian Thiel`

