site_name: Dataproc Metastore v2.0.4+20210325
site_url: http://byron.github.io/google-apis-rs/google-metastore1_beta-cli
site_description: A complete library to interact with Dataproc Metastore (protocol v1beta)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/metastore1_beta-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_locations-get.md', 'Projects', 'Locations Get']
- ['projects_locations-list.md', 'Projects', 'Locations List']
- ['projects_locations-operations-delete.md', 'Projects', 'Locations Operations Delete']
- ['projects_locations-operations-get.md', 'Projects', 'Locations Operations Get']
- ['projects_locations-operations-list.md', 'Projects', 'Locations Operations List']
- ['projects_locations-services-backups-create.md', 'Projects', 'Locations Services Backups Create']
- ['projects_locations-services-backups-delete.md', 'Projects', 'Locations Services Backups Delete']
- ['projects_locations-services-backups-get.md', 'Projects', 'Locations Services Backups Get']
- ['projects_locations-services-backups-list.md', 'Projects', 'Locations Services Backups List']
- ['projects_locations-services-create.md', 'Projects', 'Locations Services Create']
- ['projects_locations-services-delete.md', 'Projects', 'Locations Services Delete']
- ['projects_locations-services-export-metadata.md', 'Projects', 'Locations Services Export Metadata']
- ['projects_locations-services-get.md', 'Projects', 'Locations Services Get']
- ['projects_locations-services-get-iam-policy.md', 'Projects', 'Locations Services Get Iam Policy']
- ['projects_locations-services-list.md', 'Projects', 'Locations Services List']
- ['projects_locations-services-metadata-imports-create.md', 'Projects', 'Locations Services Metadata Imports Create']
- ['projects_locations-services-metadata-imports-get.md', 'Projects', 'Locations Services Metadata Imports Get']
- ['projects_locations-services-metadata-imports-list.md', 'Projects', 'Locations Services Metadata Imports List']
- ['projects_locations-services-metadata-imports-patch.md', 'Projects', 'Locations Services Metadata Imports Patch']
- ['projects_locations-services-patch.md', 'Projects', 'Locations Services Patch']
- ['projects_locations-services-restore.md', 'Projects', 'Locations Services Restore']
- ['projects_locations-services-set-iam-policy.md', 'Projects', 'Locations Services Set Iam Policy']
- ['projects_locations-services-test-iam-permissions.md', 'Projects', 'Locations Services Test Iam Permissions']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

