site_name: QPX Express v3.0.0+20160708
site_url: http://byron.github.io/google-apis-rs/google-qpxexpress1-cli
site_description: A complete library to interact with QPX Express (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/qpxexpress1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['trips_search.md', 'Trips', 'Search']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

