site_name: BigQuery Reservation v7.0.0+20251207
site_url: http://byron.github.io/google-apis-rs/google-bigqueryreservation1-cli
site_description: A complete library to interact with BigQuery Reservation (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/bigqueryreservation1-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Projects':
    - 'Locations Capacity Commitments Create': 'projects_locations-capacity-commitments-create.md'
    - 'Locations Capacity Commitments Delete': 'projects_locations-capacity-commitments-delete.md'
    - 'Locations Capacity Commitments Get': 'projects_locations-capacity-commitments-get.md'
    - 'Locations Capacity Commitments List': 'projects_locations-capacity-commitments-list.md'
    - 'Locations Capacity Commitments Merge': 'projects_locations-capacity-commitments-merge.md'
    - 'Locations Capacity Commitments Patch': 'projects_locations-capacity-commitments-patch.md'
    - 'Locations Capacity Commitments Split': 'projects_locations-capacity-commitments-split.md'
    - 'Locations Get Bi Reservation': 'projects_locations-get-bi-reservation.md'
    - 'Locations Reservation Groups Create': 'projects_locations-reservation-groups-create.md'
    - 'Locations Reservation Groups Delete': 'projects_locations-reservation-groups-delete.md'
    - 'Locations Reservation Groups Get': 'projects_locations-reservation-groups-get.md'
    - 'Locations Reservation Groups List': 'projects_locations-reservation-groups-list.md'
    - 'Locations Reservations Assignments Create': 'projects_locations-reservations-assignments-create.md'
    - 'Locations Reservations Assignments Delete': 'projects_locations-reservations-assignments-delete.md'
    - 'Locations Reservations Assignments Get Iam Policy': 'projects_locations-reservations-assignments-get-iam-policy.md'
    - 'Locations Reservations Assignments List': 'projects_locations-reservations-assignments-list.md'
    - 'Locations Reservations Assignments Move': 'projects_locations-reservations-assignments-move.md'
    - 'Locations Reservations Assignments Patch': 'projects_locations-reservations-assignments-patch.md'
    - 'Locations Reservations Assignments Set Iam Policy': 'projects_locations-reservations-assignments-set-iam-policy.md'
    - 'Locations Reservations Assignments Test Iam Permissions': 'projects_locations-reservations-assignments-test-iam-permissions.md'
    - 'Locations Reservations Create': 'projects_locations-reservations-create.md'
    - 'Locations Reservations Delete': 'projects_locations-reservations-delete.md'
    - 'Locations Reservations Failover Reservation': 'projects_locations-reservations-failover-reservation.md'
    - 'Locations Reservations Get': 'projects_locations-reservations-get.md'
    - 'Locations Reservations Get Iam Policy': 'projects_locations-reservations-get-iam-policy.md'
    - 'Locations Reservations List': 'projects_locations-reservations-list.md'
    - 'Locations Reservations Patch': 'projects_locations-reservations-patch.md'
    - 'Locations Reservations Set Iam Policy': 'projects_locations-reservations-set-iam-policy.md'
    - 'Locations Reservations Test Iam Permissions': 'projects_locations-reservations-test-iam-permissions.md'
    - 'Locations Search All Assignments': 'projects_locations-search-all-assignments.md'
    - 'Locations Search Assignments': 'projects_locations-search-assignments.md'
    - 'Locations Update Bi Reservation': 'projects_locations-update-bi-reservation.md'

theme: readthedocs

copyright: Copyright &copy; 2015â€“2024, `Sebastian Thiel`
