site_name: Firebase Realtime Database v4.0.1+20220304
site_url: http://byron.github.io/google-apis-rs/google-firebasedatabase1_beta-cli
site_description: A complete library to interact with Firebase Realtime Database (protocol v1beta)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/firebasedatabase1_beta-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_locations-instances-create.md', 'Projects', 'Locations Instances Create']
- ['projects_locations-instances-delete.md', 'Projects', 'Locations Instances Delete']
- ['projects_locations-instances-disable.md', 'Projects', 'Locations Instances Disable']
- ['projects_locations-instances-get.md', 'Projects', 'Locations Instances Get']
- ['projects_locations-instances-list.md', 'Projects', 'Locations Instances List']
- ['projects_locations-instances-reenable.md', 'Projects', 'Locations Instances Reenable']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

