site_name: Monitoring v2.0.4+20210322
site_url: http://byron.github.io/google-apis-rs/google-monitoring3-cli
site_description: A complete library to interact with Monitoring (protocol v3)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/monitoring3-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['folders_time-series-list.md', 'Folders', 'Time Series List']
- ['organizations_time-series-list.md', 'Organizations', 'Time Series List']
- ['projects_alert-policies-create.md', 'Projects', 'Alert Policies Create']
- ['projects_alert-policies-delete.md', 'Projects', 'Alert Policies Delete']
- ['projects_alert-policies-get.md', 'Projects', 'Alert Policies Get']
- ['projects_alert-policies-list.md', 'Projects', 'Alert Policies List']
- ['projects_alert-policies-patch.md', 'Projects', 'Alert Policies Patch']
- ['projects_collectd-time-series-create.md', 'Projects', 'Collectd Time Series Create']
- ['projects_groups-create.md', 'Projects', 'Groups Create']
- ['projects_groups-delete.md', 'Projects', 'Groups Delete']
- ['projects_groups-get.md', 'Projects', 'Groups Get']
- ['projects_groups-list.md', 'Projects', 'Groups List']
- ['projects_groups-members-list.md', 'Projects', 'Groups Members List']
- ['projects_groups-update.md', 'Projects', 'Groups Update']
- ['projects_metric-descriptors-create.md', 'Projects', 'Metric Descriptors Create']
- ['projects_metric-descriptors-delete.md', 'Projects', 'Metric Descriptors Delete']
- ['projects_metric-descriptors-get.md', 'Projects', 'Metric Descriptors Get']
- ['projects_metric-descriptors-list.md', 'Projects', 'Metric Descriptors List']
- ['projects_monitored-resource-descriptors-get.md', 'Projects', 'Monitored Resource Descriptors Get']
- ['projects_monitored-resource-descriptors-list.md', 'Projects', 'Monitored Resource Descriptors List']
- ['projects_notification-channel-descriptors-get.md', 'Projects', 'Notification Channel Descriptors Get']
- ['projects_notification-channel-descriptors-list.md', 'Projects', 'Notification Channel Descriptors List']
- ['projects_notification-channels-create.md', 'Projects', 'Notification Channels Create']
- ['projects_notification-channels-delete.md', 'Projects', 'Notification Channels Delete']
- ['projects_notification-channels-get.md', 'Projects', 'Notification Channels Get']
- ['projects_notification-channels-get-verification-code.md', 'Projects', 'Notification Channels Get Verification Code']
- ['projects_notification-channels-list.md', 'Projects', 'Notification Channels List']
- ['projects_notification-channels-patch.md', 'Projects', 'Notification Channels Patch']
- ['projects_notification-channels-send-verification-code.md', 'Projects', 'Notification Channels Send Verification Code']
- ['projects_notification-channels-verify.md', 'Projects', 'Notification Channels Verify']
- ['projects_time-series-create.md', 'Projects', 'Time Series Create']
- ['projects_time-series-list.md', 'Projects', 'Time Series List']
- ['projects_time-series-query.md', 'Projects', 'Time Series Query']
- ['projects_uptime-check-configs-create.md', 'Projects', 'Uptime Check Configs Create']
- ['projects_uptime-check-configs-delete.md', 'Projects', 'Uptime Check Configs Delete']
- ['projects_uptime-check-configs-get.md', 'Projects', 'Uptime Check Configs Get']
- ['projects_uptime-check-configs-list.md', 'Projects', 'Uptime Check Configs List']
- ['projects_uptime-check-configs-patch.md', 'Projects', 'Uptime Check Configs Patch']
- ['services_create.md', 'Services', 'Create']
- ['services_delete.md', 'Services', 'Delete']
- ['services_get.md', 'Services', 'Get']
- ['services_list.md', 'Services', 'List']
- ['services_patch.md', 'Services', 'Patch']
- ['services_service-level-objectives-create.md', 'Services', 'Service Level Objectives Create']
- ['services_service-level-objectives-delete.md', 'Services', 'Service Level Objectives Delete']
- ['services_service-level-objectives-get.md', 'Services', 'Service Level Objectives Get']
- ['services_service-level-objectives-list.md', 'Services', 'Service Level Objectives List']
- ['services_service-level-objectives-patch.md', 'Services', 'Service Level Objectives Patch']
- ['uptime-check-ips_list.md', 'Uptime Check Ips', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

