site_name: Docs v2.0.0+20210323
site_url: http://byron.github.io/google-apis-rs/google-docs1-cli
site_description: A complete library to interact with Docs (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/docs1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['documents_batch-update.md', 'Documents', 'Batch Update']
- ['documents_create.md', 'Documents', 'Create']
- ['documents_get.md', 'Documents', 'Get']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

