site_name: Docs v5.0.3+20230119
site_url: http://byron.github.io/google-apis-rs/google-docs1-cli
site_description: A complete library to interact with Docs (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/docs1-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Documents':
    - 'Batch Update': 'documents_batch-update.md'
    - 'Create': 'documents_create.md'
    - 'Get': 'documents_get.md'

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

