site_name: Android Provisioning Partner v1.0.7+20171202
site_url: http://byron.github.io/google-apis-rs/google-androiddeviceprovisioning1-cli
site_description: A complete library to interact with Android Provisioning Partner (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/androiddeviceprovisioning1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['operations_get.md', 'Operations', 'Get']
- ['partners_customers-create.md', 'Partners', 'Customers Create']
- ['partners_customers-list.md', 'Partners', 'Customers List']
- ['partners_devices-claim.md', 'Partners', 'Devices Claim']
- ['partners_devices-claim-async.md', 'Partners', 'Devices Claim Async']
- ['partners_devices-find-by-identifier.md', 'Partners', 'Devices Find By Identifier']
- ['partners_devices-find-by-owner.md', 'Partners', 'Devices Find By Owner']
- ['partners_devices-get.md', 'Partners', 'Devices Get']
- ['partners_devices-metadata.md', 'Partners', 'Devices Metadata']
- ['partners_devices-unclaim.md', 'Partners', 'Devices Unclaim']
- ['partners_devices-unclaim-async.md', 'Partners', 'Devices Unclaim Async']
- ['partners_devices-update-metadata-async.md', 'Partners', 'Devices Update Metadata Async']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

