site_name: Ad Exchange Buyer v1.0.7+20180823
site_url: http://byron.github.io/google-apis-rs/google-adexchangebuyer1d3-cli
site_description: A complete library to interact with Ad Exchange Buyer (protocol v1.3)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/adexchangebuyer1d3-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['accounts_get.md', 'Accounts', 'Get']
- ['accounts_list.md', 'Accounts', 'List']
- ['accounts_patch.md', 'Accounts', 'Patch']
- ['accounts_update.md', 'Accounts', 'Update']
- ['billing-info_get.md', 'Billing Info', 'Get']
- ['billing-info_list.md', 'Billing Info', 'List']
- ['budget_get.md', 'Budget', 'Get']
- ['budget_patch.md', 'Budget', 'Patch']
- ['budget_update.md', 'Budget', 'Update']
- ['creatives_get.md', 'Creatives', 'Get']
- ['creatives_insert.md', 'Creatives', 'Insert']
- ['creatives_list.md', 'Creatives', 'List']
- ['direct-deals_get.md', 'Direct Deals', 'Get']
- ['direct-deals_list.md', 'Direct Deals', 'List']
- ['performance-report_list.md', 'Performance Report', 'List']
- ['pretargeting-config_delete.md', 'Pretargeting Config', 'Delete']
- ['pretargeting-config_get.md', 'Pretargeting Config', 'Get']
- ['pretargeting-config_insert.md', 'Pretargeting Config', 'Insert']
- ['pretargeting-config_list.md', 'Pretargeting Config', 'List']
- ['pretargeting-config_patch.md', 'Pretargeting Config', 'Patch']
- ['pretargeting-config_update.md', 'Pretargeting Config', 'Update']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

