site_name: Api Keys Service v4.0.1+20220305
site_url: http://byron.github.io/google-apis-rs/google-apikeys2-cli
site_description: A complete library to interact with Api Keys Service (protocol v2)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/apikeys2-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['keys_lookup-key.md', 'Keys', 'Lookup Key']
- ['operations_get.md', 'Operations', 'Get']
- ['projects_locations-keys-clone.md', 'Projects', 'Locations Keys Clone']
- ['projects_locations-keys-create.md', 'Projects', 'Locations Keys Create']
- ['projects_locations-keys-delete.md', 'Projects', 'Locations Keys Delete']
- ['projects_locations-keys-get.md', 'Projects', 'Locations Keys Get']
- ['projects_locations-keys-get-key-string.md', 'Projects', 'Locations Keys Get Key String']
- ['projects_locations-keys-list.md', 'Projects', 'Locations Keys List']
- ['projects_locations-keys-patch.md', 'Projects', 'Locations Keys Patch']
- ['projects_locations-keys-undelete.md', 'Projects', 'Locations Keys Undelete']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

