site_name: Blogger v2.0.0+20210331
site_url: http://byron.github.io/google-apis-rs/google-blogger3-cli
site_description: A complete library to interact with Blogger (protocol v3)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/blogger3-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['blog-user-infos_get.md', 'Blog User Infos', 'Get']
- ['blogs_get.md', 'Blogs', 'Get']
- ['blogs_get-by-url.md', 'Blogs', 'Get By Url']
- ['blogs_list-by-user.md', 'Blogs', 'List By User']
- ['comments_approve.md', 'Comments', 'Approve']
- ['comments_delete.md', 'Comments', 'Delete']
- ['comments_get.md', 'Comments', 'Get']
- ['comments_list.md', 'Comments', 'List']
- ['comments_list-by-blog.md', 'Comments', 'List By Blog']
- ['comments_mark-as-spam.md', 'Comments', 'Mark As Spam']
- ['comments_remove-content.md', 'Comments', 'Remove Content']
- ['page-views_get.md', 'Page Views', 'Get']
- ['pages_delete.md', 'Pages', 'Delete']
- ['pages_get.md', 'Pages', 'Get']
- ['pages_insert.md', 'Pages', 'Insert']
- ['pages_list.md', 'Pages', 'List']
- ['pages_patch.md', 'Pages', 'Patch']
- ['pages_publish.md', 'Pages', 'Publish']
- ['pages_revert.md', 'Pages', 'Revert']
- ['pages_update.md', 'Pages', 'Update']
- ['post-user-infos_get.md', 'Post User Infos', 'Get']
- ['post-user-infos_list.md', 'Post User Infos', 'List']
- ['posts_delete.md', 'Posts', 'Delete']
- ['posts_get.md', 'Posts', 'Get']
- ['posts_get-by-path.md', 'Posts', 'Get By Path']
- ['posts_insert.md', 'Posts', 'Insert']
- ['posts_list.md', 'Posts', 'List']
- ['posts_patch.md', 'Posts', 'Patch']
- ['posts_publish.md', 'Posts', 'Publish']
- ['posts_revert.md', 'Posts', 'Revert']
- ['posts_search.md', 'Posts', 'Search']
- ['posts_update.md', 'Posts', 'Update']
- ['users_get.md', 'Users', 'Get']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

