site_name: plusDomains v1.0.9+20190616
site_url: http://byron.github.io/google-apis-rs/google-plusdomains1-cli
site_description: A complete library to interact with plusDomains (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/plusdomains1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['activities_get.md', 'Activities', 'Get']
- ['activities_list.md', 'Activities', 'List']
- ['audiences_list.md', 'Audiences', 'List']
- ['circles_list.md', 'Circles', 'List']
- ['comments_get.md', 'Comments', 'Get']
- ['comments_list.md', 'Comments', 'List']
- ['media_insert.md', 'Media', 'Insert']
- ['people_get.md', 'People', 'Get']
- ['people_list.md', 'People', 'List']
- ['people_list-by-activity.md', 'People', 'List By Activity']

theme: readthedocs

copyright: Copyright &copy; 2015-2019, `Sebastian Thiel`

