site_name: Recommender v2.0.8+20210319
site_url: http://byron.github.io/google-apis-rs/google-recommender1-cli
site_description: A complete library to interact with Recommender (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/recommender1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['billing-accounts_locations-insight-types-insights-get.md', 'Billing Accounts', 'Locations Insight Types Insights Get']
- ['billing-accounts_locations-insight-types-insights-list.md', 'Billing Accounts', 'Locations Insight Types Insights List']
- ['billing-accounts_locations-insight-types-insights-mark-accepted.md', 'Billing Accounts', 'Locations Insight Types Insights Mark Accepted']
- ['billing-accounts_locations-recommenders-recommendations-get.md', 'Billing Accounts', 'Locations Recommenders Recommendations Get']
- ['billing-accounts_locations-recommenders-recommendations-list.md', 'Billing Accounts', 'Locations Recommenders Recommendations List']
- ['billing-accounts_locations-recommenders-recommendations-mark-claimed.md', 'Billing Accounts', 'Locations Recommenders Recommendations Mark Claimed']
- ['billing-accounts_locations-recommenders-recommendations-mark-failed.md', 'Billing Accounts', 'Locations Recommenders Recommendations Mark Failed']
- ['billing-accounts_locations-recommenders-recommendations-mark-succeeded.md', 'Billing Accounts', 'Locations Recommenders Recommendations Mark Succeeded']
- ['folders_locations-insight-types-insights-get.md', 'Folders', 'Locations Insight Types Insights Get']
- ['folders_locations-insight-types-insights-list.md', 'Folders', 'Locations Insight Types Insights List']
- ['folders_locations-insight-types-insights-mark-accepted.md', 'Folders', 'Locations Insight Types Insights Mark Accepted']
- ['folders_locations-recommenders-recommendations-get.md', 'Folders', 'Locations Recommenders Recommendations Get']
- ['folders_locations-recommenders-recommendations-list.md', 'Folders', 'Locations Recommenders Recommendations List']
- ['folders_locations-recommenders-recommendations-mark-claimed.md', 'Folders', 'Locations Recommenders Recommendations Mark Claimed']
- ['folders_locations-recommenders-recommendations-mark-failed.md', 'Folders', 'Locations Recommenders Recommendations Mark Failed']
- ['folders_locations-recommenders-recommendations-mark-succeeded.md', 'Folders', 'Locations Recommenders Recommendations Mark Succeeded']
- ['organizations_locations-insight-types-insights-get.md', 'Organizations', 'Locations Insight Types Insights Get']
- ['organizations_locations-insight-types-insights-list.md', 'Organizations', 'Locations Insight Types Insights List']
- ['organizations_locations-insight-types-insights-mark-accepted.md', 'Organizations', 'Locations Insight Types Insights Mark Accepted']
- ['organizations_locations-recommenders-recommendations-get.md', 'Organizations', 'Locations Recommenders Recommendations Get']
- ['organizations_locations-recommenders-recommendations-list.md', 'Organizations', 'Locations Recommenders Recommendations List']
- ['organizations_locations-recommenders-recommendations-mark-claimed.md', 'Organizations', 'Locations Recommenders Recommendations Mark Claimed']
- ['organizations_locations-recommenders-recommendations-mark-failed.md', 'Organizations', 'Locations Recommenders Recommendations Mark Failed']
- ['organizations_locations-recommenders-recommendations-mark-succeeded.md', 'Organizations', 'Locations Recommenders Recommendations Mark Succeeded']
- ['projects_locations-insight-types-insights-get.md', 'Projects', 'Locations Insight Types Insights Get']
- ['projects_locations-insight-types-insights-list.md', 'Projects', 'Locations Insight Types Insights List']
- ['projects_locations-insight-types-insights-mark-accepted.md', 'Projects', 'Locations Insight Types Insights Mark Accepted']
- ['projects_locations-recommenders-recommendations-get.md', 'Projects', 'Locations Recommenders Recommendations Get']
- ['projects_locations-recommenders-recommendations-list.md', 'Projects', 'Locations Recommenders Recommendations List']
- ['projects_locations-recommenders-recommendations-mark-claimed.md', 'Projects', 'Locations Recommenders Recommendations Mark Claimed']
- ['projects_locations-recommenders-recommendations-mark-failed.md', 'Projects', 'Locations Recommenders Recommendations Mark Failed']
- ['projects_locations-recommenders-recommendations-mark-succeeded.md', 'Projects', 'Locations Recommenders Recommendations Mark Succeeded']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

