site_name: Area120 Tables v2.0.5+20210330
site_url: http://byron.github.io/google-apis-rs/google-area120tables1_alpha1-cli
site_description: A complete library to interact with Area120 Tables (protocol v1alpha1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/area120tables1_alpha1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['tables_get.md', 'Tables', 'Get']
- ['tables_list.md', 'Tables', 'List']
- ['tables_rows-batch-create.md', 'Tables', 'Rows Batch Create']
- ['tables_rows-batch-delete.md', 'Tables', 'Rows Batch Delete']
- ['tables_rows-batch-update.md', 'Tables', 'Rows Batch Update']
- ['tables_rows-create.md', 'Tables', 'Rows Create']
- ['tables_rows-delete.md', 'Tables', 'Rows Delete']
- ['tables_rows-get.md', 'Tables', 'Rows Get']
- ['tables_rows-list.md', 'Tables', 'Rows List']
- ['tables_rows-patch.md', 'Tables', 'Rows Patch']
- ['workspaces_get.md', 'Workspaces', 'Get']
- ['workspaces_list.md', 'Workspaces', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

