site_name: Service Registry v1.0.5+20160401
site_url: http://byron.github.io/google-apis-rs/google-serviceregistryalpha-cli
site_description: A complete library to interact with Service Registry (protocol alpha)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/serviceregistryalpha-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['endpoints_delete.md', 'Endpoints', 'Delete']
- ['endpoints_get.md', 'Endpoints', 'Get']
- ['endpoints_insert.md', 'Endpoints', 'Insert']
- ['endpoints_list.md', 'Endpoints', 'List']
- ['endpoints_patch.md', 'Endpoints', 'Patch']
- ['endpoints_update.md', 'Endpoints', 'Update']
- ['operations_get.md', 'Operations', 'Get']
- ['operations_list.md', 'Operations', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

