site_name: proximitybeacon v1.0.7+20181008
site_url: http://byron.github.io/google-apis-rs/google-proximitybeacon1_beta1-cli
site_description: A complete library to interact with proximitybeacon (protocol v1beta1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/proximitybeacon1_beta1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['beaconinfo_getforobserved.md', 'Beaconinfo', 'Getforobserved']
- ['beacons_activate.md', 'Beacons', 'Activate']
- ['beacons_attachments-batch-delete.md', 'Beacons', 'Attachments Batch Delete']
- ['beacons_attachments-create.md', 'Beacons', 'Attachments Create']
- ['beacons_attachments-delete.md', 'Beacons', 'Attachments Delete']
- ['beacons_attachments-list.md', 'Beacons', 'Attachments List']
- ['beacons_deactivate.md', 'Beacons', 'Deactivate']
- ['beacons_decommission.md', 'Beacons', 'Decommission']
- ['beacons_delete.md', 'Beacons', 'Delete']
- ['beacons_diagnostics-list.md', 'Beacons', 'Diagnostics List']
- ['beacons_get.md', 'Beacons', 'Get']
- ['beacons_list.md', 'Beacons', 'List']
- ['beacons_register.md', 'Beacons', 'Register']
- ['beacons_update.md', 'Beacons', 'Update']
- ['methods_get-eidparams.md', 'Methods', 'Get Eidparams']
- ['namespaces_list.md', 'Namespaces', 'List']
- ['namespaces_update.md', 'Namespaces', 'Update']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

