site_name: Dataproc v7.0.0+20251203
site_url: http://byron.github.io/google-apis-rs/google-dataproc1-cli
site_description: A complete library to interact with Dataproc (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/dataproc1-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Projects':
    - 'Locations Autoscaling Policies Create': 'projects_locations-autoscaling-policies-create.md'
    - 'Locations Autoscaling Policies Delete': 'projects_locations-autoscaling-policies-delete.md'
    - 'Locations Autoscaling Policies Get': 'projects_locations-autoscaling-policies-get.md'
    - 'Locations Autoscaling Policies Get Iam Policy': 'projects_locations-autoscaling-policies-get-iam-policy.md'
    - 'Locations Autoscaling Policies List': 'projects_locations-autoscaling-policies-list.md'
    - 'Locations Autoscaling Policies Set Iam Policy': 'projects_locations-autoscaling-policies-set-iam-policy.md'
    - 'Locations Autoscaling Policies Test Iam Permissions': 'projects_locations-autoscaling-policies-test-iam-permissions.md'
    - 'Locations Autoscaling Policies Update': 'projects_locations-autoscaling-policies-update.md'
    - 'Locations Batches Analyze': 'projects_locations-batches-analyze.md'
    - 'Locations Batches Create': 'projects_locations-batches-create.md'
    - 'Locations Batches Delete': 'projects_locations-batches-delete.md'
    - 'Locations Batches Get': 'projects_locations-batches-get.md'
    - 'Locations Batches List': 'projects_locations-batches-list.md'
    - 'Locations Batches Spark Applications Access': 'projects_locations-batches-spark-applications-access.md'
    - 'Locations Batches Spark Applications Access Environment Info': 'projects_locations-batches-spark-applications-access-environment-info.md'
    - 'Locations Batches Spark Applications Access Job': 'projects_locations-batches-spark-applications-access-job.md'
    - 'Locations Batches Spark Applications Access Sql Plan': 'projects_locations-batches-spark-applications-access-sql-plan.md'
    - 'Locations Batches Spark Applications Access Sql Query': 'projects_locations-batches-spark-applications-access-sql-query.md'
    - 'Locations Batches Spark Applications Access Stage Attempt': 'projects_locations-batches-spark-applications-access-stage-attempt.md'
    - 'Locations Batches Spark Applications Access Stage Rdd Graph': 'projects_locations-batches-spark-applications-access-stage-rdd-graph.md'
    - 'Locations Batches Spark Applications Search': 'projects_locations-batches-spark-applications-search.md'
    - 'Locations Batches Spark Applications Search Executor Stage Summary': 'projects_locations-batches-spark-applications-search-executor-stage-summary.md'
    - 'Locations Batches Spark Applications Search Executors': 'projects_locations-batches-spark-applications-search-executors.md'
    - 'Locations Batches Spark Applications Search Jobs': 'projects_locations-batches-spark-applications-search-jobs.md'
    - 'Locations Batches Spark Applications Search Sql Queries': 'projects_locations-batches-spark-applications-search-sql-queries.md'
    - 'Locations Batches Spark Applications Search Stage Attempt Tasks': 'projects_locations-batches-spark-applications-search-stage-attempt-tasks.md'
    - 'Locations Batches Spark Applications Search Stage Attempts': 'projects_locations-batches-spark-applications-search-stage-attempts.md'
    - 'Locations Batches Spark Applications Search Stages': 'projects_locations-batches-spark-applications-search-stages.md'
    - 'Locations Batches Spark Applications Summarize Executors': 'projects_locations-batches-spark-applications-summarize-executors.md'
    - 'Locations Batches Spark Applications Summarize Jobs': 'projects_locations-batches-spark-applications-summarize-jobs.md'
    - 'Locations Batches Spark Applications Summarize Stage Attempt Tasks': 'projects_locations-batches-spark-applications-summarize-stage-attempt-tasks.md'
    - 'Locations Batches Spark Applications Summarize Stages': 'projects_locations-batches-spark-applications-summarize-stages.md'
    - 'Locations Batches Spark Applications Write': 'projects_locations-batches-spark-applications-write.md'
    - 'Locations Operations Cancel': 'projects_locations-operations-cancel.md'
    - 'Locations Operations Delete': 'projects_locations-operations-delete.md'
    - 'Locations Operations Get': 'projects_locations-operations-get.md'
    - 'Locations Operations List': 'projects_locations-operations-list.md'
    - 'Locations Session Templates Create': 'projects_locations-session-templates-create.md'
    - 'Locations Session Templates Delete': 'projects_locations-session-templates-delete.md'
    - 'Locations Session Templates Get': 'projects_locations-session-templates-get.md'
    - 'Locations Session Templates List': 'projects_locations-session-templates-list.md'
    - 'Locations Session Templates Patch': 'projects_locations-session-templates-patch.md'
    - 'Locations Sessions Create': 'projects_locations-sessions-create.md'
    - 'Locations Sessions Delete': 'projects_locations-sessions-delete.md'
    - 'Locations Sessions Get': 'projects_locations-sessions-get.md'
    - 'Locations Sessions List': 'projects_locations-sessions-list.md'
    - 'Locations Sessions Spark Applications Access': 'projects_locations-sessions-spark-applications-access.md'
    - 'Locations Sessions Spark Applications Access Environment Info': 'projects_locations-sessions-spark-applications-access-environment-info.md'
    - 'Locations Sessions Spark Applications Access Job': 'projects_locations-sessions-spark-applications-access-job.md'
    - 'Locations Sessions Spark Applications Access Sql Plan': 'projects_locations-sessions-spark-applications-access-sql-plan.md'
    - 'Locations Sessions Spark Applications Access Sql Query': 'projects_locations-sessions-spark-applications-access-sql-query.md'
    - 'Locations Sessions Spark Applications Access Stage Attempt': 'projects_locations-sessions-spark-applications-access-stage-attempt.md'
    - 'Locations Sessions Spark Applications Access Stage Rdd Graph': 'projects_locations-sessions-spark-applications-access-stage-rdd-graph.md'
    - 'Locations Sessions Spark Applications Search': 'projects_locations-sessions-spark-applications-search.md'
    - 'Locations Sessions Spark Applications Search Executor Stage Summary': 'projects_locations-sessions-spark-applications-search-executor-stage-summary.md'
    - 'Locations Sessions Spark Applications Search Executors': 'projects_locations-sessions-spark-applications-search-executors.md'
    - 'Locations Sessions Spark Applications Search Jobs': 'projects_locations-sessions-spark-applications-search-jobs.md'
    - 'Locations Sessions Spark Applications Search Sql Queries': 'projects_locations-sessions-spark-applications-search-sql-queries.md'
    - 'Locations Sessions Spark Applications Search Stage Attempt Tasks': 'projects_locations-sessions-spark-applications-search-stage-attempt-tasks.md'
    - 'Locations Sessions Spark Applications Search Stage Attempts': 'projects_locations-sessions-spark-applications-search-stage-attempts.md'
    - 'Locations Sessions Spark Applications Search Stages': 'projects_locations-sessions-spark-applications-search-stages.md'
    - 'Locations Sessions Spark Applications Summarize Executors': 'projects_locations-sessions-spark-applications-summarize-executors.md'
    - 'Locations Sessions Spark Applications Summarize Jobs': 'projects_locations-sessions-spark-applications-summarize-jobs.md'
    - 'Locations Sessions Spark Applications Summarize Stage Attempt Tasks': 'projects_locations-sessions-spark-applications-summarize-stage-attempt-tasks.md'
    - 'Locations Sessions Spark Applications Summarize Stages': 'projects_locations-sessions-spark-applications-summarize-stages.md'
    - 'Locations Sessions Spark Applications Write': 'projects_locations-sessions-spark-applications-write.md'
    - 'Locations Sessions Terminate': 'projects_locations-sessions-terminate.md'
    - 'Locations Workflow Templates Create': 'projects_locations-workflow-templates-create.md'
    - 'Locations Workflow Templates Delete': 'projects_locations-workflow-templates-delete.md'
    - 'Locations Workflow Templates Get': 'projects_locations-workflow-templates-get.md'
    - 'Locations Workflow Templates Get Iam Policy': 'projects_locations-workflow-templates-get-iam-policy.md'
    - 'Locations Workflow Templates Instantiate': 'projects_locations-workflow-templates-instantiate.md'
    - 'Locations Workflow Templates Instantiate Inline': 'projects_locations-workflow-templates-instantiate-inline.md'
    - 'Locations Workflow Templates List': 'projects_locations-workflow-templates-list.md'
    - 'Locations Workflow Templates Set Iam Policy': 'projects_locations-workflow-templates-set-iam-policy.md'
    - 'Locations Workflow Templates Test Iam Permissions': 'projects_locations-workflow-templates-test-iam-permissions.md'
    - 'Locations Workflow Templates Update': 'projects_locations-workflow-templates-update.md'
    - 'Regions Autoscaling Policies Create': 'projects_regions-autoscaling-policies-create.md'
    - 'Regions Autoscaling Policies Delete': 'projects_regions-autoscaling-policies-delete.md'
    - 'Regions Autoscaling Policies Get': 'projects_regions-autoscaling-policies-get.md'
    - 'Regions Autoscaling Policies Get Iam Policy': 'projects_regions-autoscaling-policies-get-iam-policy.md'
    - 'Regions Autoscaling Policies List': 'projects_regions-autoscaling-policies-list.md'
    - 'Regions Autoscaling Policies Set Iam Policy': 'projects_regions-autoscaling-policies-set-iam-policy.md'
    - 'Regions Autoscaling Policies Test Iam Permissions': 'projects_regions-autoscaling-policies-test-iam-permissions.md'
    - 'Regions Autoscaling Policies Update': 'projects_regions-autoscaling-policies-update.md'
    - 'Regions Clusters Create': 'projects_regions-clusters-create.md'
    - 'Regions Clusters Delete': 'projects_regions-clusters-delete.md'
    - 'Regions Clusters Diagnose': 'projects_regions-clusters-diagnose.md'
    - 'Regions Clusters Get': 'projects_regions-clusters-get.md'
    - 'Regions Clusters Get Iam Policy': 'projects_regions-clusters-get-iam-policy.md'
    - 'Regions Clusters Inject Credentials': 'projects_regions-clusters-inject-credentials.md'
    - 'Regions Clusters List': 'projects_regions-clusters-list.md'
    - 'Regions Clusters Node Groups Create': 'projects_regions-clusters-node-groups-create.md'
    - 'Regions Clusters Node Groups Get': 'projects_regions-clusters-node-groups-get.md'
    - 'Regions Clusters Node Groups Repair': 'projects_regions-clusters-node-groups-repair.md'
    - 'Regions Clusters Node Groups Resize': 'projects_regions-clusters-node-groups-resize.md'
    - 'Regions Clusters Patch': 'projects_regions-clusters-patch.md'
    - 'Regions Clusters Repair': 'projects_regions-clusters-repair.md'
    - 'Regions Clusters Set Iam Policy': 'projects_regions-clusters-set-iam-policy.md'
    - 'Regions Clusters Start': 'projects_regions-clusters-start.md'
    - 'Regions Clusters Stop': 'projects_regions-clusters-stop.md'
    - 'Regions Clusters Test Iam Permissions': 'projects_regions-clusters-test-iam-permissions.md'
    - 'Regions Jobs Cancel': 'projects_regions-jobs-cancel.md'
    - 'Regions Jobs Delete': 'projects_regions-jobs-delete.md'
    - 'Regions Jobs Get': 'projects_regions-jobs-get.md'
    - 'Regions Jobs Get Iam Policy': 'projects_regions-jobs-get-iam-policy.md'
    - 'Regions Jobs List': 'projects_regions-jobs-list.md'
    - 'Regions Jobs Patch': 'projects_regions-jobs-patch.md'
    - 'Regions Jobs Set Iam Policy': 'projects_regions-jobs-set-iam-policy.md'
    - 'Regions Jobs Submit': 'projects_regions-jobs-submit.md'
    - 'Regions Jobs Submit As Operation': 'projects_regions-jobs-submit-as-operation.md'
    - 'Regions Jobs Test Iam Permissions': 'projects_regions-jobs-test-iam-permissions.md'
    - 'Regions Operations Cancel': 'projects_regions-operations-cancel.md'
    - 'Regions Operations Delete': 'projects_regions-operations-delete.md'
    - 'Regions Operations Get': 'projects_regions-operations-get.md'
    - 'Regions Operations Get Iam Policy': 'projects_regions-operations-get-iam-policy.md'
    - 'Regions Operations List': 'projects_regions-operations-list.md'
    - 'Regions Operations Set Iam Policy': 'projects_regions-operations-set-iam-policy.md'
    - 'Regions Operations Test Iam Permissions': 'projects_regions-operations-test-iam-permissions.md'
    - 'Regions Workflow Templates Create': 'projects_regions-workflow-templates-create.md'
    - 'Regions Workflow Templates Delete': 'projects_regions-workflow-templates-delete.md'
    - 'Regions Workflow Templates Get': 'projects_regions-workflow-templates-get.md'
    - 'Regions Workflow Templates Get Iam Policy': 'projects_regions-workflow-templates-get-iam-policy.md'
    - 'Regions Workflow Templates Instantiate': 'projects_regions-workflow-templates-instantiate.md'
    - 'Regions Workflow Templates Instantiate Inline': 'projects_regions-workflow-templates-instantiate-inline.md'
    - 'Regions Workflow Templates List': 'projects_regions-workflow-templates-list.md'
    - 'Regions Workflow Templates Set Iam Policy': 'projects_regions-workflow-templates-set-iam-policy.md'
    - 'Regions Workflow Templates Test Iam Permissions': 'projects_regions-workflow-templates-test-iam-permissions.md'
    - 'Regions Workflow Templates Update': 'projects_regions-workflow-templates-update.md'

theme: readthedocs

copyright: Copyright &copy; 2015â€“2024, `Sebastian Thiel`
