site_name: Dataproc v1.0.7+20181005
site_url: http://byron.github.io/google-apis-rs/google-dataproc1-cli
site_description: A complete library to interact with Dataproc (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/dataproc1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_locations-workflow-templates-create.md', 'Projects', 'Locations Workflow Templates Create']
- ['projects_locations-workflow-templates-delete.md', 'Projects', 'Locations Workflow Templates Delete']
- ['projects_locations-workflow-templates-get.md', 'Projects', 'Locations Workflow Templates Get']
- ['projects_locations-workflow-templates-get-iam-policy.md', 'Projects', 'Locations Workflow Templates Get Iam Policy']
- ['projects_locations-workflow-templates-instantiate.md', 'Projects', 'Locations Workflow Templates Instantiate']
- ['projects_locations-workflow-templates-instantiate-inline.md', 'Projects', 'Locations Workflow Templates Instantiate Inline']
- ['projects_locations-workflow-templates-list.md', 'Projects', 'Locations Workflow Templates List']
- ['projects_locations-workflow-templates-set-iam-policy.md', 'Projects', 'Locations Workflow Templates Set Iam Policy']
- ['projects_locations-workflow-templates-test-iam-permissions.md', 'Projects', 'Locations Workflow Templates Test Iam Permissions']
- ['projects_locations-workflow-templates-update.md', 'Projects', 'Locations Workflow Templates Update']
- ['projects_regions-clusters-create.md', 'Projects', 'Regions Clusters Create']
- ['projects_regions-clusters-delete.md', 'Projects', 'Regions Clusters Delete']
- ['projects_regions-clusters-diagnose.md', 'Projects', 'Regions Clusters Diagnose']
- ['projects_regions-clusters-get.md', 'Projects', 'Regions Clusters Get']
- ['projects_regions-clusters-get-iam-policy.md', 'Projects', 'Regions Clusters Get Iam Policy']
- ['projects_regions-clusters-list.md', 'Projects', 'Regions Clusters List']
- ['projects_regions-clusters-patch.md', 'Projects', 'Regions Clusters Patch']
- ['projects_regions-clusters-set-iam-policy.md', 'Projects', 'Regions Clusters Set Iam Policy']
- ['projects_regions-clusters-test-iam-permissions.md', 'Projects', 'Regions Clusters Test Iam Permissions']
- ['projects_regions-jobs-cancel.md', 'Projects', 'Regions Jobs Cancel']
- ['projects_regions-jobs-delete.md', 'Projects', 'Regions Jobs Delete']
- ['projects_regions-jobs-get.md', 'Projects', 'Regions Jobs Get']
- ['projects_regions-jobs-get-iam-policy.md', 'Projects', 'Regions Jobs Get Iam Policy']
- ['projects_regions-jobs-list.md', 'Projects', 'Regions Jobs List']
- ['projects_regions-jobs-patch.md', 'Projects', 'Regions Jobs Patch']
- ['projects_regions-jobs-set-iam-policy.md', 'Projects', 'Regions Jobs Set Iam Policy']
- ['projects_regions-jobs-submit.md', 'Projects', 'Regions Jobs Submit']
- ['projects_regions-jobs-test-iam-permissions.md', 'Projects', 'Regions Jobs Test Iam Permissions']
- ['projects_regions-operations-cancel.md', 'Projects', 'Regions Operations Cancel']
- ['projects_regions-operations-delete.md', 'Projects', 'Regions Operations Delete']
- ['projects_regions-operations-get.md', 'Projects', 'Regions Operations Get']
- ['projects_regions-operations-get-iam-policy.md', 'Projects', 'Regions Operations Get Iam Policy']
- ['projects_regions-operations-list.md', 'Projects', 'Regions Operations List']
- ['projects_regions-operations-set-iam-policy.md', 'Projects', 'Regions Operations Set Iam Policy']
- ['projects_regions-operations-test-iam-permissions.md', 'Projects', 'Regions Operations Test Iam Permissions']
- ['projects_regions-workflow-templates-create.md', 'Projects', 'Regions Workflow Templates Create']
- ['projects_regions-workflow-templates-delete.md', 'Projects', 'Regions Workflow Templates Delete']
- ['projects_regions-workflow-templates-get.md', 'Projects', 'Regions Workflow Templates Get']
- ['projects_regions-workflow-templates-get-iam-policy.md', 'Projects', 'Regions Workflow Templates Get Iam Policy']
- ['projects_regions-workflow-templates-instantiate.md', 'Projects', 'Regions Workflow Templates Instantiate']
- ['projects_regions-workflow-templates-instantiate-inline.md', 'Projects', 'Regions Workflow Templates Instantiate Inline']
- ['projects_regions-workflow-templates-list.md', 'Projects', 'Regions Workflow Templates List']
- ['projects_regions-workflow-templates-set-iam-policy.md', 'Projects', 'Regions Workflow Templates Set Iam Policy']
- ['projects_regions-workflow-templates-test-iam-permissions.md', 'Projects', 'Regions Workflow Templates Test Iam Permissions']
- ['projects_regions-workflow-templates-update.md', 'Projects', 'Regions Workflow Templates Update']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

