site_name: Chrome Policy v2.0.3+20210329
site_url: http://byron.github.io/google-apis-rs/google-chromepolicy1-cli
site_description: A complete library to interact with Chrome Policy (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/chromepolicy1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['customers_policies-orgunits-batch-inherit.md', 'Customers', 'Policies Orgunits Batch Inherit']
- ['customers_policies-orgunits-batch-modify.md', 'Customers', 'Policies Orgunits Batch Modify']
- ['customers_policies-resolve.md', 'Customers', 'Policies Resolve']
- ['customers_policy-schemas-get.md', 'Customers', 'Policy Schemas Get']
- ['customers_policy-schemas-list.md', 'Customers', 'Policy Schemas List']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

