site_name: Cloud Machine Learning Engine v3.0.0+20220212
site_url: http://byron.github.io/google-apis-rs/google-ml1-cli
site_description: A complete library to interact with Cloud Machine Learning Engine (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/ml1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_explain.md', 'Projects', 'Explain']
- ['projects_get-config.md', 'Projects', 'Get Config']
- ['projects_jobs-cancel.md', 'Projects', 'Jobs Cancel']
- ['projects_jobs-create.md', 'Projects', 'Jobs Create']
- ['projects_jobs-get.md', 'Projects', 'Jobs Get']
- ['projects_jobs-get-iam-policy.md', 'Projects', 'Jobs Get Iam Policy']
- ['projects_jobs-list.md', 'Projects', 'Jobs List']
- ['projects_jobs-patch.md', 'Projects', 'Jobs Patch']
- ['projects_jobs-set-iam-policy.md', 'Projects', 'Jobs Set Iam Policy']
- ['projects_jobs-test-iam-permissions.md', 'Projects', 'Jobs Test Iam Permissions']
- ['projects_locations-get.md', 'Projects', 'Locations Get']
- ['projects_locations-list.md', 'Projects', 'Locations List']
- ['projects_locations-operations-cancel.md', 'Projects', 'Locations Operations Cancel']
- ['projects_locations-operations-get.md', 'Projects', 'Locations Operations Get']
- ['projects_locations-studies-create.md', 'Projects', 'Locations Studies Create']
- ['projects_locations-studies-delete.md', 'Projects', 'Locations Studies Delete']
- ['projects_locations-studies-get.md', 'Projects', 'Locations Studies Get']
- ['projects_locations-studies-list.md', 'Projects', 'Locations Studies List']
- ['projects_locations-studies-trials-add-measurement.md', 'Projects', 'Locations Studies Trials Add Measurement']
- ['projects_locations-studies-trials-check-early-stopping-state.md', 'Projects', 'Locations Studies Trials Check Early Stopping State']
- ['projects_locations-studies-trials-complete.md', 'Projects', 'Locations Studies Trials Complete']
- ['projects_locations-studies-trials-create.md', 'Projects', 'Locations Studies Trials Create']
- ['projects_locations-studies-trials-delete.md', 'Projects', 'Locations Studies Trials Delete']
- ['projects_locations-studies-trials-get.md', 'Projects', 'Locations Studies Trials Get']
- ['projects_locations-studies-trials-list.md', 'Projects', 'Locations Studies Trials List']
- ['projects_locations-studies-trials-list-optimal-trials.md', 'Projects', 'Locations Studies Trials List Optimal Trials']
- ['projects_locations-studies-trials-stop.md', 'Projects', 'Locations Studies Trials Stop']
- ['projects_locations-studies-trials-suggest.md', 'Projects', 'Locations Studies Trials Suggest']
- ['projects_models-create.md', 'Projects', 'Models Create']
- ['projects_models-delete.md', 'Projects', 'Models Delete']
- ['projects_models-get.md', 'Projects', 'Models Get']
- ['projects_models-get-iam-policy.md', 'Projects', 'Models Get Iam Policy']
- ['projects_models-list.md', 'Projects', 'Models List']
- ['projects_models-patch.md', 'Projects', 'Models Patch']
- ['projects_models-set-iam-policy.md', 'Projects', 'Models Set Iam Policy']
- ['projects_models-test-iam-permissions.md', 'Projects', 'Models Test Iam Permissions']
- ['projects_models-versions-create.md', 'Projects', 'Models Versions Create']
- ['projects_models-versions-delete.md', 'Projects', 'Models Versions Delete']
- ['projects_models-versions-get.md', 'Projects', 'Models Versions Get']
- ['projects_models-versions-list.md', 'Projects', 'Models Versions List']
- ['projects_models-versions-patch.md', 'Projects', 'Models Versions Patch']
- ['projects_models-versions-set-default.md', 'Projects', 'Models Versions Set Default']
- ['projects_operations-cancel.md', 'Projects', 'Operations Cancel']
- ['projects_operations-get.md', 'Projects', 'Operations Get']
- ['projects_operations-list.md', 'Projects', 'Operations List']
- ['projects_predict.md', 'Projects', 'Predict']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

