site_name: appsactivity v1.0.7+20171207
site_url: http://byron.github.io/google-apis-rs/google-appsactivity1-cli
site_description: A complete library to interact with appsactivity (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/appsactivity1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['activities_list.md', 'Activities', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

