site_name: storagetransfer v1.0.7+20181008
site_url: http://byron.github.io/google-apis-rs/google-storagetransfer1-cli
site_description: A complete library to interact with storagetransfer (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/storagetransfer1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['google-service-accounts_get.md', 'Google Service Accounts', 'Get']
- ['transfer-jobs_create.md', 'Transfer Jobs', 'Create']
- ['transfer-jobs_get.md', 'Transfer Jobs', 'Get']
- ['transfer-jobs_list.md', 'Transfer Jobs', 'List']
- ['transfer-jobs_patch.md', 'Transfer Jobs', 'Patch']
- ['transfer-operations_cancel.md', 'Transfer Operations', 'Cancel']
- ['transfer-operations_delete.md', 'Transfer Operations', 'Delete']
- ['transfer-operations_get.md', 'Transfer Operations', 'Get']
- ['transfer-operations_list.md', 'Transfer Operations', 'List']
- ['transfer-operations_pause.md', 'Transfer Operations', 'Pause']
- ['transfer-operations_resume.md', 'Transfer Operations', 'Resume']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

