site_name: YouTube Analytics v1.0.7+20181010
site_url: http://byron.github.io/google-apis-rs/google-youtubeanalytics2-cli
site_description: A complete library to interact with YouTube Analytics (protocol v2)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/youtubeanalytics2-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['group-items_delete.md', 'Group Items', 'Delete']
- ['group-items_insert.md', 'Group Items', 'Insert']
- ['group-items_list.md', 'Group Items', 'List']
- ['groups_delete.md', 'Groups', 'Delete']
- ['groups_insert.md', 'Groups', 'Insert']
- ['groups_list.md', 'Groups', 'List']
- ['groups_update.md', 'Groups', 'Update']
- ['reports_query.md', 'Reports', 'Query']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

