site_name: autoscaler v1.0.8+20150629
site_url: http://byron.github.io/google-apis-rs/google-autoscaler1_beta2-cli
site_description: A complete library to interact with autoscaler (protocol v1beta2)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/autoscaler1_beta2-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['autoscalers_delete.md', 'Autoscalers', 'Delete']
- ['autoscalers_get.md', 'Autoscalers', 'Get']
- ['autoscalers_insert.md', 'Autoscalers', 'Insert']
- ['autoscalers_list.md', 'Autoscalers', 'List']
- ['autoscalers_patch.md', 'Autoscalers', 'Patch']
- ['autoscalers_update.md', 'Autoscalers', 'Update']
- ['zone-operations_delete.md', 'Zone Operations', 'Delete']
- ['zone-operations_get.md', 'Zone Operations', 'Get']
- ['zone-operations_list.md', 'Zone Operations', 'List']
- ['zones_list.md', 'Zones', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

