site_name: Surveys v1.0.7+20180508
site_url: http://byron.github.io/google-apis-rs/google-surveys2-cli
site_description: A complete library to interact with Surveys (protocol v2)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/surveys2-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['results_get.md', 'Results', 'Get']
- ['surveys_delete.md', 'Surveys', 'Delete']
- ['surveys_get.md', 'Surveys', 'Get']
- ['surveys_insert.md', 'Surveys', 'Insert']
- ['surveys_list.md', 'Surveys', 'List']
- ['surveys_start.md', 'Surveys', 'Start']
- ['surveys_stop.md', 'Surveys', 'Stop']
- ['surveys_update.md', 'Surveys', 'Update']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

