site_name: Deployment Manager v5.0.3+20221208
site_url: http://byron.github.io/google-apis-rs/google-deploymentmanager2-cli
site_description: A complete library to interact with Deployment Manager (protocol v2)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/deploymentmanager2-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Deployments':
    - 'Cancel Preview': 'deployments_cancel-preview.md'
    - 'Delete': 'deployments_delete.md'
    - 'Get': 'deployments_get.md'
    - 'Get Iam Policy': 'deployments_get-iam-policy.md'
    - 'Insert': 'deployments_insert.md'
    - 'List': 'deployments_list.md'
    - 'Patch': 'deployments_patch.md'
    - 'Set Iam Policy': 'deployments_set-iam-policy.md'
    - 'Stop': 'deployments_stop.md'
    - 'Test Iam Permissions': 'deployments_test-iam-permissions.md'
    - 'Update': 'deployments_update.md'
- 'Manifests':
    - 'Get': 'manifests_get.md'
    - 'List': 'manifests_list.md'
- 'Operations':
    - 'Get': 'operations_get.md'
    - 'List': 'operations_list.md'
- 'Resources':
    - 'Get': 'resources_get.md'
    - 'List': 'resources_list.md'
- 'Types':
    - 'List': 'types_list.md'

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

