site_name: urlshortener v3.1.0+20150519
site_url: http://byron.github.io/google-apis-rs/google-urlshortener1-cli
site_description: A complete library to interact with urlshortener (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/urlshortener1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['url_get.md', 'Url', 'Get']
- ['url_insert.md', 'Url', 'Insert']
- ['url_list.md', 'Url', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

