site_name: Firebasestorage v2.0.4+20210329
site_url: http://byron.github.io/google-apis-rs/google-firebasestorage1_beta-cli
site_description: A complete library to interact with Firebasestorage (protocol v1beta)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/firebasestorage1_beta-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_buckets-add-firebase.md', 'Projects', 'Buckets Add Firebase']
- ['projects_buckets-get.md', 'Projects', 'Buckets Get']
- ['projects_buckets-list.md', 'Projects', 'Buckets List']
- ['projects_buckets-remove-firebase.md', 'Projects', 'Buckets Remove Firebase']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

