site_name: Firebasestorage v5.0.3+20230106
site_url: http://byron.github.io/google-apis-rs/google-firebasestorage1_beta-cli
site_description: A complete library to interact with Firebasestorage (protocol v1beta)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/firebasestorage1_beta-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Projects':
    - 'Buckets Add Firebase': 'projects_buckets-add-firebase.md'
    - 'Buckets Get': 'projects_buckets-get.md'
    - 'Buckets List': 'projects_buckets-list.md'
    - 'Buckets Remove Firebase': 'projects_buckets-remove-firebase.md'

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

