site_name: Search Console v1.0.9+20190629
site_url: http://byron.github.io/google-apis-rs/google-searchconsole1-cli
site_description: A complete library to interact with Search Console (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/searchconsole1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['url-testing-tools_mobile-friendly-test-run.md', 'Url Testing Tools', 'Mobile Friendly Test Run']

theme: readthedocs

copyright: Copyright &copy; 2015-2019, `Sebastian Thiel`

