site_name: Search Console v3.1.0+20220305
site_url: http://byron.github.io/google-apis-rs/google-searchconsole1-cli
site_description: A complete library to interact with Search Console (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/searchconsole1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['searchanalytics_query.md', 'Searchanalytics', 'Query']
- ['sitemaps_delete.md', 'Sitemaps', 'Delete']
- ['sitemaps_get.md', 'Sitemaps', 'Get']
- ['sitemaps_list.md', 'Sitemaps', 'List']
- ['sitemaps_submit.md', 'Sitemaps', 'Submit']
- ['sites_add.md', 'Sites', 'Add']
- ['sites_delete.md', 'Sites', 'Delete']
- ['sites_get.md', 'Sites', 'Get']
- ['sites_list.md', 'Sites', 'List']
- ['url-inspection_index-inspect.md', 'Url Inspection', 'Index Inspect']
- ['url-testing-tools_mobile-friendly-test-run.md', 'Url Testing Tools', 'Mobile Friendly Test Run']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

