site_name: Deployment Manager v3.0.0+20160201
site_url: http://byron.github.io/google-apis-rs/google-deploymentmanager2_beta2-cli
site_description: A complete library to interact with Deployment Manager (protocol v2beta2)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/deploymentmanager2_beta2-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['deployments_delete.md', 'Deployments', 'Delete']
- ['deployments_get.md', 'Deployments', 'Get']
- ['deployments_insert.md', 'Deployments', 'Insert']
- ['deployments_list.md', 'Deployments', 'List']
- ['deployments_patch.md', 'Deployments', 'Patch']
- ['deployments_update.md', 'Deployments', 'Update']
- ['manifests_get.md', 'Manifests', 'Get']
- ['manifests_list.md', 'Manifests', 'List']
- ['operations_get.md', 'Operations', 'Get']
- ['operations_list.md', 'Operations', 'List']
- ['resources_get.md', 'Resources', 'Get']
- ['resources_list.md', 'Resources', 'List']
- ['types_list.md', 'Types', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

