site_name: My Business Business Information v4.0.1+20220305
site_url: http://byron.github.io/google-apis-rs/google-mybusinessbusinessinformation1-cli
site_description: A complete library to interact with My Business Business Information (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/mybusinessbusinessinformation1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['accounts_locations-create.md', 'Accounts', 'Locations Create']
- ['accounts_locations-list.md', 'Accounts', 'Locations List']
- ['attributes_list.md', 'Attributes', 'List']
- ['categories_batch-get.md', 'Categories', 'Batch Get']
- ['categories_list.md', 'Categories', 'List']
- ['chains_get.md', 'Chains', 'Get']
- ['chains_search.md', 'Chains', 'Search']
- ['google-locations_search.md', 'Google Locations', 'Search']
- ['locations_associate.md', 'Locations', 'Associate']
- ['locations_attributes-get-google-updated.md', 'Locations', 'Attributes Get Google Updated']
- ['locations_clear-location-association.md', 'Locations', 'Clear Location Association']
- ['locations_delete.md', 'Locations', 'Delete']
- ['locations_get.md', 'Locations', 'Get']
- ['locations_get-attributes.md', 'Locations', 'Get Attributes']
- ['locations_get-google-updated.md', 'Locations', 'Get Google Updated']
- ['locations_patch.md', 'Locations', 'Patch']
- ['locations_update-attributes.md', 'Locations', 'Update Attributes']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

