site_name: SQL Admin v1.0.7+20180917
site_url: http://byron.github.io/google-apis-rs/google-sqladmin1_beta4-cli
site_description: A complete library to interact with SQL Admin (protocol v1beta4)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/sqladmin1_beta4-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['backup-runs_delete.md', 'Backup Runs', 'Delete']
- ['backup-runs_get.md', 'Backup Runs', 'Get']
- ['backup-runs_insert.md', 'Backup Runs', 'Insert']
- ['backup-runs_list.md', 'Backup Runs', 'List']
- ['databases_delete.md', 'Databases', 'Delete']
- ['databases_get.md', 'Databases', 'Get']
- ['databases_insert.md', 'Databases', 'Insert']
- ['databases_list.md', 'Databases', 'List']
- ['databases_patch.md', 'Databases', 'Patch']
- ['databases_update.md', 'Databases', 'Update']
- ['flags_list.md', 'Flags', 'List']
- ['instances_add-server-ca.md', 'Instances', 'Add Server Ca']
- ['instances_clone.md', 'Instances', 'Clone']
- ['instances_delete.md', 'Instances', 'Delete']
- ['instances_demote-master.md', 'Instances', 'Demote Master']
- ['instances_export.md', 'Instances', 'Export']
- ['instances_failover.md', 'Instances', 'Failover']
- ['instances_get.md', 'Instances', 'Get']
- ['instances_import.md', 'Instances', 'Import']
- ['instances_insert.md', 'Instances', 'Insert']
- ['instances_list.md', 'Instances', 'List']
- ['instances_list-server-cas.md', 'Instances', 'List Server Cas']
- ['instances_patch.md', 'Instances', 'Patch']
- ['instances_promote-replica.md', 'Instances', 'Promote Replica']
- ['instances_reset-ssl-config.md', 'Instances', 'Reset Ssl Config']
- ['instances_restart.md', 'Instances', 'Restart']
- ['instances_restore-backup.md', 'Instances', 'Restore Backup']
- ['instances_rotate-server-ca.md', 'Instances', 'Rotate Server Ca']
- ['instances_start-replica.md', 'Instances', 'Start Replica']
- ['instances_stop-replica.md', 'Instances', 'Stop Replica']
- ['instances_truncate-log.md', 'Instances', 'Truncate Log']
- ['instances_update.md', 'Instances', 'Update']
- ['operations_get.md', 'Operations', 'Get']
- ['operations_list.md', 'Operations', 'List']
- ['ssl-certs_create-ephemeral.md', 'Ssl Certs', 'Create Ephemeral']
- ['ssl-certs_delete.md', 'Ssl Certs', 'Delete']
- ['ssl-certs_get.md', 'Ssl Certs', 'Get']
- ['ssl-certs_insert.md', 'Ssl Certs', 'Insert']
- ['ssl-certs_list.md', 'Ssl Certs', 'List']
- ['tiers_list.md', 'Tiers', 'List']
- ['users_delete.md', 'Users', 'Delete']
- ['users_insert.md', 'Users', 'Insert']
- ['users_list.md', 'Users', 'List']
- ['users_update.md', 'Users', 'Update']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

