site_name: Cloud Security Token v2.0.5+20210326
site_url: http://byron.github.io/google-apis-rs/google-sts1-cli
site_description: A complete library to interact with Cloud Security Token (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/sts1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['methods_token.md', 'Methods', 'Token']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

