site_name: Firestore v3.0.0+20220221
site_url: http://byron.github.io/google-apis-rs/google-firestore1-cli
site_description: A complete library to interact with Firestore (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/firestore1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_databases-collection-groups-fields-get.md', 'Projects', 'Databases Collection Groups Fields Get']
- ['projects_databases-collection-groups-fields-list.md', 'Projects', 'Databases Collection Groups Fields List']
- ['projects_databases-collection-groups-fields-patch.md', 'Projects', 'Databases Collection Groups Fields Patch']
- ['projects_databases-collection-groups-indexes-create.md', 'Projects', 'Databases Collection Groups Indexes Create']
- ['projects_databases-collection-groups-indexes-delete.md', 'Projects', 'Databases Collection Groups Indexes Delete']
- ['projects_databases-collection-groups-indexes-get.md', 'Projects', 'Databases Collection Groups Indexes Get']
- ['projects_databases-collection-groups-indexes-list.md', 'Projects', 'Databases Collection Groups Indexes List']
- ['projects_databases-documents-batch-get.md', 'Projects', 'Databases Documents Batch Get']
- ['projects_databases-documents-batch-write.md', 'Projects', 'Databases Documents Batch Write']
- ['projects_databases-documents-begin-transaction.md', 'Projects', 'Databases Documents Begin Transaction']
- ['projects_databases-documents-commit.md', 'Projects', 'Databases Documents Commit']
- ['projects_databases-documents-create-document.md', 'Projects', 'Databases Documents Create Document']
- ['projects_databases-documents-delete.md', 'Projects', 'Databases Documents Delete']
- ['projects_databases-documents-get.md', 'Projects', 'Databases Documents Get']
- ['projects_databases-documents-list.md', 'Projects', 'Databases Documents List']
- ['projects_databases-documents-list-collection-ids.md', 'Projects', 'Databases Documents List Collection Ids']
- ['projects_databases-documents-listen.md', 'Projects', 'Databases Documents Listen']
- ['projects_databases-documents-partition-query.md', 'Projects', 'Databases Documents Partition Query']
- ['projects_databases-documents-patch.md', 'Projects', 'Databases Documents Patch']
- ['projects_databases-documents-rollback.md', 'Projects', 'Databases Documents Rollback']
- ['projects_databases-documents-run-query.md', 'Projects', 'Databases Documents Run Query']
- ['projects_databases-documents-write.md', 'Projects', 'Databases Documents Write']
- ['projects_databases-export-documents.md', 'Projects', 'Databases Export Documents']
- ['projects_databases-get.md', 'Projects', 'Databases Get']
- ['projects_databases-import-documents.md', 'Projects', 'Databases Import Documents']
- ['projects_databases-list.md', 'Projects', 'Databases List']
- ['projects_databases-operations-cancel.md', 'Projects', 'Databases Operations Cancel']
- ['projects_databases-operations-delete.md', 'Projects', 'Databases Operations Delete']
- ['projects_databases-operations-get.md', 'Projects', 'Databases Operations Get']
- ['projects_databases-operations-list.md', 'Projects', 'Databases Operations List']
- ['projects_databases-patch.md', 'Projects', 'Databases Patch']
- ['projects_locations-get.md', 'Projects', 'Locations Get']
- ['projects_locations-list.md', 'Projects', 'Locations List']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

