site_name: Cloud Resource Manager v1.0.0+20160617
site_url: http://byron.github.io/google-apis-rs/google-cloudresourcemanager1_beta1-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/cloudresourcemanager1_beta1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['organizations_get.md', 'Organizations', 'Get']
- ['organizations_get-iam-policy.md', 'Organizations', 'Get Iam Policy']
- ['organizations_list.md', 'Organizations', 'List']
- ['organizations_set-iam-policy.md', 'Organizations', 'Set Iam Policy']
- ['organizations_test-iam-permissions.md', 'Organizations', 'Test Iam Permissions']
- ['organizations_update.md', 'Organizations', 'Update']
- ['projects_create.md', 'Projects', 'Create']
- ['projects_delete.md', 'Projects', 'Delete']
- ['projects_get.md', 'Projects', 'Get']
- ['projects_get-ancestry.md', 'Projects', 'Get Ancestry']
- ['projects_get-iam-policy.md', 'Projects', 'Get Iam Policy']
- ['projects_list.md', 'Projects', 'List']
- ['projects_set-iam-policy.md', 'Projects', 'Set Iam Policy']
- ['projects_test-iam-permissions.md', 'Projects', 'Test Iam Permissions']
- ['projects_undelete.md', 'Projects', 'Undelete']
- ['projects_update.md', 'Projects', 'Update']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

