site_name: Cloud Functions v1.0.13+20200401
site_url: http://byron.github.io/google-apis-rs/google-cloudfunctions1-cli
site_description: A complete library to interact with Cloud Functions (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/cloudfunctions1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['operations_get.md', 'Operations', 'Get']
- ['operations_list.md', 'Operations', 'List']
- ['projects_locations-functions-call.md', 'Projects', 'Locations Functions Call']
- ['projects_locations-functions-create.md', 'Projects', 'Locations Functions Create']
- ['projects_locations-functions-delete.md', 'Projects', 'Locations Functions Delete']
- ['projects_locations-functions-generate-download-url.md', 'Projects', 'Locations Functions Generate Download Url']
- ['projects_locations-functions-generate-upload-url.md', 'Projects', 'Locations Functions Generate Upload Url']
- ['projects_locations-functions-get.md', 'Projects', 'Locations Functions Get']
- ['projects_locations-functions-get-iam-policy.md', 'Projects', 'Locations Functions Get Iam Policy']
- ['projects_locations-functions-list.md', 'Projects', 'Locations Functions List']
- ['projects_locations-functions-patch.md', 'Projects', 'Locations Functions Patch']
- ['projects_locations-functions-set-iam-policy.md', 'Projects', 'Locations Functions Set Iam Policy']
- ['projects_locations-functions-test-iam-permissions.md', 'Projects', 'Locations Functions Test Iam Permissions']
- ['projects_locations-list.md', 'Projects', 'Locations List']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

