site_name: Cloudchannel v2.0.4+20210326
site_url: http://byron.github.io/google-apis-rs/google-cloudchannel1-cli
site_description: A complete library to interact with Cloudchannel (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/cloudchannel1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['accounts_channel-partner-links-create.md', 'Accounts', 'Channel Partner Links Create']
- ['accounts_channel-partner-links-customers-create.md', 'Accounts', 'Channel Partner Links Customers Create']
- ['accounts_channel-partner-links-customers-delete.md', 'Accounts', 'Channel Partner Links Customers Delete']
- ['accounts_channel-partner-links-customers-get.md', 'Accounts', 'Channel Partner Links Customers Get']
- ['accounts_channel-partner-links-customers-list.md', 'Accounts', 'Channel Partner Links Customers List']
- ['accounts_channel-partner-links-customers-patch.md', 'Accounts', 'Channel Partner Links Customers Patch']
- ['accounts_channel-partner-links-get.md', 'Accounts', 'Channel Partner Links Get']
- ['accounts_channel-partner-links-list.md', 'Accounts', 'Channel Partner Links List']
- ['accounts_channel-partner-links-patch.md', 'Accounts', 'Channel Partner Links Patch']
- ['accounts_check-cloud-identity-accounts-exist.md', 'Accounts', 'Check Cloud Identity Accounts Exist']
- ['accounts_customers-create.md', 'Accounts', 'Customers Create']
- ['accounts_customers-delete.md', 'Accounts', 'Customers Delete']
- ['accounts_customers-entitlements-activate.md', 'Accounts', 'Customers Entitlements Activate']
- ['accounts_customers-entitlements-cancel.md', 'Accounts', 'Customers Entitlements Cancel']
- ['accounts_customers-entitlements-change-offer.md', 'Accounts', 'Customers Entitlements Change Offer']
- ['accounts_customers-entitlements-change-parameters.md', 'Accounts', 'Customers Entitlements Change Parameters']
- ['accounts_customers-entitlements-change-renewal-settings.md', 'Accounts', 'Customers Entitlements Change Renewal Settings']
- ['accounts_customers-entitlements-create.md', 'Accounts', 'Customers Entitlements Create']
- ['accounts_customers-entitlements-get.md', 'Accounts', 'Customers Entitlements Get']
- ['accounts_customers-entitlements-list.md', 'Accounts', 'Customers Entitlements List']
- ['accounts_customers-entitlements-start-paid-service.md', 'Accounts', 'Customers Entitlements Start Paid Service']
- ['accounts_customers-entitlements-suspend.md', 'Accounts', 'Customers Entitlements Suspend']
- ['accounts_customers-get.md', 'Accounts', 'Customers Get']
- ['accounts_customers-list.md', 'Accounts', 'Customers List']
- ['accounts_customers-list-purchasable-offers.md', 'Accounts', 'Customers List Purchasable Offers']
- ['accounts_customers-list-purchasable-skus.md', 'Accounts', 'Customers List Purchasable Skus']
- ['accounts_customers-patch.md', 'Accounts', 'Customers Patch']
- ['accounts_customers-provision-cloud-identity.md', 'Accounts', 'Customers Provision Cloud Identity']
- ['accounts_customers-transfer-entitlements.md', 'Accounts', 'Customers Transfer Entitlements']
- ['accounts_customers-transfer-entitlements-to-google.md', 'Accounts', 'Customers Transfer Entitlements To Google']
- ['accounts_list-subscribers.md', 'Accounts', 'List Subscribers']
- ['accounts_list-transferable-offers.md', 'Accounts', 'List Transferable Offers']
- ['accounts_list-transferable-skus.md', 'Accounts', 'List Transferable Skus']
- ['accounts_offers-list.md', 'Accounts', 'Offers List']
- ['accounts_register.md', 'Accounts', 'Register']
- ['accounts_unregister.md', 'Accounts', 'Unregister']
- ['operations_cancel.md', 'Operations', 'Cancel']
- ['operations_delete.md', 'Operations', 'Delete']
- ['operations_get.md', 'Operations', 'Get']
- ['operations_list.md', 'Operations', 'List']
- ['products_list.md', 'Products', 'List']
- ['products_skus-list.md', 'Products', 'Skus List']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

