site_name: PubsubLite v2.0.8+20210322
site_url: http://byron.github.io/google-apis-rs/google-pubsublite1-cli
site_description: A complete library to interact with PubsubLite (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/pubsublite1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['admin_projects-locations-subscriptions-create.md', 'Admin', 'Projects Locations Subscriptions Create']
- ['admin_projects-locations-subscriptions-delete.md', 'Admin', 'Projects Locations Subscriptions Delete']
- ['admin_projects-locations-subscriptions-get.md', 'Admin', 'Projects Locations Subscriptions Get']
- ['admin_projects-locations-subscriptions-list.md', 'Admin', 'Projects Locations Subscriptions List']
- ['admin_projects-locations-subscriptions-patch.md', 'Admin', 'Projects Locations Subscriptions Patch']
- ['admin_projects-locations-topics-create.md', 'Admin', 'Projects Locations Topics Create']
- ['admin_projects-locations-topics-delete.md', 'Admin', 'Projects Locations Topics Delete']
- ['admin_projects-locations-topics-get.md', 'Admin', 'Projects Locations Topics Get']
- ['admin_projects-locations-topics-get-partitions.md', 'Admin', 'Projects Locations Topics Get Partitions']
- ['admin_projects-locations-topics-list.md', 'Admin', 'Projects Locations Topics List']
- ['admin_projects-locations-topics-patch.md', 'Admin', 'Projects Locations Topics Patch']
- ['admin_projects-locations-topics-subscriptions-list.md', 'Admin', 'Projects Locations Topics Subscriptions List']
- ['cursor_projects-locations-subscriptions-cursors-list.md', 'Cursor', 'Projects Locations Subscriptions Cursors List']
- ['topic-stats_projects-locations-topics-compute-head-cursor.md', 'Topic Stats', 'Projects Locations Topics Compute Head Cursor']
- ['topic-stats_projects-locations-topics-compute-message-stats.md', 'Topic Stats', 'Projects Locations Topics Compute Message Stats']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

