site_name: classroom v1.0.10+20190701
site_url: http://byron.github.io/google-apis-rs/google-classroom1-cli
site_description: A complete library to interact with classroom (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/classroom1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['courses_aliases-create.md', 'Courses', 'Aliases Create']
- ['courses_aliases-delete.md', 'Courses', 'Aliases Delete']
- ['courses_aliases-list.md', 'Courses', 'Aliases List']
- ['courses_announcements-create.md', 'Courses', 'Announcements Create']
- ['courses_announcements-delete.md', 'Courses', 'Announcements Delete']
- ['courses_announcements-get.md', 'Courses', 'Announcements Get']
- ['courses_announcements-list.md', 'Courses', 'Announcements List']
- ['courses_announcements-modify-assignees.md', 'Courses', 'Announcements Modify Assignees']
- ['courses_announcements-patch.md', 'Courses', 'Announcements Patch']
- ['courses_course-work-create.md', 'Courses', 'Course Work Create']
- ['courses_course-work-delete.md', 'Courses', 'Course Work Delete']
- ['courses_course-work-get.md', 'Courses', 'Course Work Get']
- ['courses_course-work-list.md', 'Courses', 'Course Work List']
- ['courses_course-work-modify-assignees.md', 'Courses', 'Course Work Modify Assignees']
- ['courses_course-work-patch.md', 'Courses', 'Course Work Patch']
- ['courses_course-work-student-submissions-get.md', 'Courses', 'Course Work Student Submissions Get']
- ['courses_course-work-student-submissions-list.md', 'Courses', 'Course Work Student Submissions List']
- ['courses_course-work-student-submissions-modify-attachments.md', 'Courses', 'Course Work Student Submissions Modify Attachments']
- ['courses_course-work-student-submissions-patch.md', 'Courses', 'Course Work Student Submissions Patch']
- ['courses_course-work-student-submissions-reclaim.md', 'Courses', 'Course Work Student Submissions Reclaim']
- ['courses_course-work-student-submissions-return.md', 'Courses', 'Course Work Student Submissions Return']
- ['courses_course-work-student-submissions-turn-in.md', 'Courses', 'Course Work Student Submissions Turn In']
- ['courses_create.md', 'Courses', 'Create']
- ['courses_delete.md', 'Courses', 'Delete']
- ['courses_get.md', 'Courses', 'Get']
- ['courses_list.md', 'Courses', 'List']
- ['courses_patch.md', 'Courses', 'Patch']
- ['courses_students-create.md', 'Courses', 'Students Create']
- ['courses_students-delete.md', 'Courses', 'Students Delete']
- ['courses_students-get.md', 'Courses', 'Students Get']
- ['courses_students-list.md', 'Courses', 'Students List']
- ['courses_teachers-create.md', 'Courses', 'Teachers Create']
- ['courses_teachers-delete.md', 'Courses', 'Teachers Delete']
- ['courses_teachers-get.md', 'Courses', 'Teachers Get']
- ['courses_teachers-list.md', 'Courses', 'Teachers List']
- ['courses_topics-create.md', 'Courses', 'Topics Create']
- ['courses_topics-delete.md', 'Courses', 'Topics Delete']
- ['courses_topics-get.md', 'Courses', 'Topics Get']
- ['courses_topics-list.md', 'Courses', 'Topics List']
- ['courses_topics-patch.md', 'Courses', 'Topics Patch']
- ['courses_update.md', 'Courses', 'Update']
- ['invitations_accept.md', 'Invitations', 'Accept']
- ['invitations_create.md', 'Invitations', 'Create']
- ['invitations_delete.md', 'Invitations', 'Delete']
- ['invitations_get.md', 'Invitations', 'Get']
- ['invitations_list.md', 'Invitations', 'List']
- ['registrations_create.md', 'Registrations', 'Create']
- ['registrations_delete.md', 'Registrations', 'Delete']
- ['user-profiles_get.md', 'User Profiles', 'Get']
- ['user-profiles_guardian-invitations-create.md', 'User Profiles', 'Guardian Invitations Create']
- ['user-profiles_guardian-invitations-get.md', 'User Profiles', 'Guardian Invitations Get']
- ['user-profiles_guardian-invitations-list.md', 'User Profiles', 'Guardian Invitations List']
- ['user-profiles_guardian-invitations-patch.md', 'User Profiles', 'Guardian Invitations Patch']
- ['user-profiles_guardians-delete.md', 'User Profiles', 'Guardians Delete']
- ['user-profiles_guardians-get.md', 'User Profiles', 'Guardians Get']
- ['user-profiles_guardians-list.md', 'User Profiles', 'Guardians List']

theme: readthedocs

copyright: Copyright &copy; 2015-2019, `Sebastian Thiel`

