site_name: Clouderrorreporting v1.0.8+20181005
site_url: http://byron.github.io/google-apis-rs/google-clouderrorreporting1_beta1-cli
site_description: A complete library to interact with Clouderrorreporting (protocol v1beta1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/clouderrorreporting1_beta1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_delete-events.md', 'Projects', 'Delete Events']
- ['projects_events-list.md', 'Projects', 'Events List']
- ['projects_events-report.md', 'Projects', 'Events Report']
- ['projects_group-stats-list.md', 'Projects', 'Group Stats List']
- ['projects_groups-get.md', 'Projects', 'Groups Get']
- ['projects_groups-update.md', 'Projects', 'Groups Update']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

