site_name: Clouderrorreporting v7.0.0+20251205
site_url: http://byron.github.io/google-apis-rs/google-clouderrorreporting1_beta1-cli
site_description: A complete library to interact with Clouderrorreporting (protocol v1beta1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/clouderrorreporting1_beta1-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Projects':
    - 'Delete Events': 'projects_delete-events.md'
    - 'Events List': 'projects_events-list.md'
    - 'Events Report': 'projects_events-report.md'
    - 'Group Stats List': 'projects_group-stats-list.md'
    - 'Groups Get': 'projects_groups-get.md'
    - 'Groups Update': 'projects_groups-update.md'
    - 'Locations Delete Events': 'projects_locations-delete-events.md'
    - 'Locations Events List': 'projects_locations-events-list.md'
    - 'Locations Group Stats List': 'projects_locations-group-stats-list.md'
    - 'Locations Groups Get': 'projects_locations-groups-get.md'
    - 'Locations Groups Update': 'projects_locations-groups-update.md'

theme: readthedocs

copyright: Copyright &copy; 2015â€“2024, `Sebastian Thiel`
