site_name: Android Publisher v7.0.0+20251216
site_url: http://byron.github.io/google-apis-rs/google-androidpublisher3-cli
site_description: A complete library to interact with Android Publisher (protocol v3)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/androidpublisher3-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Applications':
    - 'Data Safety': 'applications_data-safety.md'
    - 'Device Tier Configs Create': 'applications_device-tier-configs-create.md'
    - 'Device Tier Configs Get': 'applications_device-tier-configs-get.md'
    - 'Device Tier Configs List': 'applications_device-tier-configs-list.md'
- 'Apprecovery':
    - 'Add Targeting': 'apprecovery_add-targeting.md'
    - 'Cancel': 'apprecovery_cancel.md'
    - 'Create': 'apprecovery_create.md'
    - 'Deploy': 'apprecovery_deploy.md'
    - 'List': 'apprecovery_list.md'
- 'Edits':
    - 'Apks Addexternallyhosted': 'edits_apks-addexternallyhosted.md'
    - 'Apks List': 'edits_apks-list.md'
    - 'Apks Upload': 'edits_apks-upload.md'
    - 'Bundles List': 'edits_bundles-list.md'
    - 'Bundles Upload': 'edits_bundles-upload.md'
    - 'Commit': 'edits_commit.md'
    - 'Countryavailability Get': 'edits_countryavailability-get.md'
    - 'Delete': 'edits_delete.md'
    - 'Deobfuscationfiles Upload': 'edits_deobfuscationfiles-upload.md'
    - 'Details Get': 'edits_details-get.md'
    - 'Details Patch': 'edits_details-patch.md'
    - 'Details Update': 'edits_details-update.md'
    - 'Expansionfiles Get': 'edits_expansionfiles-get.md'
    - 'Expansionfiles Patch': 'edits_expansionfiles-patch.md'
    - 'Expansionfiles Update': 'edits_expansionfiles-update.md'
    - 'Expansionfiles Upload': 'edits_expansionfiles-upload.md'
    - 'Get': 'edits_get.md'
    - 'Images Delete': 'edits_images-delete.md'
    - 'Images Deleteall': 'edits_images-deleteall.md'
    - 'Images List': 'edits_images-list.md'
    - 'Images Upload': 'edits_images-upload.md'
    - 'Insert': 'edits_insert.md'
    - 'Listings Delete': 'edits_listings-delete.md'
    - 'Listings Deleteall': 'edits_listings-deleteall.md'
    - 'Listings Get': 'edits_listings-get.md'
    - 'Listings List': 'edits_listings-list.md'
    - 'Listings Patch': 'edits_listings-patch.md'
    - 'Listings Update': 'edits_listings-update.md'
    - 'Testers Get': 'edits_testers-get.md'
    - 'Testers Patch': 'edits_testers-patch.md'
    - 'Testers Update': 'edits_testers-update.md'
    - 'Tracks Create': 'edits_tracks-create.md'
    - 'Tracks Get': 'edits_tracks-get.md'
    - 'Tracks List': 'edits_tracks-list.md'
    - 'Tracks Patch': 'edits_tracks-patch.md'
    - 'Tracks Update': 'edits_tracks-update.md'
    - 'Validate': 'edits_validate.md'
- 'Externaltransactions':
    - 'Createexternaltransaction': 'externaltransactions_createexternaltransaction.md'
    - 'Getexternaltransaction': 'externaltransactions_getexternaltransaction.md'
    - 'Refundexternaltransaction': 'externaltransactions_refundexternaltransaction.md'
- 'Generatedapks':
    - 'Download': 'generatedapks_download.md'
    - 'List': 'generatedapks_list.md'
- 'Grants':
    - 'Create': 'grants_create.md'
    - 'Delete': 'grants_delete.md'
    - 'Patch': 'grants_patch.md'
- 'Inappproducts':
    - 'Batch Delete': 'inappproducts_batch-delete.md'
    - 'Batch Get': 'inappproducts_batch-get.md'
    - 'Batch Update': 'inappproducts_batch-update.md'
    - 'Delete': 'inappproducts_delete.md'
    - 'Get': 'inappproducts_get.md'
    - 'Insert': 'inappproducts_insert.md'
    - 'List': 'inappproducts_list.md'
    - 'Patch': 'inappproducts_patch.md'
    - 'Update': 'inappproducts_update.md'
- 'Internalappsharingartifacts':
    - 'Uploadapk': 'internalappsharingartifacts_uploadapk.md'
    - 'Uploadbundle': 'internalappsharingartifacts_uploadbundle.md'
- 'Monetization':
    - 'Convert Region Prices': 'monetization_convert-region-prices.md'
    - 'Onetimeproducts Batch Delete': 'monetization_onetimeproducts-batch-delete.md'
    - 'Onetimeproducts Batch Get': 'monetization_onetimeproducts-batch-get.md'
    - 'Onetimeproducts Batch Update': 'monetization_onetimeproducts-batch-update.md'
    - 'Onetimeproducts Delete': 'monetization_onetimeproducts-delete.md'
    - 'Onetimeproducts Get': 'monetization_onetimeproducts-get.md'
    - 'Onetimeproducts List': 'monetization_onetimeproducts-list.md'
    - 'Onetimeproducts Patch': 'monetization_onetimeproducts-patch.md'
    - 'Onetimeproducts Purchase Options Batch Delete': 'monetization_onetimeproducts-purchase-options-batch-delete.md'
    - 'Onetimeproducts Purchase Options Batch Update States': 'monetization_onetimeproducts-purchase-options-batch-update-states.md'
    - 'Onetimeproducts Purchase Options Offers Activate': 'monetization_onetimeproducts-purchase-options-offers-activate.md'
    - 'Onetimeproducts Purchase Options Offers Batch Delete': 'monetization_onetimeproducts-purchase-options-offers-batch-delete.md'
    - 'Onetimeproducts Purchase Options Offers Batch Get': 'monetization_onetimeproducts-purchase-options-offers-batch-get.md'
    - 'Onetimeproducts Purchase Options Offers Batch Update': 'monetization_onetimeproducts-purchase-options-offers-batch-update.md'
    - 'Onetimeproducts Purchase Options Offers Batch Update States': 'monetization_onetimeproducts-purchase-options-offers-batch-update-states.md'
    - 'Onetimeproducts Purchase Options Offers Cancel': 'monetization_onetimeproducts-purchase-options-offers-cancel.md'
    - 'Onetimeproducts Purchase Options Offers Deactivate': 'monetization_onetimeproducts-purchase-options-offers-deactivate.md'
    - 'Onetimeproducts Purchase Options Offers List': 'monetization_onetimeproducts-purchase-options-offers-list.md'
    - 'Subscriptions Archive': 'monetization_subscriptions-archive.md'
    - 'Subscriptions Base Plans Activate': 'monetization_subscriptions-base-plans-activate.md'
    - 'Subscriptions Base Plans Batch Migrate Prices': 'monetization_subscriptions-base-plans-batch-migrate-prices.md'
    - 'Subscriptions Base Plans Batch Update States': 'monetization_subscriptions-base-plans-batch-update-states.md'
    - 'Subscriptions Base Plans Deactivate': 'monetization_subscriptions-base-plans-deactivate.md'
    - 'Subscriptions Base Plans Delete': 'monetization_subscriptions-base-plans-delete.md'
    - 'Subscriptions Base Plans Migrate Prices': 'monetization_subscriptions-base-plans-migrate-prices.md'
    - 'Subscriptions Base Plans Offers Activate': 'monetization_subscriptions-base-plans-offers-activate.md'
    - 'Subscriptions Base Plans Offers Batch Get': 'monetization_subscriptions-base-plans-offers-batch-get.md'
    - 'Subscriptions Base Plans Offers Batch Update': 'monetization_subscriptions-base-plans-offers-batch-update.md'
    - 'Subscriptions Base Plans Offers Batch Update States': 'monetization_subscriptions-base-plans-offers-batch-update-states.md'
    - 'Subscriptions Base Plans Offers Create': 'monetization_subscriptions-base-plans-offers-create.md'
    - 'Subscriptions Base Plans Offers Deactivate': 'monetization_subscriptions-base-plans-offers-deactivate.md'
    - 'Subscriptions Base Plans Offers Delete': 'monetization_subscriptions-base-plans-offers-delete.md'
    - 'Subscriptions Base Plans Offers Get': 'monetization_subscriptions-base-plans-offers-get.md'
    - 'Subscriptions Base Plans Offers List': 'monetization_subscriptions-base-plans-offers-list.md'
    - 'Subscriptions Base Plans Offers Patch': 'monetization_subscriptions-base-plans-offers-patch.md'
    - 'Subscriptions Batch Get': 'monetization_subscriptions-batch-get.md'
    - 'Subscriptions Batch Update': 'monetization_subscriptions-batch-update.md'
    - 'Subscriptions Create': 'monetization_subscriptions-create.md'
    - 'Subscriptions Delete': 'monetization_subscriptions-delete.md'
    - 'Subscriptions Get': 'monetization_subscriptions-get.md'
    - 'Subscriptions List': 'monetization_subscriptions-list.md'
    - 'Subscriptions Patch': 'monetization_subscriptions-patch.md'
- 'Orders':
    - 'Batchget': 'orders_batchget.md'
    - 'Get': 'orders_get.md'
    - 'Refund': 'orders_refund.md'
- 'Purchases':
    - 'Products Acknowledge': 'purchases_products-acknowledge.md'
    - 'Products Consume': 'purchases_products-consume.md'
    - 'Products Get': 'purchases_products-get.md'
    - 'Productsv2 Getproductpurchasev2': 'purchases_productsv2-getproductpurchasev2.md'
    - 'Subscriptions Acknowledge': 'purchases_subscriptions-acknowledge.md'
    - 'Subscriptions Cancel': 'purchases_subscriptions-cancel.md'
    - 'Subscriptions Defer': 'purchases_subscriptions-defer.md'
    - 'Subscriptions Get': 'purchases_subscriptions-get.md'
    - 'Subscriptions Refund': 'purchases_subscriptions-refund.md'
    - 'Subscriptions Revoke': 'purchases_subscriptions-revoke.md'
    - 'Subscriptionsv2 Cancel': 'purchases_subscriptionsv2-cancel.md'
    - 'Subscriptionsv2 Get': 'purchases_subscriptionsv2-get.md'
    - 'Subscriptionsv2 Revoke': 'purchases_subscriptionsv2-revoke.md'
    - 'Voidedpurchases List': 'purchases_voidedpurchases-list.md'
- 'Reviews':
    - 'Get': 'reviews_get.md'
    - 'List': 'reviews_list.md'
    - 'Reply': 'reviews_reply.md'
- 'Systemapks':
    - 'Variants Create': 'systemapks_variants-create.md'
    - 'Variants Download': 'systemapks_variants-download.md'
    - 'Variants Get': 'systemapks_variants-get.md'
    - 'Variants List': 'systemapks_variants-list.md'
- 'Users':
    - 'Create': 'users_create.md'
    - 'Delete': 'users_delete.md'
    - 'List': 'users_list.md'
    - 'Patch': 'users_patch.md'

theme: readthedocs

copyright: Copyright &copy; 2015â€“2024, `Sebastian Thiel`
