site_name: Play Integrity v7.0.0+20251216
site_url: http://byron.github.io/google-apis-rs/google-playintegrity1-cli
site_description: A complete library to interact with Play Integrity (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/playintegrity1-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Device Recall':
    - 'Write': 'device-recall_write.md'
- 'Methods':
    - 'Decode Integrity Token': 'methods_decode-integrity-token.md'
    - 'Decode Pc Integrity Token': 'methods_decode-pc-integrity-token.md'

theme: readthedocs

copyright: Copyright &copy; 2015â€“2024, `Sebastian Thiel`
