site_name: AlertCenter v2.0.3+20210323
site_url: http://byron.github.io/google-apis-rs/google-alertcenter1_beta1-cli
site_description: A complete library to interact with AlertCenter (protocol v1beta1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/alertcenter1_beta1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['alerts_batch-delete.md', 'Alerts', 'Batch Delete']
- ['alerts_batch-undelete.md', 'Alerts', 'Batch Undelete']
- ['alerts_delete.md', 'Alerts', 'Delete']
- ['alerts_feedback-create.md', 'Alerts', 'Feedback Create']
- ['alerts_feedback-list.md', 'Alerts', 'Feedback List']
- ['alerts_get.md', 'Alerts', 'Get']
- ['alerts_get-metadata.md', 'Alerts', 'Get Metadata']
- ['alerts_list.md', 'Alerts', 'List']
- ['alerts_undelete.md', 'Alerts', 'Undelete']
- ['methods_get-settings.md', 'Methods', 'Get Settings']
- ['methods_update-settings.md', 'Methods', 'Update Settings']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

