site_name: People Service v4.0.1+20220303
site_url: http://byron.github.io/google-apis-rs/google-people1-cli
site_description: A complete library to interact with People Service (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/people1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['contact-groups_batch-get.md', 'Contact Groups', 'Batch Get']
- ['contact-groups_create.md', 'Contact Groups', 'Create']
- ['contact-groups_delete.md', 'Contact Groups', 'Delete']
- ['contact-groups_get.md', 'Contact Groups', 'Get']
- ['contact-groups_list.md', 'Contact Groups', 'List']
- ['contact-groups_members-modify.md', 'Contact Groups', 'Members Modify']
- ['contact-groups_update.md', 'Contact Groups', 'Update']
- ['other-contacts_copy-other-contact-to-my-contacts-group.md', 'Other Contacts', 'Copy Other Contact To My Contacts Group']
- ['other-contacts_list.md', 'Other Contacts', 'List']
- ['other-contacts_search.md', 'Other Contacts', 'Search']
- ['people_batch-create-contacts.md', 'People', 'Batch Create Contacts']
- ['people_batch-delete-contacts.md', 'People', 'Batch Delete Contacts']
- ['people_batch-update-contacts.md', 'People', 'Batch Update Contacts']
- ['people_connections-list.md', 'People', 'Connections List']
- ['people_create-contact.md', 'People', 'Create Contact']
- ['people_delete-contact.md', 'People', 'Delete Contact']
- ['people_delete-contact-photo.md', 'People', 'Delete Contact Photo']
- ['people_get.md', 'People', 'Get']
- ['people_get-batch-get.md', 'People', 'Get Batch Get']
- ['people_list-directory-people.md', 'People', 'List Directory People']
- ['people_search-contacts.md', 'People', 'Search Contacts']
- ['people_search-directory-people.md', 'People', 'Search Directory People']
- ['people_update-contact.md', 'People', 'Update Contact']
- ['people_update-contact-photo.md', 'People', 'Update Contact Photo']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

