site_name: gan v4.0.1+20130205
site_url: http://byron.github.io/google-apis-rs/google-gan1_beta1-cli
site_description: A complete library to interact with gan (protocol v1beta1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/gan1_beta1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['advertisers_get.md', 'Advertisers', 'Get']
- ['advertisers_list.md', 'Advertisers', 'List']
- ['cc-offers_list.md', 'Cc Offers', 'List']
- ['events_list.md', 'Events', 'List']
- ['links_get.md', 'Links', 'Get']
- ['links_insert.md', 'Links', 'Insert']
- ['links_list.md', 'Links', 'List']
- ['publishers_get.md', 'Publishers', 'Get']
- ['publishers_list.md', 'Publishers', 'List']
- ['reports_get.md', 'Reports', 'Get']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

