site_name: Photos Library v1.0.10+20190702
site_url: http://byron.github.io/google-apis-rs/google-photoslibrary1-cli
site_description: A complete library to interact with Photos Library (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/photoslibrary1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['albums_add-enrichment.md', 'Albums', 'Add Enrichment']
- ['albums_batch-add-media-items.md', 'Albums', 'Batch Add Media Items']
- ['albums_batch-remove-media-items.md', 'Albums', 'Batch Remove Media Items']
- ['albums_create.md', 'Albums', 'Create']
- ['albums_get.md', 'Albums', 'Get']
- ['albums_list.md', 'Albums', 'List']
- ['albums_share.md', 'Albums', 'Share']
- ['albums_unshare.md', 'Albums', 'Unshare']
- ['media-items_batch-create.md', 'Media Items', 'Batch Create']
- ['media-items_batch-get.md', 'Media Items', 'Batch Get']
- ['media-items_get.md', 'Media Items', 'Get']
- ['media-items_list.md', 'Media Items', 'List']
- ['media-items_search.md', 'Media Items', 'Search']
- ['shared-albums_get.md', 'Shared Albums', 'Get']
- ['shared-albums_join.md', 'Shared Albums', 'Join']
- ['shared-albums_leave.md', 'Shared Albums', 'Leave']
- ['shared-albums_list.md', 'Shared Albums', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2019, `Sebastian Thiel`

