site_name: Keep v3.0.0+20220301
site_url: http://byron.github.io/google-apis-rs/google-keep1-cli
site_description: A complete library to interact with Keep (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/keep1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['media_download.md', 'Media', 'Download']
- ['notes_create.md', 'Notes', 'Create']
- ['notes_delete.md', 'Notes', 'Delete']
- ['notes_get.md', 'Notes', 'Get']
- ['notes_list.md', 'Notes', 'List']
- ['notes_permissions-batch-create.md', 'Notes', 'Permissions Batch Create']
- ['notes_permissions-batch-delete.md', 'Notes', 'Permissions Batch Delete']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

