site_name: Secret Manager v2.0.3+20210319
site_url: http://byron.github.io/google-apis-rs/google-secretmanager1_beta1-cli
site_description: A complete library to interact with Secret Manager (protocol v1beta1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/secretmanager1_beta1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_locations-get.md', 'Projects', 'Locations Get']
- ['projects_locations-list.md', 'Projects', 'Locations List']
- ['projects_secrets-add-version.md', 'Projects', 'Secrets Add Version']
- ['projects_secrets-create.md', 'Projects', 'Secrets Create']
- ['projects_secrets-delete.md', 'Projects', 'Secrets Delete']
- ['projects_secrets-get.md', 'Projects', 'Secrets Get']
- ['projects_secrets-get-iam-policy.md', 'Projects', 'Secrets Get Iam Policy']
- ['projects_secrets-list.md', 'Projects', 'Secrets List']
- ['projects_secrets-patch.md', 'Projects', 'Secrets Patch']
- ['projects_secrets-set-iam-policy.md', 'Projects', 'Secrets Set Iam Policy']
- ['projects_secrets-test-iam-permissions.md', 'Projects', 'Secrets Test Iam Permissions']
- ['projects_secrets-versions-access.md', 'Projects', 'Secrets Versions Access']
- ['projects_secrets-versions-destroy.md', 'Projects', 'Secrets Versions Destroy']
- ['projects_secrets-versions-disable.md', 'Projects', 'Secrets Versions Disable']
- ['projects_secrets-versions-enable.md', 'Projects', 'Secrets Versions Enable']
- ['projects_secrets-versions-get.md', 'Projects', 'Secrets Versions Get']
- ['projects_secrets-versions-list.md', 'Projects', 'Secrets Versions List']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

