site_name: Service Control v1.0.9+20190622
site_url: http://byron.github.io/google-apis-rs/google-servicecontrol1-cli
site_description: A complete library to interact with Service Control (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/servicecontrol1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['services_allocate-quota.md', 'Services', 'Allocate Quota']
- ['services_check.md', 'Services', 'Check']
- ['services_report.md', 'Services', 'Report']

theme: readthedocs

copyright: Copyright &copy; 2015-2019, `Sebastian Thiel`

