site_name: testing v2.0.0+20210326
site_url: http://byron.github.io/google-apis-rs/google-testing1-cli
site_description: A complete library to interact with testing (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/testing1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['application-detail-service_get-apk-details.md', 'Application Detail Service', 'Get Apk Details']
- ['projects_test-matrices-cancel.md', 'Projects', 'Test Matrices Cancel']
- ['projects_test-matrices-create.md', 'Projects', 'Test Matrices Create']
- ['projects_test-matrices-get.md', 'Projects', 'Test Matrices Get']
- ['test-environment-catalog_get.md', 'Test Environment Catalog', 'Get']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

