site_name: Cloud Natural Language v1.0.7+20180930
site_url: http://byron.github.io/google-apis-rs/google-language1-cli
site_description: A complete library to interact with Cloud Natural Language (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/language1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['documents_analyze-entities.md', 'Documents', 'Analyze Entities']
- ['documents_analyze-entity-sentiment.md', 'Documents', 'Analyze Entity Sentiment']
- ['documents_analyze-sentiment.md', 'Documents', 'Analyze Sentiment']
- ['documents_analyze-syntax.md', 'Documents', 'Analyze Syntax']
- ['documents_annotate-text.md', 'Documents', 'Annotate Text']
- ['documents_classify-text.md', 'Documents', 'Classify Text']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

