site_name: Cloud IAP v2.0.3+20210326
site_url: http://byron.github.io/google-apis-rs/google-iap1-cli
site_description: A complete library to interact with Cloud IAP (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/iap1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['methods_get-iam-policy.md', 'Methods', 'Get Iam Policy']
- ['methods_get-iap-settings.md', 'Methods', 'Get Iap Settings']
- ['methods_set-iam-policy.md', 'Methods', 'Set Iam Policy']
- ['methods_test-iam-permissions.md', 'Methods', 'Test Iam Permissions']
- ['methods_update-iap-settings.md', 'Methods', 'Update Iap Settings']
- ['projects_brands-create.md', 'Projects', 'Brands Create']
- ['projects_brands-get.md', 'Projects', 'Brands Get']
- ['projects_brands-identity-aware-proxy-clients-create.md', 'Projects', 'Brands Identity Aware Proxy Clients Create']
- ['projects_brands-identity-aware-proxy-clients-delete.md', 'Projects', 'Brands Identity Aware Proxy Clients Delete']
- ['projects_brands-identity-aware-proxy-clients-get.md', 'Projects', 'Brands Identity Aware Proxy Clients Get']
- ['projects_brands-identity-aware-proxy-clients-list.md', 'Projects', 'Brands Identity Aware Proxy Clients List']
- ['projects_brands-identity-aware-proxy-clients-reset-secret.md', 'Projects', 'Brands Identity Aware Proxy Clients Reset Secret']
- ['projects_brands-list.md', 'Projects', 'Brands List']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

