site_name: Firebase Hosting v3.0.0+20220212
site_url: http://byron.github.io/google-apis-rs/google-firebasehosting1_beta1-cli
site_description: A complete library to interact with Firebase Hosting (protocol v1beta1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/firebasehosting1_beta1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_operations-get.md', 'Projects', 'Operations Get']
- ['projects_sites-channels-create.md', 'Projects', 'Sites Channels Create']
- ['projects_sites-channels-delete.md', 'Projects', 'Sites Channels Delete']
- ['projects_sites-channels-get.md', 'Projects', 'Sites Channels Get']
- ['projects_sites-channels-list.md', 'Projects', 'Sites Channels List']
- ['projects_sites-channels-patch.md', 'Projects', 'Sites Channels Patch']
- ['projects_sites-channels-releases-create.md', 'Projects', 'Sites Channels Releases Create']
- ['projects_sites-channels-releases-list.md', 'Projects', 'Sites Channels Releases List']
- ['projects_sites-create.md', 'Projects', 'Sites Create']
- ['projects_sites-delete.md', 'Projects', 'Sites Delete']
- ['projects_sites-domains-create.md', 'Projects', 'Sites Domains Create']
- ['projects_sites-domains-delete.md', 'Projects', 'Sites Domains Delete']
- ['projects_sites-domains-get.md', 'Projects', 'Sites Domains Get']
- ['projects_sites-domains-list.md', 'Projects', 'Sites Domains List']
- ['projects_sites-domains-update.md', 'Projects', 'Sites Domains Update']
- ['projects_sites-get.md', 'Projects', 'Sites Get']
- ['projects_sites-get-config.md', 'Projects', 'Sites Get Config']
- ['projects_sites-list.md', 'Projects', 'Sites List']
- ['projects_sites-patch.md', 'Projects', 'Sites Patch']
- ['projects_sites-releases-create.md', 'Projects', 'Sites Releases Create']
- ['projects_sites-releases-list.md', 'Projects', 'Sites Releases List']
- ['projects_sites-update-config.md', 'Projects', 'Sites Update Config']
- ['projects_sites-versions-clone.md', 'Projects', 'Sites Versions Clone']
- ['projects_sites-versions-create.md', 'Projects', 'Sites Versions Create']
- ['projects_sites-versions-delete.md', 'Projects', 'Sites Versions Delete']
- ['projects_sites-versions-files-list.md', 'Projects', 'Sites Versions Files List']
- ['projects_sites-versions-list.md', 'Projects', 'Sites Versions List']
- ['projects_sites-versions-patch.md', 'Projects', 'Sites Versions Patch']
- ['projects_sites-versions-populate-files.md', 'Projects', 'Sites Versions Populate Files']
- ['sites_channels-create.md', 'Sites', 'Channels Create']
- ['sites_channels-delete.md', 'Sites', 'Channels Delete']
- ['sites_channels-get.md', 'Sites', 'Channels Get']
- ['sites_channels-list.md', 'Sites', 'Channels List']
- ['sites_channels-patch.md', 'Sites', 'Channels Patch']
- ['sites_channels-releases-create.md', 'Sites', 'Channels Releases Create']
- ['sites_channels-releases-list.md', 'Sites', 'Channels Releases List']
- ['sites_domains-create.md', 'Sites', 'Domains Create']
- ['sites_domains-delete.md', 'Sites', 'Domains Delete']
- ['sites_domains-get.md', 'Sites', 'Domains Get']
- ['sites_domains-list.md', 'Sites', 'Domains List']
- ['sites_domains-update.md', 'Sites', 'Domains Update']
- ['sites_get-config.md', 'Sites', 'Get Config']
- ['sites_releases-create.md', 'Sites', 'Releases Create']
- ['sites_releases-list.md', 'Sites', 'Releases List']
- ['sites_update-config.md', 'Sites', 'Update Config']
- ['sites_versions-clone.md', 'Sites', 'Versions Clone']
- ['sites_versions-create.md', 'Sites', 'Versions Create']
- ['sites_versions-delete.md', 'Sites', 'Versions Delete']
- ['sites_versions-files-list.md', 'Sites', 'Versions Files List']
- ['sites_versions-list.md', 'Sites', 'Versions List']
- ['sites_versions-patch.md', 'Sites', 'Versions Patch']
- ['sites_versions-populate-files.md', 'Sites', 'Versions Populate Files']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

