site_name: OrgPolicy API v2.0.0+20210330
site_url: http://byron.github.io/google-apis-rs/google-orgpolicy2-cli
site_description: A complete library to interact with OrgPolicy API (protocol v2)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/orgpolicy2-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['folders_constraints-list.md', 'Folders', 'Constraints List']
- ['folders_policies-create.md', 'Folders', 'Policies Create']
- ['folders_policies-delete.md', 'Folders', 'Policies Delete']
- ['folders_policies-get.md', 'Folders', 'Policies Get']
- ['folders_policies-get-effective-policy.md', 'Folders', 'Policies Get Effective Policy']
- ['folders_policies-list.md', 'Folders', 'Policies List']
- ['folders_policies-patch.md', 'Folders', 'Policies Patch']
- ['organizations_constraints-list.md', 'Organizations', 'Constraints List']
- ['organizations_policies-create.md', 'Organizations', 'Policies Create']
- ['organizations_policies-delete.md', 'Organizations', 'Policies Delete']
- ['organizations_policies-get.md', 'Organizations', 'Policies Get']
- ['organizations_policies-get-effective-policy.md', 'Organizations', 'Policies Get Effective Policy']
- ['organizations_policies-list.md', 'Organizations', 'Policies List']
- ['organizations_policies-patch.md', 'Organizations', 'Policies Patch']
- ['projects_constraints-list.md', 'Projects', 'Constraints List']
- ['projects_policies-create.md', 'Projects', 'Policies Create']
- ['projects_policies-delete.md', 'Projects', 'Policies Delete']
- ['projects_policies-get.md', 'Projects', 'Policies Get']
- ['projects_policies-get-effective-policy.md', 'Projects', 'Policies Get Effective Policy']
- ['projects_policies-list.md', 'Projects', 'Policies List']
- ['projects_policies-patch.md', 'Projects', 'Policies Patch']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

