site_name: Cloud IAP v5.0.3+20230118
site_url: http://byron.github.io/google-apis-rs/google-iap1_beta1-cli
site_description: A complete library to interact with Cloud IAP (protocol v1beta1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/iap1_beta1-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Methods':
    - 'Get Iam Policy': 'methods_get-iam-policy.md'
    - 'Set Iam Policy': 'methods_set-iam-policy.md'
    - 'Test Iam Permissions': 'methods_test-iam-permissions.md'

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

