site_name: Cloud Build v2.0.8+20210329
site_url: http://byron.github.io/google-apis-rs/google-cloudbuild1-cli
site_description: A complete library to interact with Cloud Build (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/cloudbuild1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['operations_cancel.md', 'Operations', 'Cancel']
- ['operations_get.md', 'Operations', 'Get']
- ['projects_builds-cancel.md', 'Projects', 'Builds Cancel']
- ['projects_builds-create.md', 'Projects', 'Builds Create']
- ['projects_builds-get.md', 'Projects', 'Builds Get']
- ['projects_builds-list.md', 'Projects', 'Builds List']
- ['projects_builds-retry.md', 'Projects', 'Builds Retry']
- ['projects_locations-builds-cancel.md', 'Projects', 'Locations Builds Cancel']
- ['projects_locations-builds-create.md', 'Projects', 'Locations Builds Create']
- ['projects_locations-builds-get.md', 'Projects', 'Locations Builds Get']
- ['projects_locations-builds-list.md', 'Projects', 'Locations Builds List']
- ['projects_locations-builds-retry.md', 'Projects', 'Locations Builds Retry']
- ['projects_locations-operations-cancel.md', 'Projects', 'Locations Operations Cancel']
- ['projects_locations-operations-get.md', 'Projects', 'Locations Operations Get']
- ['projects_triggers-create.md', 'Projects', 'Triggers Create']
- ['projects_triggers-delete.md', 'Projects', 'Triggers Delete']
- ['projects_triggers-get.md', 'Projects', 'Triggers Get']
- ['projects_triggers-list.md', 'Projects', 'Triggers List']
- ['projects_triggers-patch.md', 'Projects', 'Triggers Patch']
- ['projects_triggers-run.md', 'Projects', 'Triggers Run']
- ['projects_triggers-webhook.md', 'Projects', 'Triggers Webhook']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

