site_name: Cloud Build v1.0.7+20181011
site_url: http://byron.github.io/google-apis-rs/google-cloudbuild1-cli
site_description: A complete library to interact with Cloud Build (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/cloudbuild1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['operations_cancel.md', 'Operations', 'Cancel']
- ['operations_get.md', 'Operations', 'Get']
- ['operations_list.md', 'Operations', 'List']
- ['projects_builds-cancel.md', 'Projects', 'Builds Cancel']
- ['projects_builds-create.md', 'Projects', 'Builds Create']
- ['projects_builds-get.md', 'Projects', 'Builds Get']
- ['projects_builds-list.md', 'Projects', 'Builds List']
- ['projects_builds-retry.md', 'Projects', 'Builds Retry']
- ['projects_triggers-create.md', 'Projects', 'Triggers Create']
- ['projects_triggers-delete.md', 'Projects', 'Triggers Delete']
- ['projects_triggers-get.md', 'Projects', 'Triggers Get']
- ['projects_triggers-list.md', 'Projects', 'Triggers List']
- ['projects_triggers-patch.md', 'Projects', 'Triggers Patch']
- ['projects_triggers-run.md', 'Projects', 'Triggers Run']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

