site_name: verifiedaccess v3.1.0+20220215
site_url: http://byron.github.io/google-apis-rs/google-verifiedaccess1-cli
site_description: A complete library to interact with verifiedaccess (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/verifiedaccess1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['challenge_create.md', 'Challenge', 'Create']
- ['challenge_verify.md', 'Challenge', 'Verify']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

