site_name: reports v1.0.7+20180806
site_url: http://byron.github.io/google-apis-rs/google-admin1_reports-cli
site_description: A complete library to interact with reports (protocol reports_v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/admin1_reports-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['activities_list.md', 'Activities', 'List']
- ['activities_watch.md', 'Activities', 'Watch']
- ['channels_stop.md', 'Channels', 'Stop']
- ['customer-usage-reports_get.md', 'Customer Usage Reports', 'Get']
- ['entity-usage-reports_get.md', 'Entity Usage Reports', 'Get']
- ['user-usage-report_get.md', 'User Usage Report', 'Get']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

