site_name: Speech v2.0.4+20181005
site_url: http://byron.github.io/google-apis-rs/google-speech1_beta1-cli
site_description: A complete library to interact with Speech (protocol v1beta1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/speech1_beta1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['operations_get.md', 'Operations', 'Get']
- ['operations_list.md', 'Operations', 'List']
- ['speech_asyncrecognize.md', 'Speech', 'Asyncrecognize']
- ['speech_syncrecognize.md', 'Speech', 'Syncrecognize']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

