site_name: Firestore v1.0.7+20181001
site_url: http://byron.github.io/google-apis-rs/google-firestore1_beta1-cli
site_description: A complete library to interact with Firestore (protocol v1beta1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/firestore1_beta1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_databases-documents-batch-get.md', 'Projects', 'Databases Documents Batch Get']
- ['projects_databases-documents-begin-transaction.md', 'Projects', 'Databases Documents Begin Transaction']
- ['projects_databases-documents-commit.md', 'Projects', 'Databases Documents Commit']
- ['projects_databases-documents-create-document.md', 'Projects', 'Databases Documents Create Document']
- ['projects_databases-documents-delete.md', 'Projects', 'Databases Documents Delete']
- ['projects_databases-documents-get.md', 'Projects', 'Databases Documents Get']
- ['projects_databases-documents-list.md', 'Projects', 'Databases Documents List']
- ['projects_databases-documents-list-collection-ids.md', 'Projects', 'Databases Documents List Collection Ids']
- ['projects_databases-documents-listen.md', 'Projects', 'Databases Documents Listen']
- ['projects_databases-documents-patch.md', 'Projects', 'Databases Documents Patch']
- ['projects_databases-documents-rollback.md', 'Projects', 'Databases Documents Rollback']
- ['projects_databases-documents-run-query.md', 'Projects', 'Databases Documents Run Query']
- ['projects_databases-documents-write.md', 'Projects', 'Databases Documents Write']
- ['projects_databases-export-documents.md', 'Projects', 'Databases Export Documents']
- ['projects_databases-import-documents.md', 'Projects', 'Databases Import Documents']
- ['projects_databases-indexes-create.md', 'Projects', 'Databases Indexes Create']
- ['projects_databases-indexes-delete.md', 'Projects', 'Databases Indexes Delete']
- ['projects_databases-indexes-get.md', 'Projects', 'Databases Indexes Get']
- ['projects_databases-indexes-list.md', 'Projects', 'Databases Indexes List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

