site_name: DLP v4.0.1+20171205
site_url: http://byron.github.io/google-apis-rs/google-dlp2_beta1-cli
site_description: A complete library to interact with DLP (protocol v2beta1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/dlp2_beta1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['content_deidentify.md', 'Content', 'Deidentify']
- ['content_inspect.md', 'Content', 'Inspect']
- ['content_redact.md', 'Content', 'Redact']
- ['data-source_analyze.md', 'Data Source', 'Analyze']
- ['inspect_operations-cancel.md', 'Inspect', 'Operations Cancel']
- ['inspect_operations-create.md', 'Inspect', 'Operations Create']
- ['inspect_operations-delete.md', 'Inspect', 'Operations Delete']
- ['inspect_operations-get.md', 'Inspect', 'Operations Get']
- ['inspect_operations-list.md', 'Inspect', 'Operations List']
- ['inspect_results-findings-list.md', 'Inspect', 'Results Findings List']
- ['risk-analysis_operations-cancel.md', 'Risk Analysis', 'Operations Cancel']
- ['risk-analysis_operations-delete.md', 'Risk Analysis', 'Operations Delete']
- ['risk-analysis_operations-get.md', 'Risk Analysis', 'Operations Get']
- ['risk-analysis_operations-list.md', 'Risk Analysis', 'Operations List']
- ['root-categories_info-types-list.md', 'Root Categories', 'Info Types List']
- ['root-categories_list.md', 'Root Categories', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

