site_name: Ad Exchange Seller v0.3.6+20160805
site_url: http://byron.github.io/google-apis-rs/google-adexchangeseller2-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/adexchangeseller2-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['accounts_adclients-list.md', 'Accounts', 'Adclients List']
- ['accounts_alerts-list.md', 'Accounts', 'Alerts List']
- ['accounts_customchannels-get.md', 'Accounts', 'Customchannels Get']
- ['accounts_customchannels-list.md', 'Accounts', 'Customchannels List']
- ['accounts_get.md', 'Accounts', 'Get']
- ['accounts_list.md', 'Accounts', 'List']
- ['accounts_metadata-dimensions-list.md', 'Accounts', 'Metadata Dimensions List']
- ['accounts_metadata-metrics-list.md', 'Accounts', 'Metadata Metrics List']
- ['accounts_preferreddeals-get.md', 'Accounts', 'Preferreddeals Get']
- ['accounts_preferreddeals-list.md', 'Accounts', 'Preferreddeals List']
- ['accounts_reports-generate.md', 'Accounts', 'Reports Generate']
- ['accounts_reports-saved-generate.md', 'Accounts', 'Reports Saved Generate']
- ['accounts_reports-saved-list.md', 'Accounts', 'Reports Saved List']
- ['accounts_urlchannels-list.md', 'Accounts', 'Urlchannels List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

