site_name: Cloud Run v2.0.8+20210326
site_url: http://byron.github.io/google-apis-rs/google-run1-cli
site_description: A complete library to interact with Cloud Run (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/run1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['namespaces_authorizeddomains-list.md', 'Namespaces', 'Authorizeddomains List']
- ['namespaces_configurations-get.md', 'Namespaces', 'Configurations Get']
- ['namespaces_configurations-list.md', 'Namespaces', 'Configurations List']
- ['namespaces_domainmappings-create.md', 'Namespaces', 'Domainmappings Create']
- ['namespaces_domainmappings-delete.md', 'Namespaces', 'Domainmappings Delete']
- ['namespaces_domainmappings-get.md', 'Namespaces', 'Domainmappings Get']
- ['namespaces_domainmappings-list.md', 'Namespaces', 'Domainmappings List']
- ['namespaces_revisions-delete.md', 'Namespaces', 'Revisions Delete']
- ['namespaces_revisions-get.md', 'Namespaces', 'Revisions Get']
- ['namespaces_revisions-list.md', 'Namespaces', 'Revisions List']
- ['namespaces_routes-get.md', 'Namespaces', 'Routes Get']
- ['namespaces_routes-list.md', 'Namespaces', 'Routes List']
- ['namespaces_services-create.md', 'Namespaces', 'Services Create']
- ['namespaces_services-delete.md', 'Namespaces', 'Services Delete']
- ['namespaces_services-get.md', 'Namespaces', 'Services Get']
- ['namespaces_services-list.md', 'Namespaces', 'Services List']
- ['namespaces_services-replace-service.md', 'Namespaces', 'Services Replace Service']
- ['projects_authorizeddomains-list.md', 'Projects', 'Authorizeddomains List']
- ['projects_locations-authorizeddomains-list.md', 'Projects', 'Locations Authorizeddomains List']
- ['projects_locations-configurations-get.md', 'Projects', 'Locations Configurations Get']
- ['projects_locations-configurations-list.md', 'Projects', 'Locations Configurations List']
- ['projects_locations-domainmappings-create.md', 'Projects', 'Locations Domainmappings Create']
- ['projects_locations-domainmappings-delete.md', 'Projects', 'Locations Domainmappings Delete']
- ['projects_locations-domainmappings-get.md', 'Projects', 'Locations Domainmappings Get']
- ['projects_locations-domainmappings-list.md', 'Projects', 'Locations Domainmappings List']
- ['projects_locations-list.md', 'Projects', 'Locations List']
- ['projects_locations-revisions-delete.md', 'Projects', 'Locations Revisions Delete']
- ['projects_locations-revisions-get.md', 'Projects', 'Locations Revisions Get']
- ['projects_locations-revisions-list.md', 'Projects', 'Locations Revisions List']
- ['projects_locations-routes-get.md', 'Projects', 'Locations Routes Get']
- ['projects_locations-routes-list.md', 'Projects', 'Locations Routes List']
- ['projects_locations-services-create.md', 'Projects', 'Locations Services Create']
- ['projects_locations-services-delete.md', 'Projects', 'Locations Services Delete']
- ['projects_locations-services-get.md', 'Projects', 'Locations Services Get']
- ['projects_locations-services-get-iam-policy.md', 'Projects', 'Locations Services Get Iam Policy']
- ['projects_locations-services-list.md', 'Projects', 'Locations Services List']
- ['projects_locations-services-replace-service.md', 'Projects', 'Locations Services Replace Service']
- ['projects_locations-services-set-iam-policy.md', 'Projects', 'Locations Services Set Iam Policy']
- ['projects_locations-services-test-iam-permissions.md', 'Projects', 'Locations Services Test Iam Permissions']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

