site_name: replicapoolupdater v3.0.0+20161003
site_url: http://byron.github.io/google-apis-rs/google-replicapoolupdater1_beta1-cli
site_description: A complete library to interact with replicapoolupdater (protocol v1beta1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/replicapoolupdater1_beta1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['rolling-updates_cancel.md', 'Rolling Updates', 'Cancel']
- ['rolling-updates_get.md', 'Rolling Updates', 'Get']
- ['rolling-updates_insert.md', 'Rolling Updates', 'Insert']
- ['rolling-updates_list.md', 'Rolling Updates', 'List']
- ['rolling-updates_list-instance-updates.md', 'Rolling Updates', 'List Instance Updates']
- ['rolling-updates_pause.md', 'Rolling Updates', 'Pause']
- ['rolling-updates_resume.md', 'Rolling Updates', 'Resume']
- ['rolling-updates_rollback.md', 'Rolling Updates', 'Rollback']
- ['zone-operations_get.md', 'Zone Operations', 'Get']
- ['zone-operations_list.md', 'Zone Operations', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

