site_name: tasks v1.0.13+20190628
site_url: http://byron.github.io/google-apis-rs/google-tasks1-cli
site_description: A complete library to interact with tasks (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/tasks1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['tasklists_delete.md', 'Tasklists', 'Delete']
- ['tasklists_get.md', 'Tasklists', 'Get']
- ['tasklists_insert.md', 'Tasklists', 'Insert']
- ['tasklists_list.md', 'Tasklists', 'List']
- ['tasklists_patch.md', 'Tasklists', 'Patch']
- ['tasklists_update.md', 'Tasklists', 'Update']
- ['tasks_clear.md', 'Tasks', 'Clear']
- ['tasks_delete.md', 'Tasks', 'Delete']
- ['tasks_get.md', 'Tasks', 'Get']
- ['tasks_insert.md', 'Tasks', 'Insert']
- ['tasks_list.md', 'Tasks', 'List']
- ['tasks_move.md', 'Tasks', 'Move']
- ['tasks_patch.md', 'Tasks', 'Patch']
- ['tasks_update.md', 'Tasks', 'Update']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

