site_name: Display Video v4.0.1+20220303
site_url: http://byron.github.io/google-apis-rs/google-displayvideo1-cli
site_description: A complete library to interact with Display Video (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/displayvideo1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['advertisers_assets-upload.md', 'Advertisers', 'Assets Upload']
- ['advertisers_audit.md', 'Advertisers', 'Audit']
- ['advertisers_bulk-edit-advertiser-assigned-targeting-options.md', 'Advertisers', 'Bulk Edit Advertiser Assigned Targeting Options']
- ['advertisers_bulk-list-advertiser-assigned-targeting-options.md', 'Advertisers', 'Bulk List Advertiser Assigned Targeting Options']
- ['advertisers_campaigns-bulk-list-campaign-assigned-targeting-options.md', 'Advertisers', 'Campaigns Bulk List Campaign Assigned Targeting Options']
- ['advertisers_campaigns-create.md', 'Advertisers', 'Campaigns Create']
- ['advertisers_campaigns-delete.md', 'Advertisers', 'Campaigns Delete']
- ['advertisers_campaigns-get.md', 'Advertisers', 'Campaigns Get']
- ['advertisers_campaigns-list.md', 'Advertisers', 'Campaigns List']
- ['advertisers_campaigns-patch.md', 'Advertisers', 'Campaigns Patch']
- ['advertisers_campaigns-targeting-types-assigned-targeting-options-get.md', 'Advertisers', 'Campaigns Targeting Types Assigned Targeting Options Get']
- ['advertisers_campaigns-targeting-types-assigned-targeting-options-list.md', 'Advertisers', 'Campaigns Targeting Types Assigned Targeting Options List']
- ['advertisers_channels-create.md', 'Advertisers', 'Channels Create']
- ['advertisers_channels-get.md', 'Advertisers', 'Channels Get']
- ['advertisers_channels-list.md', 'Advertisers', 'Channels List']
- ['advertisers_channels-patch.md', 'Advertisers', 'Channels Patch']
- ['advertisers_channels-sites-bulk-edit.md', 'Advertisers', 'Channels Sites Bulk Edit']
- ['advertisers_channels-sites-create.md', 'Advertisers', 'Channels Sites Create']
- ['advertisers_channels-sites-delete.md', 'Advertisers', 'Channels Sites Delete']
- ['advertisers_channels-sites-list.md', 'Advertisers', 'Channels Sites List']
- ['advertisers_channels-sites-replace.md', 'Advertisers', 'Channels Sites Replace']
- ['advertisers_create.md', 'Advertisers', 'Create']
- ['advertisers_creatives-create.md', 'Advertisers', 'Creatives Create']
- ['advertisers_creatives-delete.md', 'Advertisers', 'Creatives Delete']
- ['advertisers_creatives-get.md', 'Advertisers', 'Creatives Get']
- ['advertisers_creatives-list.md', 'Advertisers', 'Creatives List']
- ['advertisers_creatives-patch.md', 'Advertisers', 'Creatives Patch']
- ['advertisers_delete.md', 'Advertisers', 'Delete']
- ['advertisers_get.md', 'Advertisers', 'Get']
- ['advertisers_insertion-orders-bulk-list-insertion-order-assigned-targeting-options.md', 'Advertisers', 'Insertion Orders Bulk List Insertion Order Assigned Targeting Options']
- ['advertisers_insertion-orders-create.md', 'Advertisers', 'Insertion Orders Create']
- ['advertisers_insertion-orders-delete.md', 'Advertisers', 'Insertion Orders Delete']
- ['advertisers_insertion-orders-get.md', 'Advertisers', 'Insertion Orders Get']
- ['advertisers_insertion-orders-list.md', 'Advertisers', 'Insertion Orders List']
- ['advertisers_insertion-orders-patch.md', 'Advertisers', 'Insertion Orders Patch']
- ['advertisers_insertion-orders-targeting-types-assigned-targeting-options-get.md', 'Advertisers', 'Insertion Orders Targeting Types Assigned Targeting Options Get']
- ['advertisers_insertion-orders-targeting-types-assigned-targeting-options-list.md', 'Advertisers', 'Insertion Orders Targeting Types Assigned Targeting Options List']
- ['advertisers_invoices-list.md', 'Advertisers', 'Invoices List']
- ['advertisers_invoices-lookup-invoice-currency.md', 'Advertisers', 'Invoices Lookup Invoice Currency']
- ['advertisers_line-items-bulk-edit-line-item-assigned-targeting-options.md', 'Advertisers', 'Line Items Bulk Edit Line Item Assigned Targeting Options']
- ['advertisers_line-items-bulk-list-line-item-assigned-targeting-options.md', 'Advertisers', 'Line Items Bulk List Line Item Assigned Targeting Options']
- ['advertisers_line-items-create.md', 'Advertisers', 'Line Items Create']
- ['advertisers_line-items-delete.md', 'Advertisers', 'Line Items Delete']
- ['advertisers_line-items-generate-default.md', 'Advertisers', 'Line Items Generate Default']
- ['advertisers_line-items-get.md', 'Advertisers', 'Line Items Get']
- ['advertisers_line-items-list.md', 'Advertisers', 'Line Items List']
- ['advertisers_line-items-patch.md', 'Advertisers', 'Line Items Patch']
- ['advertisers_line-items-targeting-types-assigned-targeting-options-create.md', 'Advertisers', 'Line Items Targeting Types Assigned Targeting Options Create']
- ['advertisers_line-items-targeting-types-assigned-targeting-options-delete.md', 'Advertisers', 'Line Items Targeting Types Assigned Targeting Options Delete']
- ['advertisers_line-items-targeting-types-assigned-targeting-options-get.md', 'Advertisers', 'Line Items Targeting Types Assigned Targeting Options Get']
- ['advertisers_line-items-targeting-types-assigned-targeting-options-list.md', 'Advertisers', 'Line Items Targeting Types Assigned Targeting Options List']
- ['advertisers_list.md', 'Advertisers', 'List']
- ['advertisers_location-lists-assigned-locations-bulk-edit.md', 'Advertisers', 'Location Lists Assigned Locations Bulk Edit']
- ['advertisers_location-lists-assigned-locations-create.md', 'Advertisers', 'Location Lists Assigned Locations Create']
- ['advertisers_location-lists-assigned-locations-delete.md', 'Advertisers', 'Location Lists Assigned Locations Delete']
- ['advertisers_location-lists-assigned-locations-list.md', 'Advertisers', 'Location Lists Assigned Locations List']
- ['advertisers_location-lists-create.md', 'Advertisers', 'Location Lists Create']
- ['advertisers_location-lists-get.md', 'Advertisers', 'Location Lists Get']
- ['advertisers_location-lists-list.md', 'Advertisers', 'Location Lists List']
- ['advertisers_location-lists-patch.md', 'Advertisers', 'Location Lists Patch']
- ['advertisers_manual-triggers-activate.md', 'Advertisers', 'Manual Triggers Activate']
- ['advertisers_manual-triggers-create.md', 'Advertisers', 'Manual Triggers Create']
- ['advertisers_manual-triggers-deactivate.md', 'Advertisers', 'Manual Triggers Deactivate']
- ['advertisers_manual-triggers-get.md', 'Advertisers', 'Manual Triggers Get']
- ['advertisers_manual-triggers-list.md', 'Advertisers', 'Manual Triggers List']
- ['advertisers_manual-triggers-patch.md', 'Advertisers', 'Manual Triggers Patch']
- ['advertisers_negative-keyword-lists-create.md', 'Advertisers', 'Negative Keyword Lists Create']
- ['advertisers_negative-keyword-lists-delete.md', 'Advertisers', 'Negative Keyword Lists Delete']
- ['advertisers_negative-keyword-lists-get.md', 'Advertisers', 'Negative Keyword Lists Get']
- ['advertisers_negative-keyword-lists-list.md', 'Advertisers', 'Negative Keyword Lists List']
- ['advertisers_negative-keyword-lists-negative-keywords-bulk-edit.md', 'Advertisers', 'Negative Keyword Lists Negative Keywords Bulk Edit']
- ['advertisers_negative-keyword-lists-negative-keywords-create.md', 'Advertisers', 'Negative Keyword Lists Negative Keywords Create']
- ['advertisers_negative-keyword-lists-negative-keywords-delete.md', 'Advertisers', 'Negative Keyword Lists Negative Keywords Delete']
- ['advertisers_negative-keyword-lists-negative-keywords-list.md', 'Advertisers', 'Negative Keyword Lists Negative Keywords List']
- ['advertisers_negative-keyword-lists-negative-keywords-replace.md', 'Advertisers', 'Negative Keyword Lists Negative Keywords Replace']
- ['advertisers_negative-keyword-lists-patch.md', 'Advertisers', 'Negative Keyword Lists Patch']
- ['advertisers_patch.md', 'Advertisers', 'Patch']
- ['advertisers_targeting-types-assigned-targeting-options-create.md', 'Advertisers', 'Targeting Types Assigned Targeting Options Create']
- ['advertisers_targeting-types-assigned-targeting-options-delete.md', 'Advertisers', 'Targeting Types Assigned Targeting Options Delete']
- ['advertisers_targeting-types-assigned-targeting-options-get.md', 'Advertisers', 'Targeting Types Assigned Targeting Options Get']
- ['advertisers_targeting-types-assigned-targeting-options-list.md', 'Advertisers', 'Targeting Types Assigned Targeting Options List']
- ['combined-audiences_get.md', 'Combined Audiences', 'Get']
- ['combined-audiences_list.md', 'Combined Audiences', 'List']
- ['custom-bidding-algorithms_create.md', 'Custom Bidding Algorithms', 'Create']
- ['custom-bidding-algorithms_get.md', 'Custom Bidding Algorithms', 'Get']
- ['custom-bidding-algorithms_list.md', 'Custom Bidding Algorithms', 'List']
- ['custom-bidding-algorithms_patch.md', 'Custom Bidding Algorithms', 'Patch']
- ['custom-bidding-algorithms_scripts-create.md', 'Custom Bidding Algorithms', 'Scripts Create']
- ['custom-bidding-algorithms_scripts-get.md', 'Custom Bidding Algorithms', 'Scripts Get']
- ['custom-bidding-algorithms_scripts-list.md', 'Custom Bidding Algorithms', 'Scripts List']
- ['custom-bidding-algorithms_upload-script.md', 'Custom Bidding Algorithms', 'Upload Script']
- ['custom-lists_get.md', 'Custom Lists', 'Get']
- ['custom-lists_list.md', 'Custom Lists', 'List']
- ['first-and-third-party-audiences_create.md', 'First And Third Party Audiences', 'Create']
- ['first-and-third-party-audiences_edit-customer-match-members.md', 'First And Third Party Audiences', 'Edit Customer Match Members']
- ['first-and-third-party-audiences_get.md', 'First And Third Party Audiences', 'Get']
- ['first-and-third-party-audiences_list.md', 'First And Third Party Audiences', 'List']
- ['first-and-third-party-audiences_patch.md', 'First And Third Party Audiences', 'Patch']
- ['floodlight-groups_get.md', 'Floodlight Groups', 'Get']
- ['floodlight-groups_patch.md', 'Floodlight Groups', 'Patch']
- ['google-audiences_get.md', 'Google Audiences', 'Get']
- ['google-audiences_list.md', 'Google Audiences', 'List']
- ['inventory-source-groups_assigned-inventory-sources-bulk-edit.md', 'Inventory Source Groups', 'Assigned Inventory Sources Bulk Edit']
- ['inventory-source-groups_assigned-inventory-sources-create.md', 'Inventory Source Groups', 'Assigned Inventory Sources Create']
- ['inventory-source-groups_assigned-inventory-sources-delete.md', 'Inventory Source Groups', 'Assigned Inventory Sources Delete']
- ['inventory-source-groups_assigned-inventory-sources-list.md', 'Inventory Source Groups', 'Assigned Inventory Sources List']
- ['inventory-source-groups_create.md', 'Inventory Source Groups', 'Create']
- ['inventory-source-groups_delete.md', 'Inventory Source Groups', 'Delete']
- ['inventory-source-groups_get.md', 'Inventory Source Groups', 'Get']
- ['inventory-source-groups_list.md', 'Inventory Source Groups', 'List']
- ['inventory-source-groups_patch.md', 'Inventory Source Groups', 'Patch']
- ['inventory-sources_get.md', 'Inventory Sources', 'Get']
- ['inventory-sources_list.md', 'Inventory Sources', 'List']
- ['media_download.md', 'Media', 'Download']
- ['media_upload.md', 'Media', 'Upload']
- ['partners_bulk-edit-partner-assigned-targeting-options.md', 'Partners', 'Bulk Edit Partner Assigned Targeting Options']
- ['partners_channels-create.md', 'Partners', 'Channels Create']
- ['partners_channels-get.md', 'Partners', 'Channels Get']
- ['partners_channels-list.md', 'Partners', 'Channels List']
- ['partners_channels-patch.md', 'Partners', 'Channels Patch']
- ['partners_channels-sites-bulk-edit.md', 'Partners', 'Channels Sites Bulk Edit']
- ['partners_channels-sites-create.md', 'Partners', 'Channels Sites Create']
- ['partners_channels-sites-delete.md', 'Partners', 'Channels Sites Delete']
- ['partners_channels-sites-list.md', 'Partners', 'Channels Sites List']
- ['partners_channels-sites-replace.md', 'Partners', 'Channels Sites Replace']
- ['partners_get.md', 'Partners', 'Get']
- ['partners_list.md', 'Partners', 'List']
- ['partners_targeting-types-assigned-targeting-options-create.md', 'Partners', 'Targeting Types Assigned Targeting Options Create']
- ['partners_targeting-types-assigned-targeting-options-delete.md', 'Partners', 'Targeting Types Assigned Targeting Options Delete']
- ['partners_targeting-types-assigned-targeting-options-get.md', 'Partners', 'Targeting Types Assigned Targeting Options Get']
- ['partners_targeting-types-assigned-targeting-options-list.md', 'Partners', 'Targeting Types Assigned Targeting Options List']
- ['sdfdownloadtasks_create.md', 'Sdfdownloadtasks', 'Create']
- ['sdfdownloadtasks_operations-get.md', 'Sdfdownloadtasks', 'Operations Get']
- ['targeting-types_targeting-options-get.md', 'Targeting Types', 'Targeting Options Get']
- ['targeting-types_targeting-options-list.md', 'Targeting Types', 'Targeting Options List']
- ['targeting-types_targeting-options-search.md', 'Targeting Types', 'Targeting Options Search']
- ['users_bulk-edit-assigned-user-roles.md', 'Users', 'Bulk Edit Assigned User Roles']
- ['users_create.md', 'Users', 'Create']
- ['users_delete.md', 'Users', 'Delete']
- ['users_get.md', 'Users', 'Get']
- ['users_list.md', 'Users', 'List']
- ['users_patch.md', 'Users', 'Patch']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

