site_name: Display Video v5.0.5+20240620
site_url: http://byron.github.io/google-apis-rs/google-displayvideo1-cli
site_description: A complete library to interact with Display Video (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/displayvideo1-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Advertisers':
    - 'Assets Upload': 'advertisers_assets-upload.md'
    - 'Audit': 'advertisers_audit.md'
    - 'Bulk Edit Advertiser Assigned Targeting Options': 'advertisers_bulk-edit-advertiser-assigned-targeting-options.md'
    - 'Bulk List Advertiser Assigned Targeting Options': 'advertisers_bulk-list-advertiser-assigned-targeting-options.md'
    - 'Campaigns Bulk List Campaign Assigned Targeting Options': 'advertisers_campaigns-bulk-list-campaign-assigned-targeting-options.md'
    - 'Campaigns Create': 'advertisers_campaigns-create.md'
    - 'Campaigns Delete': 'advertisers_campaigns-delete.md'
    - 'Campaigns Get': 'advertisers_campaigns-get.md'
    - 'Campaigns List': 'advertisers_campaigns-list.md'
    - 'Campaigns Patch': 'advertisers_campaigns-patch.md'
    - 'Campaigns Targeting Types Assigned Targeting Options Get': 'advertisers_campaigns-targeting-types-assigned-targeting-options-get.md'
    - 'Campaigns Targeting Types Assigned Targeting Options List': 'advertisers_campaigns-targeting-types-assigned-targeting-options-list.md'
    - 'Channels Create': 'advertisers_channels-create.md'
    - 'Channels Get': 'advertisers_channels-get.md'
    - 'Channels List': 'advertisers_channels-list.md'
    - 'Channels Patch': 'advertisers_channels-patch.md'
    - 'Channels Sites Bulk Edit': 'advertisers_channels-sites-bulk-edit.md'
    - 'Channels Sites Create': 'advertisers_channels-sites-create.md'
    - 'Channels Sites Delete': 'advertisers_channels-sites-delete.md'
    - 'Channels Sites List': 'advertisers_channels-sites-list.md'
    - 'Channels Sites Replace': 'advertisers_channels-sites-replace.md'
    - 'Create': 'advertisers_create.md'
    - 'Creatives Create': 'advertisers_creatives-create.md'
    - 'Creatives Delete': 'advertisers_creatives-delete.md'
    - 'Creatives Get': 'advertisers_creatives-get.md'
    - 'Creatives List': 'advertisers_creatives-list.md'
    - 'Creatives Patch': 'advertisers_creatives-patch.md'
    - 'Delete': 'advertisers_delete.md'
    - 'Get': 'advertisers_get.md'
    - 'Insertion Orders Bulk List Insertion Order Assigned Targeting Options': 'advertisers_insertion-orders-bulk-list-insertion-order-assigned-targeting-options.md'
    - 'Insertion Orders Create': 'advertisers_insertion-orders-create.md'
    - 'Insertion Orders Delete': 'advertisers_insertion-orders-delete.md'
    - 'Insertion Orders Get': 'advertisers_insertion-orders-get.md'
    - 'Insertion Orders List': 'advertisers_insertion-orders-list.md'
    - 'Insertion Orders Patch': 'advertisers_insertion-orders-patch.md'
    - 'Insertion Orders Targeting Types Assigned Targeting Options Get': 'advertisers_insertion-orders-targeting-types-assigned-targeting-options-get.md'
    - 'Insertion Orders Targeting Types Assigned Targeting Options List': 'advertisers_insertion-orders-targeting-types-assigned-targeting-options-list.md'
    - 'Invoices List': 'advertisers_invoices-list.md'
    - 'Invoices Lookup Invoice Currency': 'advertisers_invoices-lookup-invoice-currency.md'
    - 'Line Items Bulk Edit Line Item Assigned Targeting Options': 'advertisers_line-items-bulk-edit-line-item-assigned-targeting-options.md'
    - 'Line Items Bulk List Line Item Assigned Targeting Options': 'advertisers_line-items-bulk-list-line-item-assigned-targeting-options.md'
    - 'Line Items Create': 'advertisers_line-items-create.md'
    - 'Line Items Delete': 'advertisers_line-items-delete.md'
    - 'Line Items Generate Default': 'advertisers_line-items-generate-default.md'
    - 'Line Items Get': 'advertisers_line-items-get.md'
    - 'Line Items List': 'advertisers_line-items-list.md'
    - 'Line Items Patch': 'advertisers_line-items-patch.md'
    - 'Line Items Targeting Types Assigned Targeting Options Create': 'advertisers_line-items-targeting-types-assigned-targeting-options-create.md'
    - 'Line Items Targeting Types Assigned Targeting Options Delete': 'advertisers_line-items-targeting-types-assigned-targeting-options-delete.md'
    - 'Line Items Targeting Types Assigned Targeting Options Get': 'advertisers_line-items-targeting-types-assigned-targeting-options-get.md'
    - 'Line Items Targeting Types Assigned Targeting Options List': 'advertisers_line-items-targeting-types-assigned-targeting-options-list.md'
    - 'List': 'advertisers_list.md'
    - 'Location Lists Assigned Locations Bulk Edit': 'advertisers_location-lists-assigned-locations-bulk-edit.md'
    - 'Location Lists Assigned Locations Create': 'advertisers_location-lists-assigned-locations-create.md'
    - 'Location Lists Assigned Locations Delete': 'advertisers_location-lists-assigned-locations-delete.md'
    - 'Location Lists Assigned Locations List': 'advertisers_location-lists-assigned-locations-list.md'
    - 'Location Lists Create': 'advertisers_location-lists-create.md'
    - 'Location Lists Get': 'advertisers_location-lists-get.md'
    - 'Location Lists List': 'advertisers_location-lists-list.md'
    - 'Location Lists Patch': 'advertisers_location-lists-patch.md'
    - 'Manual Triggers Activate': 'advertisers_manual-triggers-activate.md'
    - 'Manual Triggers Create': 'advertisers_manual-triggers-create.md'
    - 'Manual Triggers Deactivate': 'advertisers_manual-triggers-deactivate.md'
    - 'Manual Triggers Get': 'advertisers_manual-triggers-get.md'
    - 'Manual Triggers List': 'advertisers_manual-triggers-list.md'
    - 'Manual Triggers Patch': 'advertisers_manual-triggers-patch.md'
    - 'Negative Keyword Lists Create': 'advertisers_negative-keyword-lists-create.md'
    - 'Negative Keyword Lists Delete': 'advertisers_negative-keyword-lists-delete.md'
    - 'Negative Keyword Lists Get': 'advertisers_negative-keyword-lists-get.md'
    - 'Negative Keyword Lists List': 'advertisers_negative-keyword-lists-list.md'
    - 'Negative Keyword Lists Negative Keywords Bulk Edit': 'advertisers_negative-keyword-lists-negative-keywords-bulk-edit.md'
    - 'Negative Keyword Lists Negative Keywords Create': 'advertisers_negative-keyword-lists-negative-keywords-create.md'
    - 'Negative Keyword Lists Negative Keywords Delete': 'advertisers_negative-keyword-lists-negative-keywords-delete.md'
    - 'Negative Keyword Lists Negative Keywords List': 'advertisers_negative-keyword-lists-negative-keywords-list.md'
    - 'Negative Keyword Lists Negative Keywords Replace': 'advertisers_negative-keyword-lists-negative-keywords-replace.md'
    - 'Negative Keyword Lists Patch': 'advertisers_negative-keyword-lists-patch.md'
    - 'Patch': 'advertisers_patch.md'
    - 'Targeting Types Assigned Targeting Options Create': 'advertisers_targeting-types-assigned-targeting-options-create.md'
    - 'Targeting Types Assigned Targeting Options Delete': 'advertisers_targeting-types-assigned-targeting-options-delete.md'
    - 'Targeting Types Assigned Targeting Options Get': 'advertisers_targeting-types-assigned-targeting-options-get.md'
    - 'Targeting Types Assigned Targeting Options List': 'advertisers_targeting-types-assigned-targeting-options-list.md'
- 'Combined Audiences':
    - 'Get': 'combined-audiences_get.md'
    - 'List': 'combined-audiences_list.md'
- 'Custom Bidding Algorithms':
    - 'Create': 'custom-bidding-algorithms_create.md'
    - 'Get': 'custom-bidding-algorithms_get.md'
    - 'List': 'custom-bidding-algorithms_list.md'
    - 'Patch': 'custom-bidding-algorithms_patch.md'
    - 'Scripts Create': 'custom-bidding-algorithms_scripts-create.md'
    - 'Scripts Get': 'custom-bidding-algorithms_scripts-get.md'
    - 'Scripts List': 'custom-bidding-algorithms_scripts-list.md'
    - 'Upload Script': 'custom-bidding-algorithms_upload-script.md'
- 'Custom Lists':
    - 'Get': 'custom-lists_get.md'
    - 'List': 'custom-lists_list.md'
- 'First And Third Party Audiences':
    - 'Create': 'first-and-third-party-audiences_create.md'
    - 'Edit Customer Match Members': 'first-and-third-party-audiences_edit-customer-match-members.md'
    - 'Get': 'first-and-third-party-audiences_get.md'
    - 'List': 'first-and-third-party-audiences_list.md'
    - 'Patch': 'first-and-third-party-audiences_patch.md'
- 'Floodlight Groups':
    - 'Get': 'floodlight-groups_get.md'
    - 'Patch': 'floodlight-groups_patch.md'
- 'Google Audiences':
    - 'Get': 'google-audiences_get.md'
    - 'List': 'google-audiences_list.md'
- 'Guaranteed Orders':
    - 'Create': 'guaranteed-orders_create.md'
    - 'Edit Guaranteed Order Read Accessors': 'guaranteed-orders_edit-guaranteed-order-read-accessors.md'
    - 'Get': 'guaranteed-orders_get.md'
    - 'List': 'guaranteed-orders_list.md'
    - 'Patch': 'guaranteed-orders_patch.md'
- 'Inventory Source Groups':
    - 'Assigned Inventory Sources Bulk Edit': 'inventory-source-groups_assigned-inventory-sources-bulk-edit.md'
    - 'Assigned Inventory Sources Create': 'inventory-source-groups_assigned-inventory-sources-create.md'
    - 'Assigned Inventory Sources Delete': 'inventory-source-groups_assigned-inventory-sources-delete.md'
    - 'Assigned Inventory Sources List': 'inventory-source-groups_assigned-inventory-sources-list.md'
    - 'Create': 'inventory-source-groups_create.md'
    - 'Delete': 'inventory-source-groups_delete.md'
    - 'Get': 'inventory-source-groups_get.md'
    - 'List': 'inventory-source-groups_list.md'
    - 'Patch': 'inventory-source-groups_patch.md'
- 'Inventory Sources':
    - 'Create': 'inventory-sources_create.md'
    - 'Edit Inventory Source Read Write Accessors': 'inventory-sources_edit-inventory-source-read-write-accessors.md'
    - 'Get': 'inventory-sources_get.md'
    - 'List': 'inventory-sources_list.md'
    - 'Patch': 'inventory-sources_patch.md'
- 'Media':
    - 'Download': 'media_download.md'
    - 'Upload': 'media_upload.md'
- 'Partners':
    - 'Bulk Edit Partner Assigned Targeting Options': 'partners_bulk-edit-partner-assigned-targeting-options.md'
    - 'Channels Create': 'partners_channels-create.md'
    - 'Channels Get': 'partners_channels-get.md'
    - 'Channels List': 'partners_channels-list.md'
    - 'Channels Patch': 'partners_channels-patch.md'
    - 'Channels Sites Bulk Edit': 'partners_channels-sites-bulk-edit.md'
    - 'Channels Sites Create': 'partners_channels-sites-create.md'
    - 'Channels Sites Delete': 'partners_channels-sites-delete.md'
    - 'Channels Sites List': 'partners_channels-sites-list.md'
    - 'Channels Sites Replace': 'partners_channels-sites-replace.md'
    - 'Get': 'partners_get.md'
    - 'List': 'partners_list.md'
    - 'Targeting Types Assigned Targeting Options Create': 'partners_targeting-types-assigned-targeting-options-create.md'
    - 'Targeting Types Assigned Targeting Options Delete': 'partners_targeting-types-assigned-targeting-options-delete.md'
    - 'Targeting Types Assigned Targeting Options Get': 'partners_targeting-types-assigned-targeting-options-get.md'
    - 'Targeting Types Assigned Targeting Options List': 'partners_targeting-types-assigned-targeting-options-list.md'
- 'Sdfdownloadtasks':
    - 'Create': 'sdfdownloadtasks_create.md'
    - 'Operations Get': 'sdfdownloadtasks_operations-get.md'
- 'Targeting Types':
    - 'Targeting Options Get': 'targeting-types_targeting-options-get.md'
    - 'Targeting Options List': 'targeting-types_targeting-options-list.md'
    - 'Targeting Options Search': 'targeting-types_targeting-options-search.md'
- 'Users':
    - 'Bulk Edit Assigned User Roles': 'users_bulk-edit-assigned-user-roles.md'
    - 'Create': 'users_create.md'
    - 'Delete': 'users_delete.md'
    - 'Get': 'users_get.md'
    - 'List': 'users_list.md'
    - 'Patch': 'users_patch.md'

theme: readthedocs

copyright: Copyright &copy; 2015â€“2024, `Sebastian Thiel`

