site_name: plus v1.0.4+20161214
site_url: http://byron.github.io/google-apis-rs/google-plus1-cli
site_description: A complete library to interact with plus (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/plus1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['activities_get.md', 'Activities', 'Get']
- ['activities_list.md', 'Activities', 'List']
- ['activities_search.md', 'Activities', 'Search']
- ['comments_get.md', 'Comments', 'Get']
- ['comments_list.md', 'Comments', 'List']
- ['people_get.md', 'People', 'Get']
- ['people_list.md', 'People', 'List']
- ['people_list-by-activity.md', 'People', 'List By Activity']
- ['people_search.md', 'People', 'Search']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

