site_name: Consumer Surveys v3.1.0+20170407
site_url: http://byron.github.io/google-apis-rs/google-consumersurveys2-cli
site_description: A complete library to interact with Consumer Surveys (protocol v2)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/consumersurveys2-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['mobileapppanels_get.md', 'Mobileapppanels', 'Get']
- ['mobileapppanels_list.md', 'Mobileapppanels', 'List']
- ['mobileapppanels_update.md', 'Mobileapppanels', 'Update']
- ['results_get.md', 'Results', 'Get']
- ['surveys_delete.md', 'Surveys', 'Delete']
- ['surveys_get.md', 'Surveys', 'Get']
- ['surveys_insert.md', 'Surveys', 'Insert']
- ['surveys_list.md', 'Surveys', 'List']
- ['surveys_start.md', 'Surveys', 'Start']
- ['surveys_stop.md', 'Surveys', 'Stop']
- ['surveys_update.md', 'Surveys', 'Update']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

