site_name: siteVerification v1.0.7+20180830
site_url: http://byron.github.io/google-apis-rs/google-siteverification1-cli
site_description: A complete library to interact with siteVerification (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/siteverification1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['web-resource_delete.md', 'Web Resource', 'Delete']
- ['web-resource_get.md', 'Web Resource', 'Get']
- ['web-resource_get-token.md', 'Web Resource', 'Get Token']
- ['web-resource_insert.md', 'Web Resource', 'Insert']
- ['web-resource_list.md', 'Web Resource', 'List']
- ['web-resource_patch.md', 'Web Resource', 'Patch']
- ['web-resource_update.md', 'Web Resource', 'Update']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

