site_name: Pagespeed Insights v5.0.3+20230123
site_url: http://byron.github.io/google-apis-rs/google-pagespeedonline5-cli
site_description: A complete library to interact with Pagespeed Insights (protocol v5)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/pagespeedonline5-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Pagespeedapi':
    - 'Runpagespeed': 'pagespeedapi_runpagespeed.md'

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

