site_name: coordinate v1.0.6+20150811
site_url: http://byron.github.io/google-apis-rs/google-coordinate1-cli
site_description: A complete library to interact with coordinate (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/coordinate1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['custom-field-def_list.md', 'Custom Field Def', 'List']
- ['jobs_get.md', 'Jobs', 'Get']
- ['jobs_insert.md', 'Jobs', 'Insert']
- ['jobs_list.md', 'Jobs', 'List']
- ['jobs_patch.md', 'Jobs', 'Patch']
- ['jobs_update.md', 'Jobs', 'Update']
- ['location_list.md', 'Location', 'List']
- ['schedule_get.md', 'Schedule', 'Get']
- ['schedule_patch.md', 'Schedule', 'Patch']
- ['schedule_update.md', 'Schedule', 'Update']
- ['team_list.md', 'Team', 'List']
- ['worker_list.md', 'Worker', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

