site_name: Ad Exchange Buyer v1.0.7+20180823
site_url: http://byron.github.io/google-apis-rs/google-adexchangebuyer1d4-cli
site_description: A complete library to interact with Ad Exchange Buyer (protocol v1.4)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/adexchangebuyer1d4-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['accounts_get.md', 'Accounts', 'Get']
- ['accounts_list.md', 'Accounts', 'List']
- ['accounts_patch.md', 'Accounts', 'Patch']
- ['accounts_update.md', 'Accounts', 'Update']
- ['billing-info_get.md', 'Billing Info', 'Get']
- ['billing-info_list.md', 'Billing Info', 'List']
- ['budget_get.md', 'Budget', 'Get']
- ['budget_patch.md', 'Budget', 'Patch']
- ['budget_update.md', 'Budget', 'Update']
- ['creatives_add-deal.md', 'Creatives', 'Add Deal']
- ['creatives_get.md', 'Creatives', 'Get']
- ['creatives_insert.md', 'Creatives', 'Insert']
- ['creatives_list.md', 'Creatives', 'List']
- ['creatives_list-deals.md', 'Creatives', 'List Deals']
- ['creatives_remove-deal.md', 'Creatives', 'Remove Deal']
- ['marketplacedeals_delete.md', 'Marketplacedeals', 'Delete']
- ['marketplacedeals_insert.md', 'Marketplacedeals', 'Insert']
- ['marketplacedeals_list.md', 'Marketplacedeals', 'List']
- ['marketplacedeals_update.md', 'Marketplacedeals', 'Update']
- ['marketplacenotes_insert.md', 'Marketplacenotes', 'Insert']
- ['marketplacenotes_list.md', 'Marketplacenotes', 'List']
- ['marketplaceprivateauction_updateproposal.md', 'Marketplaceprivateauction', 'Updateproposal']
- ['performance-report_list.md', 'Performance Report', 'List']
- ['pretargeting-config_delete.md', 'Pretargeting Config', 'Delete']
- ['pretargeting-config_get.md', 'Pretargeting Config', 'Get']
- ['pretargeting-config_insert.md', 'Pretargeting Config', 'Insert']
- ['pretargeting-config_list.md', 'Pretargeting Config', 'List']
- ['pretargeting-config_patch.md', 'Pretargeting Config', 'Patch']
- ['pretargeting-config_update.md', 'Pretargeting Config', 'Update']
- ['products_get.md', 'Products', 'Get']
- ['products_search.md', 'Products', 'Search']
- ['proposals_get.md', 'Proposals', 'Get']
- ['proposals_insert.md', 'Proposals', 'Insert']
- ['proposals_patch.md', 'Proposals', 'Patch']
- ['proposals_search.md', 'Proposals', 'Search']
- ['proposals_setupcomplete.md', 'Proposals', 'Setupcomplete']
- ['proposals_update.md', 'Proposals', 'Update']
- ['pubprofiles_list.md', 'Pubprofiles', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

