site_name: Cloud Dataplex v5.0.5+20240611
site_url: http://byron.github.io/google-apis-rs/google-dataplex1-cli
site_description: A complete library to interact with Cloud Dataplex (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/dataplex1-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Projects':
    - 'Locations Aspect Types Create': 'projects_locations-aspect-types-create.md'
    - 'Locations Aspect Types Delete': 'projects_locations-aspect-types-delete.md'
    - 'Locations Aspect Types Get': 'projects_locations-aspect-types-get.md'
    - 'Locations Aspect Types Get Iam Policy': 'projects_locations-aspect-types-get-iam-policy.md'
    - 'Locations Aspect Types List': 'projects_locations-aspect-types-list.md'
    - 'Locations Aspect Types Patch': 'projects_locations-aspect-types-patch.md'
    - 'Locations Aspect Types Set Iam Policy': 'projects_locations-aspect-types-set-iam-policy.md'
    - 'Locations Aspect Types Test Iam Permissions': 'projects_locations-aspect-types-test-iam-permissions.md'
    - 'Locations Data Attribute Bindings Create': 'projects_locations-data-attribute-bindings-create.md'
    - 'Locations Data Attribute Bindings Delete': 'projects_locations-data-attribute-bindings-delete.md'
    - 'Locations Data Attribute Bindings Get': 'projects_locations-data-attribute-bindings-get.md'
    - 'Locations Data Attribute Bindings Get Iam Policy': 'projects_locations-data-attribute-bindings-get-iam-policy.md'
    - 'Locations Data Attribute Bindings List': 'projects_locations-data-attribute-bindings-list.md'
    - 'Locations Data Attribute Bindings Patch': 'projects_locations-data-attribute-bindings-patch.md'
    - 'Locations Data Attribute Bindings Set Iam Policy': 'projects_locations-data-attribute-bindings-set-iam-policy.md'
    - 'Locations Data Attribute Bindings Test Iam Permissions': 'projects_locations-data-attribute-bindings-test-iam-permissions.md'
    - 'Locations Data Scans Create': 'projects_locations-data-scans-create.md'
    - 'Locations Data Scans Delete': 'projects_locations-data-scans-delete.md'
    - 'Locations Data Scans Generate Data Quality Rules': 'projects_locations-data-scans-generate-data-quality-rules.md'
    - 'Locations Data Scans Get': 'projects_locations-data-scans-get.md'
    - 'Locations Data Scans Get Iam Policy': 'projects_locations-data-scans-get-iam-policy.md'
    - 'Locations Data Scans Jobs Generate Data Quality Rules': 'projects_locations-data-scans-jobs-generate-data-quality-rules.md'
    - 'Locations Data Scans Jobs Get': 'projects_locations-data-scans-jobs-get.md'
    - 'Locations Data Scans Jobs List': 'projects_locations-data-scans-jobs-list.md'
    - 'Locations Data Scans List': 'projects_locations-data-scans-list.md'
    - 'Locations Data Scans Patch': 'projects_locations-data-scans-patch.md'
    - 'Locations Data Scans Run': 'projects_locations-data-scans-run.md'
    - 'Locations Data Scans Set Iam Policy': 'projects_locations-data-scans-set-iam-policy.md'
    - 'Locations Data Scans Test Iam Permissions': 'projects_locations-data-scans-test-iam-permissions.md'
    - 'Locations Data Taxonomies Attributes Create': 'projects_locations-data-taxonomies-attributes-create.md'
    - 'Locations Data Taxonomies Attributes Delete': 'projects_locations-data-taxonomies-attributes-delete.md'
    - 'Locations Data Taxonomies Attributes Get': 'projects_locations-data-taxonomies-attributes-get.md'
    - 'Locations Data Taxonomies Attributes Get Iam Policy': 'projects_locations-data-taxonomies-attributes-get-iam-policy.md'
    - 'Locations Data Taxonomies Attributes List': 'projects_locations-data-taxonomies-attributes-list.md'
    - 'Locations Data Taxonomies Attributes Patch': 'projects_locations-data-taxonomies-attributes-patch.md'
    - 'Locations Data Taxonomies Attributes Set Iam Policy': 'projects_locations-data-taxonomies-attributes-set-iam-policy.md'
    - 'Locations Data Taxonomies Attributes Test Iam Permissions': 'projects_locations-data-taxonomies-attributes-test-iam-permissions.md'
    - 'Locations Data Taxonomies Create': 'projects_locations-data-taxonomies-create.md'
    - 'Locations Data Taxonomies Delete': 'projects_locations-data-taxonomies-delete.md'
    - 'Locations Data Taxonomies Get': 'projects_locations-data-taxonomies-get.md'
    - 'Locations Data Taxonomies Get Iam Policy': 'projects_locations-data-taxonomies-get-iam-policy.md'
    - 'Locations Data Taxonomies List': 'projects_locations-data-taxonomies-list.md'
    - 'Locations Data Taxonomies Patch': 'projects_locations-data-taxonomies-patch.md'
    - 'Locations Data Taxonomies Set Iam Policy': 'projects_locations-data-taxonomies-set-iam-policy.md'
    - 'Locations Data Taxonomies Test Iam Permissions': 'projects_locations-data-taxonomies-test-iam-permissions.md'
    - 'Locations Entry Groups Create': 'projects_locations-entry-groups-create.md'
    - 'Locations Entry Groups Delete': 'projects_locations-entry-groups-delete.md'
    - 'Locations Entry Groups Entries Create': 'projects_locations-entry-groups-entries-create.md'
    - 'Locations Entry Groups Entries Delete': 'projects_locations-entry-groups-entries-delete.md'
    - 'Locations Entry Groups Entries Get': 'projects_locations-entry-groups-entries-get.md'
    - 'Locations Entry Groups Entries List': 'projects_locations-entry-groups-entries-list.md'
    - 'Locations Entry Groups Entries Patch': 'projects_locations-entry-groups-entries-patch.md'
    - 'Locations Entry Groups Get': 'projects_locations-entry-groups-get.md'
    - 'Locations Entry Groups Get Iam Policy': 'projects_locations-entry-groups-get-iam-policy.md'
    - 'Locations Entry Groups List': 'projects_locations-entry-groups-list.md'
    - 'Locations Entry Groups Patch': 'projects_locations-entry-groups-patch.md'
    - 'Locations Entry Groups Set Iam Policy': 'projects_locations-entry-groups-set-iam-policy.md'
    - 'Locations Entry Groups Test Iam Permissions': 'projects_locations-entry-groups-test-iam-permissions.md'
    - 'Locations Entry Types Create': 'projects_locations-entry-types-create.md'
    - 'Locations Entry Types Delete': 'projects_locations-entry-types-delete.md'
    - 'Locations Entry Types Get': 'projects_locations-entry-types-get.md'
    - 'Locations Entry Types Get Iam Policy': 'projects_locations-entry-types-get-iam-policy.md'
    - 'Locations Entry Types List': 'projects_locations-entry-types-list.md'
    - 'Locations Entry Types Patch': 'projects_locations-entry-types-patch.md'
    - 'Locations Entry Types Set Iam Policy': 'projects_locations-entry-types-set-iam-policy.md'
    - 'Locations Entry Types Test Iam Permissions': 'projects_locations-entry-types-test-iam-permissions.md'
    - 'Locations Get': 'projects_locations-get.md'
    - 'Locations Governance Rules Get Iam Policy': 'projects_locations-governance-rules-get-iam-policy.md'
    - 'Locations Governance Rules Set Iam Policy': 'projects_locations-governance-rules-set-iam-policy.md'
    - 'Locations Governance Rules Test Iam Permissions': 'projects_locations-governance-rules-test-iam-permissions.md'
    - 'Locations Lakes Actions List': 'projects_locations-lakes-actions-list.md'
    - 'Locations Lakes Content Create': 'projects_locations-lakes-content-create.md'
    - 'Locations Lakes Content Delete': 'projects_locations-lakes-content-delete.md'
    - 'Locations Lakes Content Get': 'projects_locations-lakes-content-get.md'
    - 'Locations Lakes Content Get Iam Policy': 'projects_locations-lakes-content-get-iam-policy.md'
    - 'Locations Lakes Content List': 'projects_locations-lakes-content-list.md'
    - 'Locations Lakes Content Patch': 'projects_locations-lakes-content-patch.md'
    - 'Locations Lakes Content Set Iam Policy': 'projects_locations-lakes-content-set-iam-policy.md'
    - 'Locations Lakes Content Test Iam Permissions': 'projects_locations-lakes-content-test-iam-permissions.md'
    - 'Locations Lakes Contentitems Create': 'projects_locations-lakes-contentitems-create.md'
    - 'Locations Lakes Contentitems Delete': 'projects_locations-lakes-contentitems-delete.md'
    - 'Locations Lakes Contentitems Get': 'projects_locations-lakes-contentitems-get.md'
    - 'Locations Lakes Contentitems Get Iam Policy': 'projects_locations-lakes-contentitems-get-iam-policy.md'
    - 'Locations Lakes Contentitems List': 'projects_locations-lakes-contentitems-list.md'
    - 'Locations Lakes Contentitems Patch': 'projects_locations-lakes-contentitems-patch.md'
    - 'Locations Lakes Contentitems Set Iam Policy': 'projects_locations-lakes-contentitems-set-iam-policy.md'
    - 'Locations Lakes Contentitems Test Iam Permissions': 'projects_locations-lakes-contentitems-test-iam-permissions.md'
    - 'Locations Lakes Create': 'projects_locations-lakes-create.md'
    - 'Locations Lakes Delete': 'projects_locations-lakes-delete.md'
    - 'Locations Lakes Environments Create': 'projects_locations-lakes-environments-create.md'
    - 'Locations Lakes Environments Delete': 'projects_locations-lakes-environments-delete.md'
    - 'Locations Lakes Environments Get': 'projects_locations-lakes-environments-get.md'
    - 'Locations Lakes Environments Get Iam Policy': 'projects_locations-lakes-environments-get-iam-policy.md'
    - 'Locations Lakes Environments List': 'projects_locations-lakes-environments-list.md'
    - 'Locations Lakes Environments Patch': 'projects_locations-lakes-environments-patch.md'
    - 'Locations Lakes Environments Sessions List': 'projects_locations-lakes-environments-sessions-list.md'
    - 'Locations Lakes Environments Set Iam Policy': 'projects_locations-lakes-environments-set-iam-policy.md'
    - 'Locations Lakes Environments Test Iam Permissions': 'projects_locations-lakes-environments-test-iam-permissions.md'
    - 'Locations Lakes Get': 'projects_locations-lakes-get.md'
    - 'Locations Lakes Get Iam Policy': 'projects_locations-lakes-get-iam-policy.md'
    - 'Locations Lakes List': 'projects_locations-lakes-list.md'
    - 'Locations Lakes Patch': 'projects_locations-lakes-patch.md'
    - 'Locations Lakes Set Iam Policy': 'projects_locations-lakes-set-iam-policy.md'
    - 'Locations Lakes Tasks Create': 'projects_locations-lakes-tasks-create.md'
    - 'Locations Lakes Tasks Delete': 'projects_locations-lakes-tasks-delete.md'
    - 'Locations Lakes Tasks Get': 'projects_locations-lakes-tasks-get.md'
    - 'Locations Lakes Tasks Get Iam Policy': 'projects_locations-lakes-tasks-get-iam-policy.md'
    - 'Locations Lakes Tasks Jobs Cancel': 'projects_locations-lakes-tasks-jobs-cancel.md'
    - 'Locations Lakes Tasks Jobs Get': 'projects_locations-lakes-tasks-jobs-get.md'
    - 'Locations Lakes Tasks Jobs List': 'projects_locations-lakes-tasks-jobs-list.md'
    - 'Locations Lakes Tasks List': 'projects_locations-lakes-tasks-list.md'
    - 'Locations Lakes Tasks Patch': 'projects_locations-lakes-tasks-patch.md'
    - 'Locations Lakes Tasks Run': 'projects_locations-lakes-tasks-run.md'
    - 'Locations Lakes Tasks Set Iam Policy': 'projects_locations-lakes-tasks-set-iam-policy.md'
    - 'Locations Lakes Tasks Test Iam Permissions': 'projects_locations-lakes-tasks-test-iam-permissions.md'
    - 'Locations Lakes Test Iam Permissions': 'projects_locations-lakes-test-iam-permissions.md'
    - 'Locations Lakes Zones Actions List': 'projects_locations-lakes-zones-actions-list.md'
    - 'Locations Lakes Zones Assets Actions List': 'projects_locations-lakes-zones-assets-actions-list.md'
    - 'Locations Lakes Zones Assets Create': 'projects_locations-lakes-zones-assets-create.md'
    - 'Locations Lakes Zones Assets Delete': 'projects_locations-lakes-zones-assets-delete.md'
    - 'Locations Lakes Zones Assets Get': 'projects_locations-lakes-zones-assets-get.md'
    - 'Locations Lakes Zones Assets Get Iam Policy': 'projects_locations-lakes-zones-assets-get-iam-policy.md'
    - 'Locations Lakes Zones Assets List': 'projects_locations-lakes-zones-assets-list.md'
    - 'Locations Lakes Zones Assets Patch': 'projects_locations-lakes-zones-assets-patch.md'
    - 'Locations Lakes Zones Assets Set Iam Policy': 'projects_locations-lakes-zones-assets-set-iam-policy.md'
    - 'Locations Lakes Zones Assets Test Iam Permissions': 'projects_locations-lakes-zones-assets-test-iam-permissions.md'
    - 'Locations Lakes Zones Create': 'projects_locations-lakes-zones-create.md'
    - 'Locations Lakes Zones Delete': 'projects_locations-lakes-zones-delete.md'
    - 'Locations Lakes Zones Entities Create': 'projects_locations-lakes-zones-entities-create.md'
    - 'Locations Lakes Zones Entities Delete': 'projects_locations-lakes-zones-entities-delete.md'
    - 'Locations Lakes Zones Entities Get': 'projects_locations-lakes-zones-entities-get.md'
    - 'Locations Lakes Zones Entities List': 'projects_locations-lakes-zones-entities-list.md'
    - 'Locations Lakes Zones Entities Partitions Create': 'projects_locations-lakes-zones-entities-partitions-create.md'
    - 'Locations Lakes Zones Entities Partitions Delete': 'projects_locations-lakes-zones-entities-partitions-delete.md'
    - 'Locations Lakes Zones Entities Partitions Get': 'projects_locations-lakes-zones-entities-partitions-get.md'
    - 'Locations Lakes Zones Entities Partitions List': 'projects_locations-lakes-zones-entities-partitions-list.md'
    - 'Locations Lakes Zones Entities Update': 'projects_locations-lakes-zones-entities-update.md'
    - 'Locations Lakes Zones Get': 'projects_locations-lakes-zones-get.md'
    - 'Locations Lakes Zones Get Iam Policy': 'projects_locations-lakes-zones-get-iam-policy.md'
    - 'Locations Lakes Zones List': 'projects_locations-lakes-zones-list.md'
    - 'Locations Lakes Zones Patch': 'projects_locations-lakes-zones-patch.md'
    - 'Locations Lakes Zones Set Iam Policy': 'projects_locations-lakes-zones-set-iam-policy.md'
    - 'Locations Lakes Zones Test Iam Permissions': 'projects_locations-lakes-zones-test-iam-permissions.md'
    - 'Locations List': 'projects_locations-list.md'
    - 'Locations Lookup Entry': 'projects_locations-lookup-entry.md'
    - 'Locations Operations Cancel': 'projects_locations-operations-cancel.md'
    - 'Locations Operations Delete': 'projects_locations-operations-delete.md'
    - 'Locations Operations Get': 'projects_locations-operations-get.md'
    - 'Locations Operations List': 'projects_locations-operations-list.md'
    - 'Locations Search Entries': 'projects_locations-search-entries.md'

theme: readthedocs

copyright: Copyright &copy; 2015â€“2024, `Sebastian Thiel`

