site_name: Vision v3.0.0+20220225
site_url: http://byron.github.io/google-apis-rs/google-vision1-cli
site_description: A complete library to interact with Vision (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/vision1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['files_annotate.md', 'Files', 'Annotate']
- ['files_async-batch-annotate.md', 'Files', 'Async Batch Annotate']
- ['images_annotate.md', 'Images', 'Annotate']
- ['images_async-batch-annotate.md', 'Images', 'Async Batch Annotate']
- ['locations_operations-get.md', 'Locations', 'Operations Get']
- ['operations_cancel.md', 'Operations', 'Cancel']
- ['operations_delete.md', 'Operations', 'Delete']
- ['operations_get.md', 'Operations', 'Get']
- ['operations_list.md', 'Operations', 'List']
- ['projects_files-annotate.md', 'Projects', 'Files Annotate']
- ['projects_files-async-batch-annotate.md', 'Projects', 'Files Async Batch Annotate']
- ['projects_images-annotate.md', 'Projects', 'Images Annotate']
- ['projects_images-async-batch-annotate.md', 'Projects', 'Images Async Batch Annotate']
- ['projects_locations-files-annotate.md', 'Projects', 'Locations Files Annotate']
- ['projects_locations-files-async-batch-annotate.md', 'Projects', 'Locations Files Async Batch Annotate']
- ['projects_locations-images-annotate.md', 'Projects', 'Locations Images Annotate']
- ['projects_locations-images-async-batch-annotate.md', 'Projects', 'Locations Images Async Batch Annotate']
- ['projects_locations-operations-get.md', 'Projects', 'Locations Operations Get']
- ['projects_locations-product-sets-add-product.md', 'Projects', 'Locations Product Sets Add Product']
- ['projects_locations-product-sets-create.md', 'Projects', 'Locations Product Sets Create']
- ['projects_locations-product-sets-delete.md', 'Projects', 'Locations Product Sets Delete']
- ['projects_locations-product-sets-get.md', 'Projects', 'Locations Product Sets Get']
- ['projects_locations-product-sets-import.md', 'Projects', 'Locations Product Sets Import']
- ['projects_locations-product-sets-list.md', 'Projects', 'Locations Product Sets List']
- ['projects_locations-product-sets-patch.md', 'Projects', 'Locations Product Sets Patch']
- ['projects_locations-product-sets-products-list.md', 'Projects', 'Locations Product Sets Products List']
- ['projects_locations-product-sets-remove-product.md', 'Projects', 'Locations Product Sets Remove Product']
- ['projects_locations-products-create.md', 'Projects', 'Locations Products Create']
- ['projects_locations-products-delete.md', 'Projects', 'Locations Products Delete']
- ['projects_locations-products-get.md', 'Projects', 'Locations Products Get']
- ['projects_locations-products-list.md', 'Projects', 'Locations Products List']
- ['projects_locations-products-patch.md', 'Projects', 'Locations Products Patch']
- ['projects_locations-products-purge.md', 'Projects', 'Locations Products Purge']
- ['projects_locations-products-reference-images-create.md', 'Projects', 'Locations Products Reference Images Create']
- ['projects_locations-products-reference-images-delete.md', 'Projects', 'Locations Products Reference Images Delete']
- ['projects_locations-products-reference-images-get.md', 'Projects', 'Locations Products Reference Images Get']
- ['projects_locations-products-reference-images-list.md', 'Projects', 'Locations Products Reference Images List']
- ['projects_operations-get.md', 'Projects', 'Operations Get']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

