site_name: Vision v1.0.7+20181001
site_url: http://byron.github.io/google-apis-rs/google-vision1-cli
site_description: A complete library to interact with Vision (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/vision1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['files_async-batch-annotate.md', 'Files', 'Async Batch Annotate']
- ['images_annotate.md', 'Images', 'Annotate']
- ['locations_operations-get.md', 'Locations', 'Operations Get']
- ['operations_cancel.md', 'Operations', 'Cancel']
- ['operations_delete.md', 'Operations', 'Delete']
- ['operations_get.md', 'Operations', 'Get']
- ['operations_list.md', 'Operations', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

