site_name: Security Command Center v5.0.5+20240622
site_url: http://byron.github.io/google-apis-rs/google-securitycenter1-cli
site_description: A complete library to interact with Security Command Center (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/securitycenter1-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Folders':
    - 'Assets Group': 'folders_assets-group.md'
    - 'Assets List': 'folders_assets-list.md'
    - 'Assets Update Security Marks': 'folders_assets-update-security-marks.md'
    - 'Big Query Exports Create': 'folders_big-query-exports-create.md'
    - 'Big Query Exports Delete': 'folders_big-query-exports-delete.md'
    - 'Big Query Exports Get': 'folders_big-query-exports-get.md'
    - 'Big Query Exports List': 'folders_big-query-exports-list.md'
    - 'Big Query Exports Patch': 'folders_big-query-exports-patch.md'
    - 'Event Threat Detection Settings Custom Modules Create': 'folders_event-threat-detection-settings-custom-modules-create.md'
    - 'Event Threat Detection Settings Custom Modules Delete': 'folders_event-threat-detection-settings-custom-modules-delete.md'
    - 'Event Threat Detection Settings Custom Modules Get': 'folders_event-threat-detection-settings-custom-modules-get.md'
    - 'Event Threat Detection Settings Custom Modules List': 'folders_event-threat-detection-settings-custom-modules-list.md'
    - 'Event Threat Detection Settings Custom Modules List Descendant': 'folders_event-threat-detection-settings-custom-modules-list-descendant.md'
    - 'Event Threat Detection Settings Custom Modules Patch': 'folders_event-threat-detection-settings-custom-modules-patch.md'
    - 'Event Threat Detection Settings Effective Custom Modules Get': 'folders_event-threat-detection-settings-effective-custom-modules-get.md'
    - 'Event Threat Detection Settings Effective Custom Modules List': 'folders_event-threat-detection-settings-effective-custom-modules-list.md'
    - 'Event Threat Detection Settings Validate Custom Module': 'folders_event-threat-detection-settings-validate-custom-module.md'
    - 'Findings Bulk Mute': 'folders_findings-bulk-mute.md'
    - 'Locations Mute Configs Create': 'folders_locations-mute-configs-create.md'
    - 'Locations Mute Configs Delete': 'folders_locations-mute-configs-delete.md'
    - 'Locations Mute Configs Get': 'folders_locations-mute-configs-get.md'
    - 'Locations Mute Configs List': 'folders_locations-mute-configs-list.md'
    - 'Locations Mute Configs Patch': 'folders_locations-mute-configs-patch.md'
    - 'Mute Configs Create': 'folders_mute-configs-create.md'
    - 'Mute Configs Delete': 'folders_mute-configs-delete.md'
    - 'Mute Configs Get': 'folders_mute-configs-get.md'
    - 'Mute Configs List': 'folders_mute-configs-list.md'
    - 'Mute Configs Patch': 'folders_mute-configs-patch.md'
    - 'Notification Configs Create': 'folders_notification-configs-create.md'
    - 'Notification Configs Delete': 'folders_notification-configs-delete.md'
    - 'Notification Configs Get': 'folders_notification-configs-get.md'
    - 'Notification Configs List': 'folders_notification-configs-list.md'
    - 'Notification Configs Patch': 'folders_notification-configs-patch.md'
    - 'Security Health Analytics Settings Custom Modules Create': 'folders_security-health-analytics-settings-custom-modules-create.md'
    - 'Security Health Analytics Settings Custom Modules Delete': 'folders_security-health-analytics-settings-custom-modules-delete.md'
    - 'Security Health Analytics Settings Custom Modules Get': 'folders_security-health-analytics-settings-custom-modules-get.md'
    - 'Security Health Analytics Settings Custom Modules List': 'folders_security-health-analytics-settings-custom-modules-list.md'
    - 'Security Health Analytics Settings Custom Modules List Descendant': 'folders_security-health-analytics-settings-custom-modules-list-descendant.md'
    - 'Security Health Analytics Settings Custom Modules Patch': 'folders_security-health-analytics-settings-custom-modules-patch.md'
    - 'Security Health Analytics Settings Custom Modules Simulate': 'folders_security-health-analytics-settings-custom-modules-simulate.md'
    - 'Security Health Analytics Settings Effective Custom Modules Get': 'folders_security-health-analytics-settings-effective-custom-modules-get.md'
    - 'Security Health Analytics Settings Effective Custom Modules List': 'folders_security-health-analytics-settings-effective-custom-modules-list.md'
    - 'Sources Findings External Systems Patch': 'folders_sources-findings-external-systems-patch.md'
    - 'Sources Findings Group': 'folders_sources-findings-group.md'
    - 'Sources Findings List': 'folders_sources-findings-list.md'
    - 'Sources Findings Patch': 'folders_sources-findings-patch.md'
    - 'Sources Findings Set Mute': 'folders_sources-findings-set-mute.md'
    - 'Sources Findings Set State': 'folders_sources-findings-set-state.md'
    - 'Sources Findings Update Security Marks': 'folders_sources-findings-update-security-marks.md'
    - 'Sources List': 'folders_sources-list.md'
- 'Organizations':
    - 'Assets Group': 'organizations_assets-group.md'
    - 'Assets List': 'organizations_assets-list.md'
    - 'Assets Run Discovery': 'organizations_assets-run-discovery.md'
    - 'Assets Update Security Marks': 'organizations_assets-update-security-marks.md'
    - 'Big Query Exports Create': 'organizations_big-query-exports-create.md'
    - 'Big Query Exports Delete': 'organizations_big-query-exports-delete.md'
    - 'Big Query Exports Get': 'organizations_big-query-exports-get.md'
    - 'Big Query Exports List': 'organizations_big-query-exports-list.md'
    - 'Big Query Exports Patch': 'organizations_big-query-exports-patch.md'
    - 'Event Threat Detection Settings Custom Modules Create': 'organizations_event-threat-detection-settings-custom-modules-create.md'
    - 'Event Threat Detection Settings Custom Modules Delete': 'organizations_event-threat-detection-settings-custom-modules-delete.md'
    - 'Event Threat Detection Settings Custom Modules Get': 'organizations_event-threat-detection-settings-custom-modules-get.md'
    - 'Event Threat Detection Settings Custom Modules List': 'organizations_event-threat-detection-settings-custom-modules-list.md'
    - 'Event Threat Detection Settings Custom Modules List Descendant': 'organizations_event-threat-detection-settings-custom-modules-list-descendant.md'
    - 'Event Threat Detection Settings Custom Modules Patch': 'organizations_event-threat-detection-settings-custom-modules-patch.md'
    - 'Event Threat Detection Settings Effective Custom Modules Get': 'organizations_event-threat-detection-settings-effective-custom-modules-get.md'
    - 'Event Threat Detection Settings Effective Custom Modules List': 'organizations_event-threat-detection-settings-effective-custom-modules-list.md'
    - 'Event Threat Detection Settings Validate Custom Module': 'organizations_event-threat-detection-settings-validate-custom-module.md'
    - 'Findings Bulk Mute': 'organizations_findings-bulk-mute.md'
    - 'Get Organization Settings': 'organizations_get-organization-settings.md'
    - 'Locations Mute Configs Create': 'organizations_locations-mute-configs-create.md'
    - 'Locations Mute Configs Delete': 'organizations_locations-mute-configs-delete.md'
    - 'Locations Mute Configs Get': 'organizations_locations-mute-configs-get.md'
    - 'Locations Mute Configs List': 'organizations_locations-mute-configs-list.md'
    - 'Locations Mute Configs Patch': 'organizations_locations-mute-configs-patch.md'
    - 'Mute Configs Create': 'organizations_mute-configs-create.md'
    - 'Mute Configs Delete': 'organizations_mute-configs-delete.md'
    - 'Mute Configs Get': 'organizations_mute-configs-get.md'
    - 'Mute Configs List': 'organizations_mute-configs-list.md'
    - 'Mute Configs Patch': 'organizations_mute-configs-patch.md'
    - 'Notification Configs Create': 'organizations_notification-configs-create.md'
    - 'Notification Configs Delete': 'organizations_notification-configs-delete.md'
    - 'Notification Configs Get': 'organizations_notification-configs-get.md'
    - 'Notification Configs List': 'organizations_notification-configs-list.md'
    - 'Notification Configs Patch': 'organizations_notification-configs-patch.md'
    - 'Operations Cancel': 'organizations_operations-cancel.md'
    - 'Operations Delete': 'organizations_operations-delete.md'
    - 'Operations Get': 'organizations_operations-get.md'
    - 'Operations List': 'organizations_operations-list.md'
    - 'Resource Value Configs Batch Create': 'organizations_resource-value-configs-batch-create.md'
    - 'Resource Value Configs Delete': 'organizations_resource-value-configs-delete.md'
    - 'Resource Value Configs Get': 'organizations_resource-value-configs-get.md'
    - 'Resource Value Configs List': 'organizations_resource-value-configs-list.md'
    - 'Resource Value Configs Patch': 'organizations_resource-value-configs-patch.md'
    - 'Security Health Analytics Settings Custom Modules Create': 'organizations_security-health-analytics-settings-custom-modules-create.md'
    - 'Security Health Analytics Settings Custom Modules Delete': 'organizations_security-health-analytics-settings-custom-modules-delete.md'
    - 'Security Health Analytics Settings Custom Modules Get': 'organizations_security-health-analytics-settings-custom-modules-get.md'
    - 'Security Health Analytics Settings Custom Modules List': 'organizations_security-health-analytics-settings-custom-modules-list.md'
    - 'Security Health Analytics Settings Custom Modules List Descendant': 'organizations_security-health-analytics-settings-custom-modules-list-descendant.md'
    - 'Security Health Analytics Settings Custom Modules Patch': 'organizations_security-health-analytics-settings-custom-modules-patch.md'
    - 'Security Health Analytics Settings Custom Modules Simulate': 'organizations_security-health-analytics-settings-custom-modules-simulate.md'
    - 'Security Health Analytics Settings Effective Custom Modules Get': 'organizations_security-health-analytics-settings-effective-custom-modules-get.md'
    - 'Security Health Analytics Settings Effective Custom Modules List': 'organizations_security-health-analytics-settings-effective-custom-modules-list.md'
    - 'Simulations Attack Exposure Results Attack Paths List': 'organizations_simulations-attack-exposure-results-attack-paths-list.md'
    - 'Simulations Attack Exposure Results Valued Resources List': 'organizations_simulations-attack-exposure-results-valued-resources-list.md'
    - 'Simulations Attack Paths List': 'organizations_simulations-attack-paths-list.md'
    - 'Simulations Get': 'organizations_simulations-get.md'
    - 'Simulations Valued Resources Attack Paths List': 'organizations_simulations-valued-resources-attack-paths-list.md'
    - 'Simulations Valued Resources Get': 'organizations_simulations-valued-resources-get.md'
    - 'Simulations Valued Resources List': 'organizations_simulations-valued-resources-list.md'
    - 'Sources Create': 'organizations_sources-create.md'
    - 'Sources Findings Create': 'organizations_sources-findings-create.md'
    - 'Sources Findings External Systems Patch': 'organizations_sources-findings-external-systems-patch.md'
    - 'Sources Findings Group': 'organizations_sources-findings-group.md'
    - 'Sources Findings List': 'organizations_sources-findings-list.md'
    - 'Sources Findings Patch': 'organizations_sources-findings-patch.md'
    - 'Sources Findings Set Mute': 'organizations_sources-findings-set-mute.md'
    - 'Sources Findings Set State': 'organizations_sources-findings-set-state.md'
    - 'Sources Findings Update Security Marks': 'organizations_sources-findings-update-security-marks.md'
    - 'Sources Get': 'organizations_sources-get.md'
    - 'Sources Get Iam Policy': 'organizations_sources-get-iam-policy.md'
    - 'Sources List': 'organizations_sources-list.md'
    - 'Sources Patch': 'organizations_sources-patch.md'
    - 'Sources Set Iam Policy': 'organizations_sources-set-iam-policy.md'
    - 'Sources Test Iam Permissions': 'organizations_sources-test-iam-permissions.md'
    - 'Update Organization Settings': 'organizations_update-organization-settings.md'
- 'Projects':
    - 'Assets Group': 'projects_assets-group.md'
    - 'Assets List': 'projects_assets-list.md'
    - 'Assets Update Security Marks': 'projects_assets-update-security-marks.md'
    - 'Big Query Exports Create': 'projects_big-query-exports-create.md'
    - 'Big Query Exports Delete': 'projects_big-query-exports-delete.md'
    - 'Big Query Exports Get': 'projects_big-query-exports-get.md'
    - 'Big Query Exports List': 'projects_big-query-exports-list.md'
    - 'Big Query Exports Patch': 'projects_big-query-exports-patch.md'
    - 'Event Threat Detection Settings Custom Modules Create': 'projects_event-threat-detection-settings-custom-modules-create.md'
    - 'Event Threat Detection Settings Custom Modules Delete': 'projects_event-threat-detection-settings-custom-modules-delete.md'
    - 'Event Threat Detection Settings Custom Modules Get': 'projects_event-threat-detection-settings-custom-modules-get.md'
    - 'Event Threat Detection Settings Custom Modules List': 'projects_event-threat-detection-settings-custom-modules-list.md'
    - 'Event Threat Detection Settings Custom Modules List Descendant': 'projects_event-threat-detection-settings-custom-modules-list-descendant.md'
    - 'Event Threat Detection Settings Custom Modules Patch': 'projects_event-threat-detection-settings-custom-modules-patch.md'
    - 'Event Threat Detection Settings Effective Custom Modules Get': 'projects_event-threat-detection-settings-effective-custom-modules-get.md'
    - 'Event Threat Detection Settings Effective Custom Modules List': 'projects_event-threat-detection-settings-effective-custom-modules-list.md'
    - 'Event Threat Detection Settings Validate Custom Module': 'projects_event-threat-detection-settings-validate-custom-module.md'
    - 'Findings Bulk Mute': 'projects_findings-bulk-mute.md'
    - 'Locations Mute Configs Create': 'projects_locations-mute-configs-create.md'
    - 'Locations Mute Configs Delete': 'projects_locations-mute-configs-delete.md'
    - 'Locations Mute Configs Get': 'projects_locations-mute-configs-get.md'
    - 'Locations Mute Configs List': 'projects_locations-mute-configs-list.md'
    - 'Locations Mute Configs Patch': 'projects_locations-mute-configs-patch.md'
    - 'Mute Configs Create': 'projects_mute-configs-create.md'
    - 'Mute Configs Delete': 'projects_mute-configs-delete.md'
    - 'Mute Configs Get': 'projects_mute-configs-get.md'
    - 'Mute Configs List': 'projects_mute-configs-list.md'
    - 'Mute Configs Patch': 'projects_mute-configs-patch.md'
    - 'Notification Configs Create': 'projects_notification-configs-create.md'
    - 'Notification Configs Delete': 'projects_notification-configs-delete.md'
    - 'Notification Configs Get': 'projects_notification-configs-get.md'
    - 'Notification Configs List': 'projects_notification-configs-list.md'
    - 'Notification Configs Patch': 'projects_notification-configs-patch.md'
    - 'Security Health Analytics Settings Custom Modules Create': 'projects_security-health-analytics-settings-custom-modules-create.md'
    - 'Security Health Analytics Settings Custom Modules Delete': 'projects_security-health-analytics-settings-custom-modules-delete.md'
    - 'Security Health Analytics Settings Custom Modules Get': 'projects_security-health-analytics-settings-custom-modules-get.md'
    - 'Security Health Analytics Settings Custom Modules List': 'projects_security-health-analytics-settings-custom-modules-list.md'
    - 'Security Health Analytics Settings Custom Modules List Descendant': 'projects_security-health-analytics-settings-custom-modules-list-descendant.md'
    - 'Security Health Analytics Settings Custom Modules Patch': 'projects_security-health-analytics-settings-custom-modules-patch.md'
    - 'Security Health Analytics Settings Custom Modules Simulate': 'projects_security-health-analytics-settings-custom-modules-simulate.md'
    - 'Security Health Analytics Settings Effective Custom Modules Get': 'projects_security-health-analytics-settings-effective-custom-modules-get.md'
    - 'Security Health Analytics Settings Effective Custom Modules List': 'projects_security-health-analytics-settings-effective-custom-modules-list.md'
    - 'Sources Findings External Systems Patch': 'projects_sources-findings-external-systems-patch.md'
    - 'Sources Findings Group': 'projects_sources-findings-group.md'
    - 'Sources Findings List': 'projects_sources-findings-list.md'
    - 'Sources Findings Patch': 'projects_sources-findings-patch.md'
    - 'Sources Findings Set Mute': 'projects_sources-findings-set-mute.md'
    - 'Sources Findings Set State': 'projects_sources-findings-set-state.md'
    - 'Sources Findings Update Security Marks': 'projects_sources-findings-update-security-marks.md'
    - 'Sources List': 'projects_sources-list.md'

theme: readthedocs

copyright: Copyright &copy; 2015â€“2024, `Sebastian Thiel`

