site_name: Cloud RuntimeConfig v1.0.7+20180924
site_url: http://byron.github.io/google-apis-rs/google-runtimeconfig1-cli
site_description: A complete library to interact with Cloud RuntimeConfig (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/runtimeconfig1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['operations_cancel.md', 'Operations', 'Cancel']
- ['operations_delete.md', 'Operations', 'Delete']
- ['operations_list.md', 'Operations', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

