site_name: Network Management v7.0.0+20251203
site_url: http://byron.github.io/google-apis-rs/google-networkmanagement1-cli
site_description: A complete library to interact with Network Management (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/networkmanagement1-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Organizations':
    - 'Locations Get': 'organizations_locations-get.md'
    - 'Locations List': 'organizations_locations-list.md'
    - 'Locations Operations Cancel': 'organizations_locations-operations-cancel.md'
    - 'Locations Operations Delete': 'organizations_locations-operations-delete.md'
    - 'Locations Operations Get': 'organizations_locations-operations-get.md'
    - 'Locations Operations List': 'organizations_locations-operations-list.md'
    - 'Locations Vpc Flow Logs Configs Create': 'organizations_locations-vpc-flow-logs-configs-create.md'
    - 'Locations Vpc Flow Logs Configs Delete': 'organizations_locations-vpc-flow-logs-configs-delete.md'
    - 'Locations Vpc Flow Logs Configs Get': 'organizations_locations-vpc-flow-logs-configs-get.md'
    - 'Locations Vpc Flow Logs Configs List': 'organizations_locations-vpc-flow-logs-configs-list.md'
    - 'Locations Vpc Flow Logs Configs Patch': 'organizations_locations-vpc-flow-logs-configs-patch.md'
- 'Projects':
    - 'Locations Get': 'projects_locations-get.md'
    - 'Locations Global Connectivity Tests Create': 'projects_locations-global-connectivity-tests-create.md'
    - 'Locations Global Connectivity Tests Delete': 'projects_locations-global-connectivity-tests-delete.md'
    - 'Locations Global Connectivity Tests Get': 'projects_locations-global-connectivity-tests-get.md'
    - 'Locations Global Connectivity Tests Get Iam Policy': 'projects_locations-global-connectivity-tests-get-iam-policy.md'
    - 'Locations Global Connectivity Tests List': 'projects_locations-global-connectivity-tests-list.md'
    - 'Locations Global Connectivity Tests Patch': 'projects_locations-global-connectivity-tests-patch.md'
    - 'Locations Global Connectivity Tests Rerun': 'projects_locations-global-connectivity-tests-rerun.md'
    - 'Locations Global Connectivity Tests Set Iam Policy': 'projects_locations-global-connectivity-tests-set-iam-policy.md'
    - 'Locations Global Connectivity Tests Test Iam Permissions': 'projects_locations-global-connectivity-tests-test-iam-permissions.md'
    - 'Locations Global Operations Cancel': 'projects_locations-global-operations-cancel.md'
    - 'Locations Global Operations Delete': 'projects_locations-global-operations-delete.md'
    - 'Locations Global Operations Get': 'projects_locations-global-operations-get.md'
    - 'Locations Global Operations List': 'projects_locations-global-operations-list.md'
    - 'Locations List': 'projects_locations-list.md'
    - 'Locations Vpc Flow Logs Configs Create': 'projects_locations-vpc-flow-logs-configs-create.md'
    - 'Locations Vpc Flow Logs Configs Delete': 'projects_locations-vpc-flow-logs-configs-delete.md'
    - 'Locations Vpc Flow Logs Configs Get': 'projects_locations-vpc-flow-logs-configs-get.md'
    - 'Locations Vpc Flow Logs Configs List': 'projects_locations-vpc-flow-logs-configs-list.md'
    - 'Locations Vpc Flow Logs Configs Patch': 'projects_locations-vpc-flow-logs-configs-patch.md'
    - 'Locations Vpc Flow Logs Configs Query Org Vpc Flow Logs Configs': 'projects_locations-vpc-flow-logs-configs-query-org-vpc-flow-logs-configs.md'
    - 'Locations Vpc Flow Logs Configs Show Effective Flow Logs Configs': 'projects_locations-vpc-flow-logs-configs-show-effective-flow-logs-configs.md'

theme: readthedocs

copyright: Copyright &copy; 2015â€“2024, `Sebastian Thiel`
