site_name: groupssettings v0.3.0+20140428
site_url: http://byron.github.io/google-apis-rs/google-groupssettings1-cli
site_description: Write integrating applications with bcore

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/groupssettings1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['groups_get.md', 'Groups', 'Get']
- ['groups_patch.md', 'Groups', 'Patch']
- ['groups_update.md', 'Groups', 'Update']

theme: readthedocs

copyright: Copyright &copy; 2015, `Sebastian Thiel`

