site_name: Manufacturer Center v1.0.7+20180919
site_url: http://byron.github.io/google-apis-rs/google-manufacturers1-cli
site_description: A complete library to interact with Manufacturer Center (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/manufacturers1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['accounts_products-delete.md', 'Accounts', 'Products Delete']
- ['accounts_products-get.md', 'Accounts', 'Products Get']
- ['accounts_products-list.md', 'Accounts', 'Products List']
- ['accounts_products-update.md', 'Accounts', 'Products Update']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

