site_name: DLP v5.0.5+20240616
site_url: http://byron.github.io/google-apis-rs/google-dlp2-cli
site_description: A complete library to interact with DLP (protocol v2)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/dlp2-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Info Types':
    - 'List': 'info-types_list.md'
- 'Locations':
    - 'Info Types List': 'locations_info-types-list.md'
- 'Organizations':
    - 'Deidentify Templates Create': 'organizations_deidentify-templates-create.md'
    - 'Deidentify Templates Delete': 'organizations_deidentify-templates-delete.md'
    - 'Deidentify Templates Get': 'organizations_deidentify-templates-get.md'
    - 'Deidentify Templates List': 'organizations_deidentify-templates-list.md'
    - 'Deidentify Templates Patch': 'organizations_deidentify-templates-patch.md'
    - 'Inspect Templates Create': 'organizations_inspect-templates-create.md'
    - 'Inspect Templates Delete': 'organizations_inspect-templates-delete.md'
    - 'Inspect Templates Get': 'organizations_inspect-templates-get.md'
    - 'Inspect Templates List': 'organizations_inspect-templates-list.md'
    - 'Inspect Templates Patch': 'organizations_inspect-templates-patch.md'
    - 'Locations Column Data Profiles Get': 'organizations_locations-column-data-profiles-get.md'
    - 'Locations Column Data Profiles List': 'organizations_locations-column-data-profiles-list.md'
    - 'Locations Connections Create': 'organizations_locations-connections-create.md'
    - 'Locations Connections Delete': 'organizations_locations-connections-delete.md'
    - 'Locations Connections Get': 'organizations_locations-connections-get.md'
    - 'Locations Connections Patch': 'organizations_locations-connections-patch.md'
    - 'Locations Connections Search': 'organizations_locations-connections-search.md'
    - 'Locations Deidentify Templates Create': 'organizations_locations-deidentify-templates-create.md'
    - 'Locations Deidentify Templates Delete': 'organizations_locations-deidentify-templates-delete.md'
    - 'Locations Deidentify Templates Get': 'organizations_locations-deidentify-templates-get.md'
    - 'Locations Deidentify Templates List': 'organizations_locations-deidentify-templates-list.md'
    - 'Locations Deidentify Templates Patch': 'organizations_locations-deidentify-templates-patch.md'
    - 'Locations Discovery Configs Create': 'organizations_locations-discovery-configs-create.md'
    - 'Locations Discovery Configs Delete': 'organizations_locations-discovery-configs-delete.md'
    - 'Locations Discovery Configs Get': 'organizations_locations-discovery-configs-get.md'
    - 'Locations Discovery Configs List': 'organizations_locations-discovery-configs-list.md'
    - 'Locations Discovery Configs Patch': 'organizations_locations-discovery-configs-patch.md'
    - 'Locations Dlp Jobs List': 'organizations_locations-dlp-jobs-list.md'
    - 'Locations Inspect Templates Create': 'organizations_locations-inspect-templates-create.md'
    - 'Locations Inspect Templates Delete': 'organizations_locations-inspect-templates-delete.md'
    - 'Locations Inspect Templates Get': 'organizations_locations-inspect-templates-get.md'
    - 'Locations Inspect Templates List': 'organizations_locations-inspect-templates-list.md'
    - 'Locations Inspect Templates Patch': 'organizations_locations-inspect-templates-patch.md'
    - 'Locations Job Triggers Create': 'organizations_locations-job-triggers-create.md'
    - 'Locations Job Triggers Delete': 'organizations_locations-job-triggers-delete.md'
    - 'Locations Job Triggers Get': 'organizations_locations-job-triggers-get.md'
    - 'Locations Job Triggers List': 'organizations_locations-job-triggers-list.md'
    - 'Locations Job Triggers Patch': 'organizations_locations-job-triggers-patch.md'
    - 'Locations Project Data Profiles Get': 'organizations_locations-project-data-profiles-get.md'
    - 'Locations Project Data Profiles List': 'organizations_locations-project-data-profiles-list.md'
    - 'Locations Stored Info Types Create': 'organizations_locations-stored-info-types-create.md'
    - 'Locations Stored Info Types Delete': 'organizations_locations-stored-info-types-delete.md'
    - 'Locations Stored Info Types Get': 'organizations_locations-stored-info-types-get.md'
    - 'Locations Stored Info Types List': 'organizations_locations-stored-info-types-list.md'
    - 'Locations Stored Info Types Patch': 'organizations_locations-stored-info-types-patch.md'
    - 'Locations Table Data Profiles Delete': 'organizations_locations-table-data-profiles-delete.md'
    - 'Locations Table Data Profiles Get': 'organizations_locations-table-data-profiles-get.md'
    - 'Locations Table Data Profiles List': 'organizations_locations-table-data-profiles-list.md'
    - 'Stored Info Types Create': 'organizations_stored-info-types-create.md'
    - 'Stored Info Types Delete': 'organizations_stored-info-types-delete.md'
    - 'Stored Info Types Get': 'organizations_stored-info-types-get.md'
    - 'Stored Info Types List': 'organizations_stored-info-types-list.md'
    - 'Stored Info Types Patch': 'organizations_stored-info-types-patch.md'
- 'Projects':
    - 'Content Deidentify': 'projects_content-deidentify.md'
    - 'Content Inspect': 'projects_content-inspect.md'
    - 'Content Reidentify': 'projects_content-reidentify.md'
    - 'Deidentify Templates Create': 'projects_deidentify-templates-create.md'
    - 'Deidentify Templates Delete': 'projects_deidentify-templates-delete.md'
    - 'Deidentify Templates Get': 'projects_deidentify-templates-get.md'
    - 'Deidentify Templates List': 'projects_deidentify-templates-list.md'
    - 'Deidentify Templates Patch': 'projects_deidentify-templates-patch.md'
    - 'Dlp Jobs Cancel': 'projects_dlp-jobs-cancel.md'
    - 'Dlp Jobs Create': 'projects_dlp-jobs-create.md'
    - 'Dlp Jobs Delete': 'projects_dlp-jobs-delete.md'
    - 'Dlp Jobs Get': 'projects_dlp-jobs-get.md'
    - 'Dlp Jobs List': 'projects_dlp-jobs-list.md'
    - 'Image Redact': 'projects_image-redact.md'
    - 'Inspect Templates Create': 'projects_inspect-templates-create.md'
    - 'Inspect Templates Delete': 'projects_inspect-templates-delete.md'
    - 'Inspect Templates Get': 'projects_inspect-templates-get.md'
    - 'Inspect Templates List': 'projects_inspect-templates-list.md'
    - 'Inspect Templates Patch': 'projects_inspect-templates-patch.md'
    - 'Job Triggers Activate': 'projects_job-triggers-activate.md'
    - 'Job Triggers Create': 'projects_job-triggers-create.md'
    - 'Job Triggers Delete': 'projects_job-triggers-delete.md'
    - 'Job Triggers Get': 'projects_job-triggers-get.md'
    - 'Job Triggers List': 'projects_job-triggers-list.md'
    - 'Job Triggers Patch': 'projects_job-triggers-patch.md'
    - 'Locations Column Data Profiles Get': 'projects_locations-column-data-profiles-get.md'
    - 'Locations Column Data Profiles List': 'projects_locations-column-data-profiles-list.md'
    - 'Locations Connections Create': 'projects_locations-connections-create.md'
    - 'Locations Connections Delete': 'projects_locations-connections-delete.md'
    - 'Locations Connections Get': 'projects_locations-connections-get.md'
    - 'Locations Connections List': 'projects_locations-connections-list.md'
    - 'Locations Connections Patch': 'projects_locations-connections-patch.md'
    - 'Locations Connections Search': 'projects_locations-connections-search.md'
    - 'Locations Content Deidentify': 'projects_locations-content-deidentify.md'
    - 'Locations Content Inspect': 'projects_locations-content-inspect.md'
    - 'Locations Content Reidentify': 'projects_locations-content-reidentify.md'
    - 'Locations Deidentify Templates Create': 'projects_locations-deidentify-templates-create.md'
    - 'Locations Deidentify Templates Delete': 'projects_locations-deidentify-templates-delete.md'
    - 'Locations Deidentify Templates Get': 'projects_locations-deidentify-templates-get.md'
    - 'Locations Deidentify Templates List': 'projects_locations-deidentify-templates-list.md'
    - 'Locations Deidentify Templates Patch': 'projects_locations-deidentify-templates-patch.md'
    - 'Locations Discovery Configs Create': 'projects_locations-discovery-configs-create.md'
    - 'Locations Discovery Configs Delete': 'projects_locations-discovery-configs-delete.md'
    - 'Locations Discovery Configs Get': 'projects_locations-discovery-configs-get.md'
    - 'Locations Discovery Configs List': 'projects_locations-discovery-configs-list.md'
    - 'Locations Discovery Configs Patch': 'projects_locations-discovery-configs-patch.md'
    - 'Locations Dlp Jobs Cancel': 'projects_locations-dlp-jobs-cancel.md'
    - 'Locations Dlp Jobs Create': 'projects_locations-dlp-jobs-create.md'
    - 'Locations Dlp Jobs Delete': 'projects_locations-dlp-jobs-delete.md'
    - 'Locations Dlp Jobs Finish': 'projects_locations-dlp-jobs-finish.md'
    - 'Locations Dlp Jobs Get': 'projects_locations-dlp-jobs-get.md'
    - 'Locations Dlp Jobs Hybrid Inspect': 'projects_locations-dlp-jobs-hybrid-inspect.md'
    - 'Locations Dlp Jobs List': 'projects_locations-dlp-jobs-list.md'
    - 'Locations Image Redact': 'projects_locations-image-redact.md'
    - 'Locations Inspect Templates Create': 'projects_locations-inspect-templates-create.md'
    - 'Locations Inspect Templates Delete': 'projects_locations-inspect-templates-delete.md'
    - 'Locations Inspect Templates Get': 'projects_locations-inspect-templates-get.md'
    - 'Locations Inspect Templates List': 'projects_locations-inspect-templates-list.md'
    - 'Locations Inspect Templates Patch': 'projects_locations-inspect-templates-patch.md'
    - 'Locations Job Triggers Activate': 'projects_locations-job-triggers-activate.md'
    - 'Locations Job Triggers Create': 'projects_locations-job-triggers-create.md'
    - 'Locations Job Triggers Delete': 'projects_locations-job-triggers-delete.md'
    - 'Locations Job Triggers Get': 'projects_locations-job-triggers-get.md'
    - 'Locations Job Triggers Hybrid Inspect': 'projects_locations-job-triggers-hybrid-inspect.md'
    - 'Locations Job Triggers List': 'projects_locations-job-triggers-list.md'
    - 'Locations Job Triggers Patch': 'projects_locations-job-triggers-patch.md'
    - 'Locations Project Data Profiles Get': 'projects_locations-project-data-profiles-get.md'
    - 'Locations Project Data Profiles List': 'projects_locations-project-data-profiles-list.md'
    - 'Locations Stored Info Types Create': 'projects_locations-stored-info-types-create.md'
    - 'Locations Stored Info Types Delete': 'projects_locations-stored-info-types-delete.md'
    - 'Locations Stored Info Types Get': 'projects_locations-stored-info-types-get.md'
    - 'Locations Stored Info Types List': 'projects_locations-stored-info-types-list.md'
    - 'Locations Stored Info Types Patch': 'projects_locations-stored-info-types-patch.md'
    - 'Locations Table Data Profiles Delete': 'projects_locations-table-data-profiles-delete.md'
    - 'Locations Table Data Profiles Get': 'projects_locations-table-data-profiles-get.md'
    - 'Locations Table Data Profiles List': 'projects_locations-table-data-profiles-list.md'
    - 'Stored Info Types Create': 'projects_stored-info-types-create.md'
    - 'Stored Info Types Delete': 'projects_stored-info-types-delete.md'
    - 'Stored Info Types Get': 'projects_stored-info-types-get.md'
    - 'Stored Info Types List': 'projects_stored-info-types-list.md'
    - 'Stored Info Types Patch': 'projects_stored-info-types-patch.md'

theme: readthedocs

copyright: Copyright &copy; 2015â€“2024, `Sebastian Thiel`

