site_name: Localservices v3.0.0+20220305
site_url: http://byron.github.io/google-apis-rs/google-localservices1-cli
site_description: A complete library to interact with Localservices (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/localservices1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['account-reports_search.md', 'Account Reports', 'Search']
- ['detailed-lead-reports_search.md', 'Detailed Lead Reports', 'Search']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

