site_name: gmail v1.0.7+20180904
site_url: http://byron.github.io/google-apis-rs/google-gmail1-cli
site_description: A complete library to interact with gmail (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/gmail1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['users_drafts-create.md', 'Users', 'Drafts Create']
- ['users_drafts-delete.md', 'Users', 'Drafts Delete']
- ['users_drafts-get.md', 'Users', 'Drafts Get']
- ['users_drafts-list.md', 'Users', 'Drafts List']
- ['users_drafts-send.md', 'Users', 'Drafts Send']
- ['users_drafts-update.md', 'Users', 'Drafts Update']
- ['users_get-profile.md', 'Users', 'Get Profile']
- ['users_history-list.md', 'Users', 'History List']
- ['users_labels-create.md', 'Users', 'Labels Create']
- ['users_labels-delete.md', 'Users', 'Labels Delete']
- ['users_labels-get.md', 'Users', 'Labels Get']
- ['users_labels-list.md', 'Users', 'Labels List']
- ['users_labels-patch.md', 'Users', 'Labels Patch']
- ['users_labels-update.md', 'Users', 'Labels Update']
- ['users_messages-attachments-get.md', 'Users', 'Messages Attachments Get']
- ['users_messages-batch-delete.md', 'Users', 'Messages Batch Delete']
- ['users_messages-batch-modify.md', 'Users', 'Messages Batch Modify']
- ['users_messages-delete.md', 'Users', 'Messages Delete']
- ['users_messages-get.md', 'Users', 'Messages Get']
- ['users_messages-import.md', 'Users', 'Messages Import']
- ['users_messages-insert.md', 'Users', 'Messages Insert']
- ['users_messages-list.md', 'Users', 'Messages List']
- ['users_messages-modify.md', 'Users', 'Messages Modify']
- ['users_messages-send.md', 'Users', 'Messages Send']
- ['users_messages-trash.md', 'Users', 'Messages Trash']
- ['users_messages-untrash.md', 'Users', 'Messages Untrash']
- ['users_settings-delegates-create.md', 'Users', 'Settings Delegates Create']
- ['users_settings-delegates-delete.md', 'Users', 'Settings Delegates Delete']
- ['users_settings-delegates-get.md', 'Users', 'Settings Delegates Get']
- ['users_settings-delegates-list.md', 'Users', 'Settings Delegates List']
- ['users_settings-filters-create.md', 'Users', 'Settings Filters Create']
- ['users_settings-filters-delete.md', 'Users', 'Settings Filters Delete']
- ['users_settings-filters-get.md', 'Users', 'Settings Filters Get']
- ['users_settings-filters-list.md', 'Users', 'Settings Filters List']
- ['users_settings-forwarding-addresses-create.md', 'Users', 'Settings Forwarding Addresses Create']
- ['users_settings-forwarding-addresses-delete.md', 'Users', 'Settings Forwarding Addresses Delete']
- ['users_settings-forwarding-addresses-get.md', 'Users', 'Settings Forwarding Addresses Get']
- ['users_settings-forwarding-addresses-list.md', 'Users', 'Settings Forwarding Addresses List']
- ['users_settings-get-auto-forwarding.md', 'Users', 'Settings Get Auto Forwarding']
- ['users_settings-get-imap.md', 'Users', 'Settings Get Imap']
- ['users_settings-get-pop.md', 'Users', 'Settings Get Pop']
- ['users_settings-get-vacation.md', 'Users', 'Settings Get Vacation']
- ['users_settings-send-as-create.md', 'Users', 'Settings Send As Create']
- ['users_settings-send-as-delete.md', 'Users', 'Settings Send As Delete']
- ['users_settings-send-as-get.md', 'Users', 'Settings Send As Get']
- ['users_settings-send-as-list.md', 'Users', 'Settings Send As List']
- ['users_settings-send-as-patch.md', 'Users', 'Settings Send As Patch']
- ['users_settings-send-as-smime-info-delete.md', 'Users', 'Settings Send As Smime Info Delete']
- ['users_settings-send-as-smime-info-get.md', 'Users', 'Settings Send As Smime Info Get']
- ['users_settings-send-as-smime-info-insert.md', 'Users', 'Settings Send As Smime Info Insert']
- ['users_settings-send-as-smime-info-list.md', 'Users', 'Settings Send As Smime Info List']
- ['users_settings-send-as-smime-info-set-default.md', 'Users', 'Settings Send As Smime Info Set Default']
- ['users_settings-send-as-update.md', 'Users', 'Settings Send As Update']
- ['users_settings-send-as-verify.md', 'Users', 'Settings Send As Verify']
- ['users_settings-update-auto-forwarding.md', 'Users', 'Settings Update Auto Forwarding']
- ['users_settings-update-imap.md', 'Users', 'Settings Update Imap']
- ['users_settings-update-pop.md', 'Users', 'Settings Update Pop']
- ['users_settings-update-vacation.md', 'Users', 'Settings Update Vacation']
- ['users_stop.md', 'Users', 'Stop']
- ['users_threads-delete.md', 'Users', 'Threads Delete']
- ['users_threads-get.md', 'Users', 'Threads Get']
- ['users_threads-list.md', 'Users', 'Threads List']
- ['users_threads-modify.md', 'Users', 'Threads Modify']
- ['users_threads-trash.md', 'Users', 'Threads Trash']
- ['users_threads-untrash.md', 'Users', 'Threads Untrash']
- ['users_watch.md', 'Users', 'Watch']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

