site_name: Ad Experience Report v1.0.7+20180911
site_url: http://byron.github.io/google-apis-rs/google-adexperiencereport1-cli
site_description: A complete library to interact with Ad Experience Report (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/adexperiencereport1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['sites_get.md', 'Sites', 'Get']
- ['violating-sites_list.md', 'Violating Sites', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

