site_name: Firebase Cloud Messaging v1.0.13+20200406
site_url: http://byron.github.io/google-apis-rs/google-fcm1-cli
site_description: A complete library to interact with Firebase Cloud Messaging (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/fcm1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_messages-send.md', 'Projects', 'Messages Send']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

