site_name: Cloud Resource Manager v1.0.8+20181008
site_url: http://byron.github.io/google-apis-rs/google-cloudresourcemanager2-cli
site_description: A complete library to interact with Cloud Resource Manager (protocol v2)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/cloudresourcemanager2-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['folders_create.md', 'Folders', 'Create']
- ['folders_delete.md', 'Folders', 'Delete']
- ['folders_get.md', 'Folders', 'Get']
- ['folders_get-iam-policy.md', 'Folders', 'Get Iam Policy']
- ['folders_list.md', 'Folders', 'List']
- ['folders_move.md', 'Folders', 'Move']
- ['folders_patch.md', 'Folders', 'Patch']
- ['folders_search.md', 'Folders', 'Search']
- ['folders_set-iam-policy.md', 'Folders', 'Set Iam Policy']
- ['folders_test-iam-permissions.md', 'Folders', 'Test Iam Permissions']
- ['folders_undelete.md', 'Folders', 'Undelete']
- ['operations_get.md', 'Operations', 'Get']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

