site_name: Indexing v5.0.3+20230117
site_url: http://byron.github.io/google-apis-rs/google-indexing3-cli
site_description: A complete library to interact with Indexing (protocol v3)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/indexing3-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Url Notifications':
    - 'Get Metadata': 'url-notifications_get-metadata.md'
    - 'Publish': 'url-notifications_publish.md'

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

