site_name: sasportal v2.0.5+20210330
site_url: http://byron.github.io/google-apis-rs/google-sasportal1_alpha1-cli
site_description: A complete library to interact with sasportal (protocol v1alpha1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/sasportal1_alpha1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['customers_deployments-create.md', 'Customers', 'Deployments Create']
- ['customers_deployments-delete.md', 'Customers', 'Deployments Delete']
- ['customers_deployments-devices-create.md', 'Customers', 'Deployments Devices Create']
- ['customers_deployments-devices-create-signed.md', 'Customers', 'Deployments Devices Create Signed']
- ['customers_deployments-devices-list.md', 'Customers', 'Deployments Devices List']
- ['customers_deployments-get.md', 'Customers', 'Deployments Get']
- ['customers_deployments-list.md', 'Customers', 'Deployments List']
- ['customers_deployments-move.md', 'Customers', 'Deployments Move']
- ['customers_deployments-patch.md', 'Customers', 'Deployments Patch']
- ['customers_devices-create.md', 'Customers', 'Devices Create']
- ['customers_devices-create-signed.md', 'Customers', 'Devices Create Signed']
- ['customers_devices-delete.md', 'Customers', 'Devices Delete']
- ['customers_devices-get.md', 'Customers', 'Devices Get']
- ['customers_devices-list.md', 'Customers', 'Devices List']
- ['customers_devices-move.md', 'Customers', 'Devices Move']
- ['customers_devices-patch.md', 'Customers', 'Devices Patch']
- ['customers_devices-sign-device.md', 'Customers', 'Devices Sign Device']
- ['customers_devices-update-signed.md', 'Customers', 'Devices Update Signed']
- ['customers_get.md', 'Customers', 'Get']
- ['customers_list.md', 'Customers', 'List']
- ['customers_nodes-create.md', 'Customers', 'Nodes Create']
- ['customers_nodes-delete.md', 'Customers', 'Nodes Delete']
- ['customers_nodes-deployments-create.md', 'Customers', 'Nodes Deployments Create']
- ['customers_nodes-deployments-list.md', 'Customers', 'Nodes Deployments List']
- ['customers_nodes-devices-create.md', 'Customers', 'Nodes Devices Create']
- ['customers_nodes-devices-create-signed.md', 'Customers', 'Nodes Devices Create Signed']
- ['customers_nodes-devices-list.md', 'Customers', 'Nodes Devices List']
- ['customers_nodes-get.md', 'Customers', 'Nodes Get']
- ['customers_nodes-list.md', 'Customers', 'Nodes List']
- ['customers_nodes-move.md', 'Customers', 'Nodes Move']
- ['customers_nodes-nodes-create.md', 'Customers', 'Nodes Nodes Create']
- ['customers_nodes-nodes-list.md', 'Customers', 'Nodes Nodes List']
- ['customers_nodes-patch.md', 'Customers', 'Nodes Patch']
- ['customers_patch.md', 'Customers', 'Patch']
- ['deployments_devices-delete.md', 'Deployments', 'Devices Delete']
- ['deployments_devices-get.md', 'Deployments', 'Devices Get']
- ['deployments_devices-move.md', 'Deployments', 'Devices Move']
- ['deployments_devices-patch.md', 'Deployments', 'Devices Patch']
- ['deployments_devices-sign-device.md', 'Deployments', 'Devices Sign Device']
- ['deployments_devices-update-signed.md', 'Deployments', 'Devices Update Signed']
- ['deployments_get.md', 'Deployments', 'Get']
- ['installer_generate-secret.md', 'Installer', 'Generate Secret']
- ['installer_validate.md', 'Installer', 'Validate']
- ['nodes_deployments-delete.md', 'Nodes', 'Deployments Delete']
- ['nodes_deployments-devices-create.md', 'Nodes', 'Deployments Devices Create']
- ['nodes_deployments-devices-create-signed.md', 'Nodes', 'Deployments Devices Create Signed']
- ['nodes_deployments-devices-list.md', 'Nodes', 'Deployments Devices List']
- ['nodes_deployments-get.md', 'Nodes', 'Deployments Get']
- ['nodes_deployments-list.md', 'Nodes', 'Deployments List']
- ['nodes_deployments-move.md', 'Nodes', 'Deployments Move']
- ['nodes_deployments-patch.md', 'Nodes', 'Deployments Patch']
- ['nodes_devices-create.md', 'Nodes', 'Devices Create']
- ['nodes_devices-create-signed.md', 'Nodes', 'Devices Create Signed']
- ['nodes_devices-delete.md', 'Nodes', 'Devices Delete']
- ['nodes_devices-get.md', 'Nodes', 'Devices Get']
- ['nodes_devices-list.md', 'Nodes', 'Devices List']
- ['nodes_devices-move.md', 'Nodes', 'Devices Move']
- ['nodes_devices-patch.md', 'Nodes', 'Devices Patch']
- ['nodes_devices-sign-device.md', 'Nodes', 'Devices Sign Device']
- ['nodes_devices-update-signed.md', 'Nodes', 'Devices Update Signed']
- ['nodes_get.md', 'Nodes', 'Get']
- ['nodes_nodes-create.md', 'Nodes', 'Nodes Create']
- ['nodes_nodes-delete.md', 'Nodes', 'Nodes Delete']
- ['nodes_nodes-deployments-create.md', 'Nodes', 'Nodes Deployments Create']
- ['nodes_nodes-deployments-list.md', 'Nodes', 'Nodes Deployments List']
- ['nodes_nodes-devices-create.md', 'Nodes', 'Nodes Devices Create']
- ['nodes_nodes-devices-create-signed.md', 'Nodes', 'Nodes Devices Create Signed']
- ['nodes_nodes-devices-list.md', 'Nodes', 'Nodes Devices List']
- ['nodes_nodes-get.md', 'Nodes', 'Nodes Get']
- ['nodes_nodes-list.md', 'Nodes', 'Nodes List']
- ['nodes_nodes-move.md', 'Nodes', 'Nodes Move']
- ['nodes_nodes-nodes-create.md', 'Nodes', 'Nodes Nodes Create']
- ['nodes_nodes-nodes-list.md', 'Nodes', 'Nodes Nodes List']
- ['nodes_nodes-patch.md', 'Nodes', 'Nodes Patch']
- ['policies_get.md', 'Policies', 'Get']
- ['policies_set.md', 'Policies', 'Set']
- ['policies_test.md', 'Policies', 'Test']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

