site_name: AI Platform Notebooks v2.0.0+20210305
site_url: http://byron.github.io/google-apis-rs/google-notebooks1-cli
site_description: A complete library to interact with AI Platform Notebooks (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/notebooks1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_locations-environments-create.md', 'Projects', 'Locations Environments Create']
- ['projects_locations-environments-delete.md', 'Projects', 'Locations Environments Delete']
- ['projects_locations-environments-get.md', 'Projects', 'Locations Environments Get']
- ['projects_locations-environments-list.md', 'Projects', 'Locations Environments List']
- ['projects_locations-executions-create.md', 'Projects', 'Locations Executions Create']
- ['projects_locations-executions-delete.md', 'Projects', 'Locations Executions Delete']
- ['projects_locations-executions-get.md', 'Projects', 'Locations Executions Get']
- ['projects_locations-executions-list.md', 'Projects', 'Locations Executions List']
- ['projects_locations-get.md', 'Projects', 'Locations Get']
- ['projects_locations-instances-create.md', 'Projects', 'Locations Instances Create']
- ['projects_locations-instances-delete.md', 'Projects', 'Locations Instances Delete']
- ['projects_locations-instances-get.md', 'Projects', 'Locations Instances Get']
- ['projects_locations-instances-get-iam-policy.md', 'Projects', 'Locations Instances Get Iam Policy']
- ['projects_locations-instances-get-instance-health.md', 'Projects', 'Locations Instances Get Instance Health']
- ['projects_locations-instances-is-upgradeable.md', 'Projects', 'Locations Instances Is Upgradeable']
- ['projects_locations-instances-list.md', 'Projects', 'Locations Instances List']
- ['projects_locations-instances-register.md', 'Projects', 'Locations Instances Register']
- ['projects_locations-instances-report.md', 'Projects', 'Locations Instances Report']
- ['projects_locations-instances-reset.md', 'Projects', 'Locations Instances Reset']
- ['projects_locations-instances-set-accelerator.md', 'Projects', 'Locations Instances Set Accelerator']
- ['projects_locations-instances-set-iam-policy.md', 'Projects', 'Locations Instances Set Iam Policy']
- ['projects_locations-instances-set-labels.md', 'Projects', 'Locations Instances Set Labels']
- ['projects_locations-instances-set-machine-type.md', 'Projects', 'Locations Instances Set Machine Type']
- ['projects_locations-instances-start.md', 'Projects', 'Locations Instances Start']
- ['projects_locations-instances-stop.md', 'Projects', 'Locations Instances Stop']
- ['projects_locations-instances-test-iam-permissions.md', 'Projects', 'Locations Instances Test Iam Permissions']
- ['projects_locations-instances-upgrade.md', 'Projects', 'Locations Instances Upgrade']
- ['projects_locations-instances-upgrade-internal.md', 'Projects', 'Locations Instances Upgrade Internal']
- ['projects_locations-list.md', 'Projects', 'Locations List']
- ['projects_locations-operations-cancel.md', 'Projects', 'Locations Operations Cancel']
- ['projects_locations-operations-delete.md', 'Projects', 'Locations Operations Delete']
- ['projects_locations-operations-get.md', 'Projects', 'Locations Operations Get']
- ['projects_locations-operations-list.md', 'Projects', 'Locations Operations List']
- ['projects_locations-schedules-create.md', 'Projects', 'Locations Schedules Create']
- ['projects_locations-schedules-delete.md', 'Projects', 'Locations Schedules Delete']
- ['projects_locations-schedules-get.md', 'Projects', 'Locations Schedules Get']
- ['projects_locations-schedules-list.md', 'Projects', 'Locations Schedules List']
- ['projects_locations-schedules-trigger.md', 'Projects', 'Locations Schedules Trigger']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

