site_name: directory v1.0.7+20180917
site_url: http://byron.github.io/google-apis-rs/google-admin1_directory-cli
site_description: A complete library to interact with directory (protocol directory_v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/admin1_directory-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['asps_delete.md', 'Asps', 'Delete']
- ['asps_get.md', 'Asps', 'Get']
- ['asps_list.md', 'Asps', 'List']
- ['channels_stop.md', 'Channels', 'Stop']
- ['chromeosdevices_action.md', 'Chromeosdevices', 'Action']
- ['chromeosdevices_get.md', 'Chromeosdevices', 'Get']
- ['chromeosdevices_list.md', 'Chromeosdevices', 'List']
- ['chromeosdevices_move-devices-to-ou.md', 'Chromeosdevices', 'Move Devices To Ou']
- ['chromeosdevices_patch.md', 'Chromeosdevices', 'Patch']
- ['chromeosdevices_update.md', 'Chromeosdevices', 'Update']
- ['customers_get.md', 'Customers', 'Get']
- ['customers_patch.md', 'Customers', 'Patch']
- ['customers_update.md', 'Customers', 'Update']
- ['domain-aliases_delete.md', 'Domain Aliases', 'Delete']
- ['domain-aliases_get.md', 'Domain Aliases', 'Get']
- ['domain-aliases_insert.md', 'Domain Aliases', 'Insert']
- ['domain-aliases_list.md', 'Domain Aliases', 'List']
- ['domains_delete.md', 'Domains', 'Delete']
- ['domains_get.md', 'Domains', 'Get']
- ['domains_insert.md', 'Domains', 'Insert']
- ['domains_list.md', 'Domains', 'List']
- ['groups_aliases-delete.md', 'Groups', 'Aliases Delete']
- ['groups_aliases-insert.md', 'Groups', 'Aliases Insert']
- ['groups_aliases-list.md', 'Groups', 'Aliases List']
- ['groups_delete.md', 'Groups', 'Delete']
- ['groups_get.md', 'Groups', 'Get']
- ['groups_insert.md', 'Groups', 'Insert']
- ['groups_list.md', 'Groups', 'List']
- ['groups_patch.md', 'Groups', 'Patch']
- ['groups_update.md', 'Groups', 'Update']
- ['members_delete.md', 'Members', 'Delete']
- ['members_get.md', 'Members', 'Get']
- ['members_has-member.md', 'Members', 'Has Member']
- ['members_insert.md', 'Members', 'Insert']
- ['members_list.md', 'Members', 'List']
- ['members_patch.md', 'Members', 'Patch']
- ['members_update.md', 'Members', 'Update']
- ['mobiledevices_action.md', 'Mobiledevices', 'Action']
- ['mobiledevices_delete.md', 'Mobiledevices', 'Delete']
- ['mobiledevices_get.md', 'Mobiledevices', 'Get']
- ['mobiledevices_list.md', 'Mobiledevices', 'List']
- ['notifications_delete.md', 'Notifications', 'Delete']
- ['notifications_get.md', 'Notifications', 'Get']
- ['notifications_list.md', 'Notifications', 'List']
- ['notifications_patch.md', 'Notifications', 'Patch']
- ['notifications_update.md', 'Notifications', 'Update']
- ['orgunits_delete.md', 'Orgunits', 'Delete']
- ['orgunits_get.md', 'Orgunits', 'Get']
- ['orgunits_insert.md', 'Orgunits', 'Insert']
- ['orgunits_list.md', 'Orgunits', 'List']
- ['orgunits_patch.md', 'Orgunits', 'Patch']
- ['orgunits_update.md', 'Orgunits', 'Update']
- ['privileges_list.md', 'Privileges', 'List']
- ['resolved-app-access-settings_get-settings.md', 'Resolved App Access Settings', 'Get Settings']
- ['resolved-app-access-settings_list-trusted-apps.md', 'Resolved App Access Settings', 'List Trusted Apps']
- ['resources_buildings-delete.md', 'Resources', 'Buildings Delete']
- ['resources_buildings-get.md', 'Resources', 'Buildings Get']
- ['resources_buildings-insert.md', 'Resources', 'Buildings Insert']
- ['resources_buildings-list.md', 'Resources', 'Buildings List']
- ['resources_buildings-patch.md', 'Resources', 'Buildings Patch']
- ['resources_buildings-update.md', 'Resources', 'Buildings Update']
- ['resources_calendars-delete.md', 'Resources', 'Calendars Delete']
- ['resources_calendars-get.md', 'Resources', 'Calendars Get']
- ['resources_calendars-insert.md', 'Resources', 'Calendars Insert']
- ['resources_calendars-list.md', 'Resources', 'Calendars List']
- ['resources_calendars-patch.md', 'Resources', 'Calendars Patch']
- ['resources_calendars-update.md', 'Resources', 'Calendars Update']
- ['resources_features-delete.md', 'Resources', 'Features Delete']
- ['resources_features-get.md', 'Resources', 'Features Get']
- ['resources_features-insert.md', 'Resources', 'Features Insert']
- ['resources_features-list.md', 'Resources', 'Features List']
- ['resources_features-patch.md', 'Resources', 'Features Patch']
- ['resources_features-rename.md', 'Resources', 'Features Rename']
- ['resources_features-update.md', 'Resources', 'Features Update']
- ['role-assignments_delete.md', 'Role Assignments', 'Delete']
- ['role-assignments_get.md', 'Role Assignments', 'Get']
- ['role-assignments_insert.md', 'Role Assignments', 'Insert']
- ['role-assignments_list.md', 'Role Assignments', 'List']
- ['roles_delete.md', 'Roles', 'Delete']
- ['roles_get.md', 'Roles', 'Get']
- ['roles_insert.md', 'Roles', 'Insert']
- ['roles_list.md', 'Roles', 'List']
- ['roles_patch.md', 'Roles', 'Patch']
- ['roles_update.md', 'Roles', 'Update']
- ['schemas_delete.md', 'Schemas', 'Delete']
- ['schemas_get.md', 'Schemas', 'Get']
- ['schemas_insert.md', 'Schemas', 'Insert']
- ['schemas_list.md', 'Schemas', 'List']
- ['schemas_patch.md', 'Schemas', 'Patch']
- ['schemas_update.md', 'Schemas', 'Update']
- ['tokens_delete.md', 'Tokens', 'Delete']
- ['tokens_get.md', 'Tokens', 'Get']
- ['tokens_list.md', 'Tokens', 'List']
- ['users_aliases-delete.md', 'Users', 'Aliases Delete']
- ['users_aliases-insert.md', 'Users', 'Aliases Insert']
- ['users_aliases-list.md', 'Users', 'Aliases List']
- ['users_aliases-watch.md', 'Users', 'Aliases Watch']
- ['users_delete.md', 'Users', 'Delete']
- ['users_get.md', 'Users', 'Get']
- ['users_insert.md', 'Users', 'Insert']
- ['users_list.md', 'Users', 'List']
- ['users_make-admin.md', 'Users', 'Make Admin']
- ['users_patch.md', 'Users', 'Patch']
- ['users_photos-delete.md', 'Users', 'Photos Delete']
- ['users_photos-get.md', 'Users', 'Photos Get']
- ['users_photos-patch.md', 'Users', 'Photos Patch']
- ['users_photos-update.md', 'Users', 'Photos Update']
- ['users_undelete.md', 'Users', 'Undelete']
- ['users_update.md', 'Users', 'Update']
- ['users_watch.md', 'Users', 'Watch']
- ['verification-codes_generate.md', 'Verification Codes', 'Generate']
- ['verification-codes_invalidate.md', 'Verification Codes', 'Invalidate']
- ['verification-codes_list.md', 'Verification Codes', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

