site_name: manager v1.0.3+20140915
site_url: http://byron.github.io/google-apis-rs/google-manager1_beta2-cli
site_description: A complete library to interact with manager (protocol v1beta2)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/manager1_beta2-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['deployments_delete.md', 'Deployments', 'Delete']
- ['deployments_get.md', 'Deployments', 'Get']
- ['deployments_insert.md', 'Deployments', 'Insert']
- ['deployments_list.md', 'Deployments', 'List']
- ['templates_delete.md', 'Templates', 'Delete']
- ['templates_get.md', 'Templates', 'Get']
- ['templates_insert.md', 'Templates', 'Insert']
- ['templates_list.md', 'Templates', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

