site_name: Partners v1.0.7+20180925
site_url: http://byron.github.io/google-apis-rs/google-partners2-cli
site_description: A complete library to interact with Partners (protocol v2)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/partners2-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['analytics_list.md', 'Analytics', 'List']
- ['client-messages_log.md', 'Client Messages', 'Log']
- ['companies_get.md', 'Companies', 'Get']
- ['companies_leads-create.md', 'Companies', 'Leads Create']
- ['companies_list.md', 'Companies', 'List']
- ['leads_list.md', 'Leads', 'List']
- ['methods_get-partnersstatus.md', 'Methods', 'Get Partnersstatus']
- ['methods_update-companies.md', 'Methods', 'Update Companies']
- ['methods_update-leads.md', 'Methods', 'Update Leads']
- ['offers_history-list.md', 'Offers', 'History List']
- ['offers_list.md', 'Offers', 'List']
- ['user-events_log.md', 'User Events', 'Log']
- ['user-states_list.md', 'User States', 'List']
- ['users_create-company-relation.md', 'Users', 'Create Company Relation']
- ['users_delete-company-relation.md', 'Users', 'Delete Company Relation']
- ['users_get.md', 'Users', 'Get']
- ['users_update-profile.md', 'Users', 'Update Profile']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

