site_name: BigQuery Connection Service v2.0.3+20210326
site_url: http://byron.github.io/google-apis-rs/google-bigqueryconnection1_beta1-cli
site_description: A complete library to interact with BigQuery Connection Service (protocol v1beta1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/bigqueryconnection1_beta1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_locations-connections-create.md', 'Projects', 'Locations Connections Create']
- ['projects_locations-connections-delete.md', 'Projects', 'Locations Connections Delete']
- ['projects_locations-connections-get.md', 'Projects', 'Locations Connections Get']
- ['projects_locations-connections-get-iam-policy.md', 'Projects', 'Locations Connections Get Iam Policy']
- ['projects_locations-connections-list.md', 'Projects', 'Locations Connections List']
- ['projects_locations-connections-patch.md', 'Projects', 'Locations Connections Patch']
- ['projects_locations-connections-set-iam-policy.md', 'Projects', 'Locations Connections Set Iam Policy']
- ['projects_locations-connections-test-iam-permissions.md', 'Projects', 'Locations Connections Test Iam Permissions']
- ['projects_locations-connections-update-credential.md', 'Projects', 'Locations Connections Update Credential']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

