site_name: bigquery v1.0.10+20190630
site_url: http://byron.github.io/google-apis-rs/google-bigquery2-cli
site_description: A complete library to interact with bigquery (protocol v2)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/bigquery2-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['datasets_delete.md', 'Datasets', 'Delete']
- ['datasets_get.md', 'Datasets', 'Get']
- ['datasets_insert.md', 'Datasets', 'Insert']
- ['datasets_list.md', 'Datasets', 'List']
- ['datasets_patch.md', 'Datasets', 'Patch']
- ['datasets_update.md', 'Datasets', 'Update']
- ['jobs_cancel.md', 'Jobs', 'Cancel']
- ['jobs_get.md', 'Jobs', 'Get']
- ['jobs_get-query-results.md', 'Jobs', 'Get Query Results']
- ['jobs_insert.md', 'Jobs', 'Insert']
- ['jobs_list.md', 'Jobs', 'List']
- ['jobs_query.md', 'Jobs', 'Query']
- ['models_delete.md', 'Models', 'Delete']
- ['models_get.md', 'Models', 'Get']
- ['models_list.md', 'Models', 'List']
- ['models_patch.md', 'Models', 'Patch']
- ['projects_get-service-account.md', 'Projects', 'Get Service Account']
- ['projects_list.md', 'Projects', 'List']
- ['routines_delete.md', 'Routines', 'Delete']
- ['routines_get.md', 'Routines', 'Get']
- ['routines_insert.md', 'Routines', 'Insert']
- ['routines_list.md', 'Routines', 'List']
- ['routines_update.md', 'Routines', 'Update']
- ['tabledata_insert-all.md', 'Tabledata', 'Insert All']
- ['tabledata_list.md', 'Tabledata', 'List']
- ['tables_delete.md', 'Tables', 'Delete']
- ['tables_get.md', 'Tables', 'Get']
- ['tables_insert.md', 'Tables', 'Insert']
- ['tables_list.md', 'Tables', 'List']
- ['tables_patch.md', 'Tables', 'Patch']
- ['tables_update.md', 'Tables', 'Update']

theme: readthedocs

copyright: Copyright &copy; 2015-2019, `Sebastian Thiel`

