site_name: Cloud Monitoring v1.0.6+20170501
site_url: http://byron.github.io/google-apis-rs/google-cloudmonitoring2_beta2-cli
site_description: A complete library to interact with Cloud Monitoring (protocol v2beta2)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/cloudmonitoring2_beta2-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['metric-descriptors_create.md', 'Metric Descriptors', 'Create']
- ['metric-descriptors_delete.md', 'Metric Descriptors', 'Delete']
- ['metric-descriptors_list.md', 'Metric Descriptors', 'List']
- ['timeseries_list.md', 'Timeseries', 'List']
- ['timeseries_write.md', 'Timeseries', 'Write']
- ['timeseries-descriptors_list.md', 'Timeseries Descriptors', 'List']

theme: readthedocs

copyright: Copyright &copy; 2015-2016, `Sebastian Thiel`

