site_name: Cloud Trace v5.0.3+20230112
site_url: http://byron.github.io/google-apis-rs/google-cloudtrace1-cli
site_description: A complete library to interact with Cloud Trace (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/cloudtrace1-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Projects':
    - 'Patch Traces': 'projects_patch-traces.md'
    - 'Traces Get': 'projects_traces-get.md'
    - 'Traces List': 'projects_traces-list.md'

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

