site_name: Access Approval v5.0.5+20240621
site_url: http://byron.github.io/google-apis-rs/google-accessapproval1-cli
site_description: A complete library to interact with Access Approval (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/accessapproval1-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Folders':
    - 'Approval Requests Approve': 'folders_approval-requests-approve.md'
    - 'Approval Requests Dismiss': 'folders_approval-requests-dismiss.md'
    - 'Approval Requests Get': 'folders_approval-requests-get.md'
    - 'Approval Requests Invalidate': 'folders_approval-requests-invalidate.md'
    - 'Approval Requests List': 'folders_approval-requests-list.md'
    - 'Delete Access Approval Settings': 'folders_delete-access-approval-settings.md'
    - 'Get Access Approval Settings': 'folders_get-access-approval-settings.md'
    - 'Get Service Account': 'folders_get-service-account.md'
    - 'Update Access Approval Settings': 'folders_update-access-approval-settings.md'
- 'Organizations':
    - 'Approval Requests Approve': 'organizations_approval-requests-approve.md'
    - 'Approval Requests Dismiss': 'organizations_approval-requests-dismiss.md'
    - 'Approval Requests Get': 'organizations_approval-requests-get.md'
    - 'Approval Requests Invalidate': 'organizations_approval-requests-invalidate.md'
    - 'Approval Requests List': 'organizations_approval-requests-list.md'
    - 'Delete Access Approval Settings': 'organizations_delete-access-approval-settings.md'
    - 'Get Access Approval Settings': 'organizations_get-access-approval-settings.md'
    - 'Get Service Account': 'organizations_get-service-account.md'
    - 'Update Access Approval Settings': 'organizations_update-access-approval-settings.md'
- 'Projects':
    - 'Approval Requests Approve': 'projects_approval-requests-approve.md'
    - 'Approval Requests Dismiss': 'projects_approval-requests-dismiss.md'
    - 'Approval Requests Get': 'projects_approval-requests-get.md'
    - 'Approval Requests Invalidate': 'projects_approval-requests-invalidate.md'
    - 'Approval Requests List': 'projects_approval-requests-list.md'
    - 'Delete Access Approval Settings': 'projects_delete-access-approval-settings.md'
    - 'Get Access Approval Settings': 'projects_get-access-approval-settings.md'
    - 'Get Service Account': 'projects_get-service-account.md'
    - 'Update Access Approval Settings': 'projects_update-access-approval-settings.md'

theme: readthedocs

copyright: Copyright &copy; 2015â€“2024, `Sebastian Thiel`

