site_name: Service Directory v3.0.0+20220224
site_url: http://byron.github.io/google-apis-rs/google-servicedirectory1-cli
site_description: A complete library to interact with Service Directory (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/servicedirectory1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['projects_locations-get.md', 'Projects', 'Locations Get']
- ['projects_locations-list.md', 'Projects', 'Locations List']
- ['projects_locations-namespaces-create.md', 'Projects', 'Locations Namespaces Create']
- ['projects_locations-namespaces-delete.md', 'Projects', 'Locations Namespaces Delete']
- ['projects_locations-namespaces-get.md', 'Projects', 'Locations Namespaces Get']
- ['projects_locations-namespaces-get-iam-policy.md', 'Projects', 'Locations Namespaces Get Iam Policy']
- ['projects_locations-namespaces-list.md', 'Projects', 'Locations Namespaces List']
- ['projects_locations-namespaces-patch.md', 'Projects', 'Locations Namespaces Patch']
- ['projects_locations-namespaces-services-create.md', 'Projects', 'Locations Namespaces Services Create']
- ['projects_locations-namespaces-services-delete.md', 'Projects', 'Locations Namespaces Services Delete']
- ['projects_locations-namespaces-services-endpoints-create.md', 'Projects', 'Locations Namespaces Services Endpoints Create']
- ['projects_locations-namespaces-services-endpoints-delete.md', 'Projects', 'Locations Namespaces Services Endpoints Delete']
- ['projects_locations-namespaces-services-endpoints-get.md', 'Projects', 'Locations Namespaces Services Endpoints Get']
- ['projects_locations-namespaces-services-endpoints-list.md', 'Projects', 'Locations Namespaces Services Endpoints List']
- ['projects_locations-namespaces-services-endpoints-patch.md', 'Projects', 'Locations Namespaces Services Endpoints Patch']
- ['projects_locations-namespaces-services-get.md', 'Projects', 'Locations Namespaces Services Get']
- ['projects_locations-namespaces-services-get-iam-policy.md', 'Projects', 'Locations Namespaces Services Get Iam Policy']
- ['projects_locations-namespaces-services-list.md', 'Projects', 'Locations Namespaces Services List']
- ['projects_locations-namespaces-services-patch.md', 'Projects', 'Locations Namespaces Services Patch']
- ['projects_locations-namespaces-services-resolve.md', 'Projects', 'Locations Namespaces Services Resolve']
- ['projects_locations-namespaces-services-set-iam-policy.md', 'Projects', 'Locations Namespaces Services Set Iam Policy']
- ['projects_locations-namespaces-services-test-iam-permissions.md', 'Projects', 'Locations Namespaces Services Test Iam Permissions']
- ['projects_locations-namespaces-set-iam-policy.md', 'Projects', 'Locations Namespaces Set Iam Policy']
- ['projects_locations-namespaces-test-iam-permissions.md', 'Projects', 'Locations Namespaces Test Iam Permissions']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

