site_name: Payments Reseller Subscription v7.0.0+20251210
site_url: http://byron.github.io/google-apis-rs/google-paymentsresellersubscription1-cli
site_description: A complete library to interact with Payments Reseller Subscription (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/main/gen/paymentsresellersubscription1-cli

docs_dir: docs
site_dir: build_html

nav:
- Home: 'index.md'
- 'Partners':
    - 'Products List': 'partners_products-list.md'
    - 'Promotions Find Eligible': 'partners_promotions-find-eligible.md'
    - 'Promotions List': 'partners_promotions-list.md'
    - 'Subscriptions Cancel': 'partners_subscriptions-cancel.md'
    - 'Subscriptions Create': 'partners_subscriptions-create.md'
    - 'Subscriptions Entitle': 'partners_subscriptions-entitle.md'
    - 'Subscriptions Extend': 'partners_subscriptions-extend.md'
    - 'Subscriptions Get': 'partners_subscriptions-get.md'
    - 'Subscriptions Line Items Patch': 'partners_subscriptions-line-items-patch.md'
    - 'Subscriptions Provision': 'partners_subscriptions-provision.md'
    - 'Subscriptions Resume': 'partners_subscriptions-resume.md'
    - 'Subscriptions Suspend': 'partners_subscriptions-suspend.md'
    - 'Subscriptions Undo Cancel': 'partners_subscriptions-undo-cancel.md'
    - 'User Sessions Generate': 'partners_user-sessions-generate.md'

theme: readthedocs

copyright: Copyright &copy; 2015â€“2024, `Sebastian Thiel`
