site_name: Play Movies v1.0.13+20170919
site_url: http://byron.github.io/google-apis-rs/google-playmoviespartner1-cli
site_description: A complete library to interact with Play Movies (protocol v1)

repo_url: https://github.com/Byron/google-apis-rs/tree/master/gen/playmoviespartner1-cli

docs_dir: docs
site_dir: build_html

pages:
- ['index.md', 'Home']
- ['accounts_avails-get.md', 'Accounts', 'Avails Get']
- ['accounts_avails-list.md', 'Accounts', 'Avails List']
- ['accounts_orders-get.md', 'Accounts', 'Orders Get']
- ['accounts_orders-list.md', 'Accounts', 'Orders List']
- ['accounts_store-infos-country-get.md', 'Accounts', 'Store Infos Country Get']
- ['accounts_store-infos-list.md', 'Accounts', 'Store Infos List']

theme: readthedocs

copyright: Copyright &copy; 2015-2020, `Sebastian Thiel`

